//! The multi-machine Renode `.resc` renderer (TASK-0049.05 / TASK-0450
//! split).

use super::plan::TransportPlan;

/// axiSram base address the input fixture is injected at (matches the
/// single-machine `tests/renode/embedded/run.resc` + the shim's
/// `NUC_INPUT_REGION`). Mapped in the platform, NOT in `memory.x`, so the
/// stack/.bss never collide with the injected bytes.
const AXISRAM_BASE: &str = "0x24000000";

/// Render the multi-machine Renode `.resc` that co-simulates one machine
/// per worker, wires them on the plan's `UARTHub`s, and start-gates the
/// boot so receivers enable RX before senders transmit (TASK-0049.05).
///
/// The caller (the `renode-multimcu` just recipe) injects, before
/// `include`-ing this script:
///   * `$<worker>Bin` = @<path to that worker's cross-compiled ELF>, one
///     per used worker (e.g. `$hostBin`, `$w0Bin`);
///   * the OUTPUT-CAPTURE file var(s) the saver USART1(s) write to
///     (TASK-0049.10.05): with EXACTLY ONE saver this is the single
///     `$uartFile` (byte-identical to pre-C2; the `renode-multimcu` recipe
///     injects/reads it for 02-split-add `host`); with ≥2 savers each saver
///     gets a DISTINCT `$<worker>Uart` (ex14 `$feUart`, `$rfUart`) — the
///     exact vars + their reference-layout concatenation order are
///     [`TransportPlan::output_captures`] (decl-order, slice D concatenates
///     in that order);
///   * `$input`        = @<path to the input.bin injected into loaders>.
pub(crate) fn render_multimachine_resc(plan: &TransportPlan) -> String {
    use std::fmt::Write as _;
    let mut s = String::new();
    let worker_names: Vec<&str> = plan.workers.values().map(|w| w.name.as_str()).collect();

    writeln!(s, ":name: nucleus-m11-multimcu").ok();
    writeln!(
        s,
        ":description: Co-simulate {} STM32H7 MCUs ({}) wired by UARTHub(s); \
         generated by the embedded-pattern backend (TASK-0049.05).",
        worker_names.len(),
        worker_names.join(", ")
    )
    .ok();
    s.push('\n');
    s.push_str(
        "# GENERATED multi-machine Renode script (embedded-pattern, M11 BIN).\n\
         # Do not edit; rerun `nucleus build --shim stm32h7` on a multi-worker\n\
         # schedule to regenerate. One machine per worker, wired by a UARTHub\n\
         # per CHANNEL (SeqTag) (Renode's UARTHub is a broadcast bus; a\n\
         # dedicated hub per channel keeps every transport stream on its own\n\
         # byte FIFO, so two same-direction channels between one worker pair\n\
         # never cross — TASK-0049.05.02).\n\
         #\n\
         # START-GATING (load-bearing, TASK-0049.01): Renode's\n\
         # UARTBase.WriteChar DROPS bytes that arrive before the receiver\n\
         # enables RX. Each firmware enables RX on all its link USARTs as its\n\
         # FIRST action; this script releases the machines in a staged order\n\
         # computed so a worker's first transmit to a peer never precedes\n\
         # that peer's release (TASK-0049.05.03 — handles the cyclic ex14\n\
         # interconnect, which has no static receivers-first sort).\n\n",
    );

    // 1. One UARTHub per channel (seq).
    for h in &plan.hubs {
        writeln!(s, "emulation CreateUARTHub \"{}\"", h.name).ok();
    }
    s.push('\n');

    // 2. One machine per worker: platform + hub connects + capture/inject.
    for plan_w in plan.workers.values() {
        writeln!(s, "mach create \"{}\"", plan_w.name).ok();
        s.push_str("machine LoadPlatformDescription @platforms/cpus/stm32h743.repl\n");
        // Connect this worker's USART for each CHANNEL (seq) to that
        // channel's dedicated hub (TASK-0049.05.02). `seq_usart` is injective
        // so each connect targets a distinct USART + distinct hub.
        for (seq, usart) in &plan_w.seq_usart {
            if let Some(h) = plan.hubs.iter().find(|h| h.seq == *seq) {
                writeln!(s, "connector Connect {} {}", usart.renode_name, h.name).ok();
            }
        }
        // Effectful-output capture (TASK-0049.10.05). Driven off the plan's
        // `output_captures` (the SINGLE SOURCE OF TRUTH for the per-saver
        // file var + drained symbol + decl-order) so the `.resc`, the shim,
        // and slice D's concat order cannot drift. Single saver -> `$uartFile`
        // (recipe-compatible, byte-identical to pre-C2); multi-saver -> each
        // saver's DISTINCT `$<worker>Uart` so they no longer collide on one
        // shared file.
        for cap in plan.output_captures.iter().filter(|c| c.worker == plan_w.worker) {
            writeln!(
                s,
                "# This worker saves output `{:?}` -> capture its USART1 to the \
                 file backend (slice D concatenates in output_captures order).",
                cap.data,
            )
            .ok();
            writeln!(s, "usart1 CreateFileBackend ${} true", cap.file_var).ok();
        }
        if plan_w.loads_input {
            writeln!(
                s,
                "# This worker loads input -> inject the fixture into axiSram @ {AXISRAM_BASE}.",
            )
            .ok();
            writeln!(s, "sysbus LoadBinary $input {AXISRAM_BASE}").ok();
        }
        s.push('\n');
    }

    // 3. Fine global quantum so the machines interleave finely (mirrors the
    //    bundled scripts/multi-node/*.resc multi-MCU UART pattern).
    s.push_str("emulation SetGlobalQuantum \"0.00001\"\n\n");

    // 4. Load every ELF (caller injects $<worker>Bin per worker).
    for plan_w in plan.workers.values() {
        writeln!(s, "mach set \"{}\"", plan_w.name).ok();
        writeln!(s, "sysbus LoadELF ${}Bin", plan_w.name).ok();
    }
    s.push('\n');

    // 5. Start-gating: halt all, then release in the simulated staged boot
    //    order (compute_boot_order) with a boot window between each so RX is
    //    enabled before any peer transmits to a machine.
    s.push_str(
        "# Hold every machine halted, then release in the staged boot order\n\
         # (TASK-0049.05.03) with a boot window between each (RX-enable\n\
         # before any peer's first TX to it).\n",
    );
    for plan_w in plan.workers.values() {
        writeln!(s, "mach set \"{}\"", plan_w.name).ok();
        s.push_str("cpu IsHalted true\n");
    }
    s.push('\n');
    for (i, w) in plan.boot_order.iter().enumerate() {
        let name = &plan.workers[w].name;
        writeln!(s, "mach set \"{name}\"").ok();
        s.push_str("cpu IsHalted false\n");
        if i + 1 < plan.boot_order.len() {
            // Boot window: let this machine run init() (enable RX on all its
            // link USARTs) and settle before the next machine is released.
            // Load-bearing — the staged boot order is only sound if each
            // machine is RX-ready before the next one starts transmitting.
            s.push_str("emulation RunFor \"0.002\"\n");
        } else {
            // Last machine released: run for a FIXED emulated-seconds window.
            // 0.3 s is sufficient for the 02-split-add single-pass case (one
            // host->w0->host hop), NOT a proof of "to completion". A deeper
            // pipeline (e.g. ex14's 4-frame x 3-MCU schedule) needs a larger
            // or save-count-gated window; sizing the window to schedule depth
            // is tracked with the unframed-multiplex transport work
            // (TASK-0049.05.02). This window is bounded + determinate.
            s.push_str("emulation RunFor \"0.3\"\n");
        }
    }
    s.push_str("quit\n");
    s
}
