//! Per-worker `src/bin/<wname>.rs` body emit. Drives the shared
//! [`backend_common::multi_worker_walker::render_worker_events`] walker
//! with `rendezvous_prefix = "chan"` (see the module-level docstring on
//! [`super`]) and emits the surrounding prelude: rendezvous-file
//! handshake (TASK-0176), Reactor + per-chan instances (TASK-0233 sized
//! from sidecar), per-barrier CTRL-channel shim structs (TASK-0172
//! contract-carried SyncTag identity), and the TASK-0327 host-relay
//! phase splice for w2w transfers.

use std::fmt::Write as _;

use nucleus_compiler::event::WorkerId;

use backend_common::check_frame::{
    collect_count_check_frames, emit_count_guard_local, emit_count_reporter_struct,
    emit_count_static,
};
use backend_common::multi_worker_walker::{self as walker, WalkerCtx};
use backend_common::render::{render_array_init_for, rust_type_of};

use super::Plan;
use super::encode::encode_decode_paths;
use super::walkers::relay_phase_insertion_point;
use crate::EmitError;

impl Plan<'_> {
    /// Render one worker's full `src/bin/<wname>.rs`.
    pub(crate) fn render_worker_program(&self, worker: WorkerId) -> Result<String, EmitError> {
        let mut out = String::new();
        let wname = self.worker_name(worker);
        let is_host = worker == self.host_worker;

        // ---- File header + modules. ----
        writeln!(
            out,
            "//! Generated by the mp-tcp-event backend (TASK-0042.05, \
             multi-process). Worker `{wname}`{}.",
            if is_host {
                " [host/server]"
            } else {
                " [client]"
            }
        )
        .ok();
        writeln!(out, "//! Do not edit; rerun `nucleus build` to regenerate.").ok();
        writeln!(out).ok();
        writeln!(out, "#[path = \"../kernels.rs\"]").ok();
        writeln!(out, "#[allow(dead_code)]").ok();
        writeln!(out, "mod kernels;").ok();
        writeln!(out, "#[path = \"../wire.rs\"]").ok();
        writeln!(out, "#[allow(dead_code)]").ok();
        writeln!(out, "mod wire;").ok();
        writeln!(out, "#[path = \"../runtime.rs\"]").ok();
        writeln!(out, "#[allow(dead_code)]").ok();
        writeln!(out, "mod runtime;").ok();
        writeln!(out).ok();

        // ---- Imports (role-specific so warning-clean). ----
        writeln!(out, "use std::fs;").ok();
        writeln!(out, "use std::path::PathBuf;").ok();
        if is_host {
            writeln!(out, "use std::net::TcpListener;").ok();
            writeln!(out, "use std::io::Write as _;").ok();
        } else {
            writeln!(out, "use std::net::TcpStream as StdTcpStream;").ok();
            writeln!(out, "use std::time::Duration;").ok();
        }
        // Host-or-not — both need these in main() for the reactor +
        // chan setup.
        writeln!(out, "use std::cell::RefCell;").ok();
        writeln!(out, "use std::rc::Rc;").ok();
        writeln!(out).ok();

        // ---- Count check_frame substrate (file scope). ----
        let count_frames = collect_count_check_frames(&self.per_worker[&worker]);
        if !count_frames.is_empty() {
            emit_count_reporter_struct(&mut out);
            for cf in &count_frames {
                emit_count_static(&mut out, &cf.ident);
            }
            writeln!(out).ok();
        }

        // ---- main(). ----
        writeln!(
            out,
            "#[allow(unused_mut, dead_code, unused_variables, \
             unused_assignments, clippy::needless_late_init)]"
        )
        .ok();
        writeln!(out, "fn main() {{").ok();

        // Per-Count-loop Drop guard local.
        for cf in &count_frames {
            emit_count_guard_local(&mut out, &cf.ident, &cf.loop_var, cf.latency_max_ns);
        }
        if !count_frames.is_empty() {
            writeln!(out).ok();
        }

        // ---- Rendezvous-file handshake + DATA/CTRL socket setup. ----
        self.emit_handshake(&mut out, worker, is_host)?;
        writeln!(out).ok();

        // ---- Build the Reactor (mio-managed DATA sockets) + chan
        //      instances. ----
        self.emit_reactor_and_chans(&mut out, worker)?;
        writeln!(out).ok();

        // ---- Pre-init locals (Wait targets + indexed Fire writes). ----
        let pre_init = self.collect_pre_init(worker)?;
        for (name, did) in &pre_init {
            let ty = self.sidecar.data_type(*did).ok_or_else(|| {
                EmitError::ContractGap(format!(
                    "pre-init data `{name}` ({did:?}) has no ResolvedType in sidecar"
                ))
            })?;
            let rty = rust_type_of(ty);
            let init = render_array_init_for(ty);
            writeln!(out, "    let mut {name}: {rty} = {init};").ok();
        }
        if !pre_init.is_empty() {
            writeln!(out).ok();
        }

        // ---- Drive the shared walker. ----
        let walker_ctx = WalkerCtx {
            names: self.names,
            sidecar: self.sidecar,
            rendezvous_prefix: "chan",
            rendezvous_ids: &self.chan_ids,
            pair_tiles: &self.pair_tiles,
        };
        // The walker emits chan_<rid>.push(...) / chan_<rid>.wait() /
        // bar_<bid>.wait() — but barriers in mp-tcp-event don't lower
        // to `bar_<bid>.wait()`. They go through CTRL-channel
        // wire::barrier_cross instead, and the walker's prefix knob
        // doesn't reach Event::Sync. So we cannot use the shared
        // walker directly for the Sync arm — we route around it by
        // emitting our own walker for Event::Sync.
        //
        // The cleanest split: emit a per-event recursive walker that
        // delegates Fire/Loop/Push/Wait to the shared walker but
        // special-cases Sync. But the shared walker is a single
        // function on a borrowed context — splitting per-event would
        // duplicate the Fire/Loop logic.
        //
        // Pragmatic solution: extend the shared walker (already
        // emitting `{prefix}bar_<tag>.wait()`) by ALSO declaring a
        // `bar_<tag>` local on this worker that's a small CTRL-channel
        // shim. The shim's `.wait()` calls wire::barrier_cross on the
        // CTRL socket. That way the walker is reused VERBATIM, and the
        // mp-tcp-event-specific work all lives in the emitted prelude.
        //
        // See emit_barrier_shims below.
        self.emit_barrier_shims(&mut out, worker, is_host)?;
        if !self.barriers_used_by(worker).is_empty() {
            writeln!(out).ok();
        }

        // TASK-0327 (cycle 149): for HOST, when the schedule has w2w
        // pushes, splice the synchronous relay phase right BEFORE the
        // LAST top-level `Event::Sync` event (= between pass-1 barrier
        // and pass-2 barrier on the 06/distributed2 reproducer). The
        // relay phase drains all worker-to-worker (seq, dst) hops
        // through host's existing reactor: `wait(seq)` blocks driving
        // the reactor (pulling frames from `data_<src>` mio sockets
        // into `inbound[seq]`); `push(seq, dst_peer, payload, cap)`
        // enqueues to `outbound[(seq, dst_peer)]` (drained on next
        // reactor turn into `data_<dst>` mio socket). Non-host workers
        // render unchanged — their `chan_<rid>` uses peer_idx=0 (host)
        // for both push and wait; host does the forwarding.
        //
        // Mirror of mp-tcp-bufsync's cycle-148 splice in
        // `nucleus/backends/mp-tcp-bufsync/src/lib.rs` `render_worker_program`.
        let host_events = &self.per_worker[&worker];
        let host_relay = if is_host {
            self.render_relay_phase(1)?
        } else {
            String::new()
        };
        if is_host && !host_relay.is_empty() {
            let split_at =
                relay_phase_insertion_point(host_events, self.per_worker, self.host_worker);
            let mut pre = String::new();
            walker::render_worker_events(
                &walker_ctx,
                worker,
                &host_events[..split_at],
                &mut pre,
                1,
                "",
            )?;
            out.push_str(&pre);
            out.push_str(&host_relay);
            let mut post = String::new();
            walker::render_worker_events(
                &walker_ctx,
                worker,
                &host_events[split_at..],
                &mut post,
                1,
                "",
            )?;
            out.push_str(&post);
        } else {
            let body = {
                let mut buf = String::new();
                walker::render_worker_events(
                    &walker_ctx,
                    worker,
                    host_events,
                    &mut buf,
                    1,
                    "",
                )?;
                buf
            };
            out.push_str(&body);
        }

        // ---- Flush outbound + close. ----
        writeln!(out).ok();
        writeln!(out, "    reactor.borrow_mut().flush_outbound();").ok();

        writeln!(out, "}}").ok();
        Ok(out)
    }

    /// Emit the rendezvous-file handshake + DATA/CTRL socket setup.
    /// Host = server, non-host = client. Identical pattern to
    /// mp-tcp-bufsync (TASK-0176); rendezvous-file mechanism is the
    /// SINGLE-ALLOCATOR pattern that closes the close-then-rebind
    /// TOCTOU window. DO NOT reintroduce the deleted
    /// `__nuc_pick_port` helper.
    fn emit_handshake(
        &self,
        out: &mut String,
        worker: WorkerId,
        is_host: bool,
    ) -> Result<(), EmitError> {
        let wname = self.worker_name(worker);
        if is_host {
            writeln!(
                out,
                "    let rendezvous_dir: PathBuf = std::env::var_os(\"NUC_RENDEZVOUS_DIR\")\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20.map(PathBuf::from)\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20.unwrap_or_else(|| panic!(\"host: NUC_RENDEZVOUS_DIR not set (run.sh must export it)\"));"
            )
            .ok();
            writeln!(out, "    let _ = &rendezvous_dir;").ok();
            // Per non-host worker: bind, publish port, accept DATA + CTRL.
            for nw in self.non_host_workers() {
                let nwn = self.worker_name(nw);
                writeln!(
                    out,
                    "    let listener_{nwn} = TcpListener::bind(\"127.0.0.1:0\")\n\
                     \x20\x20\x20\x20\x20\x20\x20\x20.unwrap_or_else(|e| panic!(\"host: bind 127.0.0.1:0 for {nwn} failed: {{e}}\"));"
                )
                .ok();
                writeln!(
                    out,
                    "    let port_{nwn}: u16 = listener_{nwn}.local_addr()\n\
                     \x20\x20\x20\x20\x20\x20\x20\x20.unwrap_or_else(|e| panic!(\"host: local_addr for {nwn} listener failed: {{e}}\"))\n\
                     \x20\x20\x20\x20\x20\x20\x20\x20.port();"
                )
                .ok();
                writeln!(
                    out,
                    "    {{\n\
                     \x20\x20\x20\x20\x20\x20\x20\x20let rdv_final = rendezvous_dir.join(\"{nwn}.port\");\n\
                     \x20\x20\x20\x20\x20\x20\x20\x20let rdv_tmp = rendezvous_dir.join(\"{nwn}.port.tmp\");\n\
                     \x20\x20\x20\x20\x20\x20\x20\x20let mut f = fs::File::create(&rdv_tmp)\n\
                     \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20.unwrap_or_else(|e| panic!(\"host: create rendezvous tmp `{{}}` for {nwn} failed: {{e}}\", rdv_tmp.display()));\n\
                     \x20\x20\x20\x20\x20\x20\x20\x20write!(f, \"{{}}\", port_{nwn})\n\
                     \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20.unwrap_or_else(|e| panic!(\"host: write port {{}} to rendezvous tmp `{{}}` for {nwn} failed: {{e}}\", port_{nwn}, rdv_tmp.display()));\n\
                     \x20\x20\x20\x20\x20\x20\x20\x20drop(f);\n\
                     \x20\x20\x20\x20\x20\x20\x20\x20fs::rename(&rdv_tmp, &rdv_final)\n\
                     \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20.unwrap_or_else(|e| panic!(\"host: rename rendezvous `{{}}` -> `{{}}` for {nwn} failed: {{e}}\", rdv_tmp.display(), rdv_final.display()));\n\
                     \x20\x20\x20\x20}}"
                )
                .ok();
                writeln!(
                    out,
                    "    let (data_{nwn}_std, _) = listener_{nwn}.accept()\n\
                     \x20\x20\x20\x20\x20\x20\x20\x20.unwrap_or_else(|e| panic!(\"host: accept DATA from {nwn} failed: {{e}}\"));"
                )
                .ok();
                writeln!(
                    out,
                    "    let (ctrl_{nwn}_raw, _) = listener_{nwn}.accept()\n\
                     \x20\x20\x20\x20\x20\x20\x20\x20.unwrap_or_else(|e| panic!(\"host: accept CTRL from {nwn} failed: {{e}}\"));"
                )
                .ok();
                writeln!(out, "    data_{nwn}_std.set_nodelay(true).ok();").ok();
                writeln!(out, "    ctrl_{nwn}_raw.set_nodelay(true).ok();").ok();
                writeln!(out, "    wire::apply_sock_buf(&data_{nwn}_std);").ok();
                writeln!(out, "    wire::apply_sock_buf(&ctrl_{nwn}_raw);").ok();
                writeln!(
                    out,
                    "    let ctrl_{nwn}: Rc<RefCell<std::net::TcpStream>> = Rc::new(RefCell::new(ctrl_{nwn}_raw));"
                )
                .ok();
                // Convert std TcpStream -> mio TcpStream + set non-blocking.
                writeln!(
                    out,
                    "    data_{nwn}_std.set_nonblocking(true)\n\
                     \x20\x20\x20\x20\x20\x20\x20\x20.unwrap_or_else(|e| panic!(\"host: set_nonblocking on DATA to {nwn} failed: {{e}}\"));"
                )
                .ok();
                writeln!(
                    out,
                    "    let data_{nwn} = mio::net::TcpStream::from_std(data_{nwn}_std);"
                )
                .ok();
            }
        } else {
            // Non-host: read the rendezvous file then connect_retry
            // for DATA + CTRL.
            let wn = wname.clone();
            writeln!(
                out,
                "    let rendezvous_dir: PathBuf = std::env::var_os(\"NUC_RENDEZVOUS_DIR\")\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20.map(PathBuf::from)\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20.unwrap_or_else(|| panic!(\"{wn}: NUC_RENDEZVOUS_DIR not set (run.sh must export it)\"));"
            )
            .ok();
            writeln!(
                out,
                "    let rdv_path = rendezvous_dir.join(\"{wn}.port\");"
            )
            .ok();
            writeln!(
                out,
                "    fn read_rendezvous_port(path: &std::path::Path, who: &str) -> u16 {{\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20let mut attempt = 0u32;\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20loop {{\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20match fs::read_to_string(path) {{\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20Ok(s) => {{\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20let trimmed = s.trim();\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20return trimmed.parse::<u16>().unwrap_or_else(|e| panic!(\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\"{{}}: rendezvous file `{{}}` contained `{{}}` which is not a u16: {{}}\",\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20who, path.display(), trimmed, e\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20));\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20}}\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20Err(_e) => {{\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20attempt += 1;\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20if attempt > 600 {{\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20panic!(\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\"{{}}: rendezvous file `{{}}` did not appear within 6s ({{}} attempts x 10ms) — host worker did not start or failed to bind\",\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20who, path.display(), attempt\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20);\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20}}\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20std::thread::sleep(Duration::from_millis(10));\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20}}\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20}}\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20}}\n\
                 \x20\x20\x20\x20}}"
            )
            .ok();
            writeln!(
                out,
                "    let port: u16 = read_rendezvous_port(&rdv_path, \"{wn}\");"
            )
            .ok();
            writeln!(
                out,
                "    fn connect_retry(port: u16, role: &str) -> StdTcpStream {{\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20let mut attempt = 0u32;\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20loop {{\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20match StdTcpStream::connect((\"127.0.0.1\", port)) {{\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20Ok(s) => return s,\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20Err(e) => {{\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20attempt += 1;\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20if attempt > 600 {{ panic!(\"{wn}: cannot connect {{role}} to host 127.0.0.1:{{port}} after {{attempt}} tries: {{e}}\"); }}\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20std::thread::sleep(Duration::from_millis(10));\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20}}\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20}}\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20}}\n\
                 \x20\x20\x20\x20}}"
            )
            .ok();
            writeln!(
                out,
                "    let data_host_std = connect_retry(port, \"DATA\");"
            )
            .ok();
            writeln!(
                out,
                "    let ctrl_host_raw = connect_retry(port, \"CTRL\");"
            )
            .ok();
            writeln!(out, "    data_host_std.set_nodelay(true).ok();").ok();
            writeln!(out, "    ctrl_host_raw.set_nodelay(true).ok();").ok();
            writeln!(out, "    wire::apply_sock_buf(&data_host_std);").ok();
            writeln!(out, "    wire::apply_sock_buf(&ctrl_host_raw);").ok();
            writeln!(
                out,
                "    data_host_std.set_nonblocking(true)\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20.unwrap_or_else(|e| panic!(\"{wn}: set_nonblocking on DATA to host failed: {{e}}\"));"
            )
            .ok();
            writeln!(
                out,
                "    let data_host = mio::net::TcpStream::from_std(data_host_std);"
            )
            .ok();
            writeln!(
                out,
                "    let ctrl_host: Rc<RefCell<std::net::TcpStream>> = Rc::new(RefCell::new(ctrl_host_raw));"
            )
            .ok();
        }
        Ok(())
    }

    /// Build the Reactor with peer DATA sockets + the per-chan
    /// instances sized from the sidecar.
    fn emit_reactor_and_chans(&self, out: &mut String, worker: WorkerId) -> Result<(), EmitError> {
        // Build the peers Vec for Reactor::new in deterministic order.
        let peers: Vec<WorkerId> = if worker == self.host_worker {
            self.non_host_workers()
        } else {
            vec![self.host_worker]
        };
        writeln!(out, "    let reactor = {{").ok();
        writeln!(
            out,
            "        let peers: Vec<(mio::net::TcpStream, String)> = vec!["
        )
        .ok();
        for p in &peers {
            let pn = self.worker_name(*p);
            // The DATA socket variable name depends on the role:
            // host -> data_<peer_name>, non-host -> data_host.
            let var = if worker == self.host_worker {
                format!("data_{pn}")
            } else {
                "data_host".to_string()
            };
            writeln!(out, "            ({var}, \"{pn}\".to_string()),").ok();
        }
        writeln!(out, "        ];").ok();
        writeln!(
            out,
            "        Rc::new(RefCell::new(runtime::Reactor::new(peers)))"
        )
        .ok();
        writeln!(out, "    }};").ok();
        writeln!(out).ok();

        // Per-chan instances: chan_<rid> = Chan::new(reactor, seq,
        // peer_idx, cap, encode, decode).
        let touched = self.worker_chans(worker);
        for (key, rid) in &self.chan_ids {
            if !touched.contains(rid) {
                continue;
            }
            let (data, seq) = *key;
            let cap =
                self.chan_caps.get(key).copied().ok_or_else(|| {
                    EmitError::ContractGap(format!("missing chan_cap for {key:?}"))
                })?;
            let ty = self.sidecar.data_type(data).ok_or_else(|| {
                EmitError::ContractGap(format!("cross-worker data {data:?} has no ResolvedType"))
            })?;
            let rty = rust_type_of(ty);
            let peer_idx = self.chan_peer_index(worker, *key)?;
            let (enc, dec) = encode_decode_paths(ty);
            writeln!(
                out,
                "    let chan_{rid}: runtime::Chan<{rty}> = runtime::Chan::new(\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20Rc::clone(&reactor), {seq}u64, {peer_idx}usize, \
                 {cap}usize, {enc}, {dec},\n\
                 \x20\x20\x20\x20);",
                seq = seq.0,
                peer_idx = peer_idx,
                cap = cap,
            )
            .ok();
        }
        Ok(())
    }

    /// Emit the per-barrier shim locals. The shared walker emits
    /// `bar_<bid>.wait()`; mp-tcp-event maps that to a struct whose
    /// `.wait()` method calls `wire::barrier_cross` on the CTRL
    /// socket(s) for this barrier's participants. Host crosses with
    /// every non-host participant in WorkerId order; non-host crosses
    /// with host only.
    fn emit_barrier_shims(
        &self,
        out: &mut String,
        worker: WorkerId,
        is_host: bool,
    ) -> Result<(), EmitError> {
        let tags = self.barriers_used_by(worker);
        if tags.is_empty() {
            return Ok(());
        }
        // Inline the shim type ONCE (zero-cost; per-barrier instances
        // are tiny structs that borrow the CTRL streams).
        writeln!(
            out,
            "    // Barrier shim — per-barrier .wait() invokes wire::barrier_cross"
        )
        .ok();
        writeln!(
            out,
            "    // on the CTRL stream(s) for this barrier's participants."
        )
        .ok();
        // The shim type is the same shape across all barriers within
        // one worker: a struct holding Rc<RefCell<TcpStream>> clones
        // for every CTRL peer this barrier crosses. We DECLARE ONE
        // shim type per barrier so the field set matches that
        // barrier's peer set exactly (different barriers can name
        // different participant subsets — see TASK-0172 +
        // mp-tcp-bufsync's partial/non-uniform barrier proof).
        for tag in &tags {
            let bid = tag.0;
            let parts = self
                .barrier_participants
                .get(tag)
                .expect("tag in tags came from barriers_used_by");
            if is_host {
                let mut peers: Vec<WorkerId> = parts
                    .iter()
                    .copied()
                    .filter(|w| *w != self.host_worker)
                    .collect();
                peers.sort_unstable();
                writeln!(out, "    struct Bar{bid} {{").ok();
                for p in &peers {
                    let pn = self.worker_name(*p);
                    writeln!(out, "        ctrl_{pn}: Rc<RefCell<std::net::TcpStream>>,").ok();
                }
                writeln!(out, "    }}").ok();
                writeln!(out, "    impl Bar{bid} {{").ok();
                writeln!(out, "        fn wait(&self) {{").ok();
                for p in &peers {
                    let pn = self.worker_name(*p);
                    writeln!(
                        out,
                        "            wire::barrier_cross(&mut *self.ctrl_{pn}.borrow_mut(), {bid});"
                    )
                    .ok();
                }
                writeln!(out, "        }}").ok();
                writeln!(out, "    }}").ok();
                writeln!(out, "    let bar_{bid} = Bar{bid} {{").ok();
                for p in &peers {
                    let pn = self.worker_name(*p);
                    writeln!(out, "        ctrl_{pn}: Rc::clone(&ctrl_{pn}),").ok();
                }
                writeln!(out, "    }};").ok();
            } else {
                writeln!(out, "    struct Bar{bid} {{").ok();
                writeln!(out, "        ctrl_host: Rc<RefCell<std::net::TcpStream>>,").ok();
                writeln!(out, "    }}").ok();
                writeln!(out, "    impl Bar{bid} {{").ok();
                writeln!(out, "        fn wait(&self) {{").ok();
                writeln!(
                    out,
                    "            wire::barrier_cross(&mut *self.ctrl_host.borrow_mut(), {bid});"
                )
                .ok();
                writeln!(out, "        }}").ok();
                writeln!(out, "    }}").ok();
                writeln!(
                    out,
                    "    let bar_{bid} = Bar{bid} {{ ctrl_host: Rc::clone(&ctrl_host) }};"
                )
                .ok();
            }
        }
        Ok(())
    }
}
