//! mp-tcp-poll multi-worker emit-string pins (TASK-0044.02.02 cycle 195).
//!
//! Structural-diff oracle: for any in-scope multi-worker schedule, the
//! mp-tcp-poll per-worker binary differs from mp-tcp-bufsync's ONLY
//! in:
//!   - `wire::read_msg_expect_poll` vs `wire::read_msg_expect`
//!   - `wire::write_msg_poll` vs `wire::write_msg`
//!   - `wire::barrier_cross_poll` vs `wire::barrier_cross`
//!   - presence of `wire::apply_nonblocking(...)` lines after each
//!     `wire::apply_sock_buf(...)` line (mp-tcp-poll only)
//!   - 1-line comment-block text under the host-relay banner
//!     (cycle-195 wording vs bufsync's TASK-0327 wording)
//!   - module-doc / banner-text provenance lines (cycle-195 wording
//!     names mp-tcp-poll; bufsync names mp-tcp-bufsync)
//!
//! Everything else (kernel calls, loop headers, partition slices,
//! reuse codegen, check-frame instrumentation, pre-init declarations,
//! sock-setup other than apply_nonblocking) MUST be byte-identical.
//! This is the cross-backend differential invariant at the
//! emit-string layer — it bites earlier than the e2e bit-identical
//! oracle and catches silent-sibling regressions of the cycle-195
//! poll-variant swap before they hit `cargo build`.

use std::path::PathBuf;

fn repo_root() -> PathBuf {
    let here = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    here.parent()
        .and_then(std::path::Path::parent)
        .and_then(std::path::Path::parent)
        .expect("three ancestors above mp-tcp-poll crate")
        .to_path_buf()
}

fn scratch_dir(name: &str) -> PathBuf {
    let target = repo_root().join("nucleus/target/mp-tcp-poll-multi-worker-emit-scratch");
    let _ = std::fs::create_dir_all(&target);
    let dir = target.join(name);
    let _ = std::fs::remove_dir_all(&dir);
    std::fs::create_dir_all(&dir).expect("create scratch dir");
    dir
}

/// Take a mp-tcp-poll-emitted bin source and rewrite it back to the
/// byte-identicality-by-construction-equivalent mp-tcp-bufsync form.
/// The four legal differences are reverted one-by-one; any residual
/// diff vs mp-tcp-bufsync's output then surfaces as a real codegen
/// drift (the test would fail).
fn poll_to_bufsync_equivalent(src: &str) -> String {
    let mut s = src.to_string();
    // Wait-primitive swap. The `(&mut ` suffix anchors the call site
    // and avoids partial-token matches (e.g. accidentally rewriting a
    // hypothetical sibling identifier whose name contains
    // `read_msg_expect_poll` as a substring).
    s = s.replace(
        "wire::read_msg_expect_poll(&mut ",
        "wire::read_msg_expect(&mut ",
    );
    s = s.replace("wire::write_msg_poll(&mut ", "wire::write_msg(&mut ");
    s = s.replace(
        "wire::barrier_cross_poll(&mut ",
        "wire::barrier_cross(&mut ",
    );
    // Strip the apply_nonblocking lines (mp-tcp-poll-only). Each
    // appears as a full line `    wire::apply_nonblocking(&sock);\n`
    // — strip with the surrounding newline so the residual line count
    // matches bufsync.
    let lines: Vec<&str> = s.lines().collect();
    let filtered: Vec<&str> = lines
        .into_iter()
        .filter(|line| !line.trim_start().starts_with("wire::apply_nonblocking("))
        .collect();
    let mut out = filtered.join("\n");
    if s.ends_with('\n') {
        out.push('\n');
    }
    // Provenance / banner-text swaps.
    out = out.replace(
        "Generated by the mp-tcp-poll backend (TASK-0044.02.02, ",
        "Generated by the mp-tcp-bufsync backend (TASK-0036, ",
    );
    // Relay-phase header block: cycle-195 emits a different comment
    // block than bufsync's TASK-0327. Both blocks live under the
    // host-only splice; the cleanest way to discharge the diff is to
    // strip both backends' comment lines and compare the meat.
    out
}

/// Drop every comment line in the host-relay banner. Both backends
/// emit a 4-7 line `// ...` block that introduces the relay phase;
/// the exact wording differs: cycle-195 names poll-variant helpers
/// and nonblocking-socket rationale; bufsync names TASK-0327
/// star-topology. The hop lines themselves (the `{ let
/// __relay_payload = ... }` statements) are the load-bearing emit
/// and are kept; trailing `// relay ...` end-of-line comments on
/// the hop lines are NOT banner-line comments — they live on
/// substantive code lines and must match.
///
/// Heuristic: a line starting with whitespace then `//` is a banner
/// candidate. Both banner blocks contain known keywords (`host-relay
/// phase`, `SYNCHRONOUS`, `poll-write`, `wire::read_msg_expect`,
/// `relay_payload` would be on a code line so excluded). The
/// alternative (line-range based stripping) is fragile to insertion-
/// point shifts; the keyword filter is robust.
fn strip_relay_banner_comments(src: &str) -> String {
    src.lines()
        .filter(|line| {
            let t = line.trim_start();
            if !t.starts_with("//") {
                return true;
            }
            // A whole-line `// ...` banner candidate. Strip iff it
            // contains a known relay-banner keyword. Hop-line trailing
            // `// relay ...` comments are excluded because they live
            // on the SAME line as the `{ let __relay_payload ... }`
            // statement — that line does NOT start with `//`.
            let strip = t.contains("host-relay phase")
                || t.contains("SYNCHRONOUS")
                || t.contains("poll-write")
                || t.contains("poll-variant wire helpers")
                || t.contains("nonblocking socket")
                || t.contains("sorted-WorkerId")
                || t.contains("seq cross-check")
                || t.contains("data, ctrl)-pair-per-(host, worker)")
                || t.contains("worker-to-worker Push/Wait")
                || t.contains("read from data_<src>")
                || t.contains("one (seq, dst) hop")
                || t.contains("forward worker-to-worker")
                || t.contains("pairs through host's existing")
                || t.contains("preserves the fail-loud contract")
                || t.contains("Push/Wait pairing divergence");
            !strip
        })
        .collect::<Vec<_>>()
        .join("\n")
}

fn assert_poll_bin_equiv_bufsync(label: &str, poll_src: &str, bufsync_src: &str) {
    // Cycle-195 review-gate P2.1 fold-back: guard against the
    // regression direction the canonicaliser silently no-ops on. If
    // poll regressed to emit blocking primitives, the `replace
    // "_poll" -> ""` would be a no-op, both canonicalised forms would
    // be identical, and the test would PASS while the code is wrong.
    // Pin the load-bearing positive needles + blocking anti-needles
    // BEFORE the swap canonicaliser runs. (Per-bin granularity here;
    // the OR-style smoke positive needle lives in tests/skeleton.rs.)
    //
    // We only require poll to carry AT LEAST ONE poll-variant call:
    // some bins (e.g. a host worker that only barrier-crosses) may
    // not use read/write_msg_poll. Conversely the bufsync sibling
    // must carry AT LEAST ONE blocking call; this guarantees the
    // canonicaliser actually saw a swap to revert.
    let poll_has_any_poll_call = poll_src.contains("wire::read_msg_expect_poll")
        || poll_src.contains("wire::write_msg_poll")
        || poll_src.contains("wire::barrier_cross_poll");
    let bufsync_has_any_blocking_call = bufsync_src.contains("wire::read_msg_expect(&mut ")
        || bufsync_src.contains("wire::write_msg(&mut ")
        || bufsync_src.contains("wire::barrier_cross(&mut ");
    assert!(
        poll_has_any_poll_call,
        "{label}: mp-tcp-poll bin carries NO wire::*_poll calls — \
         cycle-195 swap regressed (canonicaliser would silently no-op)"
    );
    assert!(
        bufsync_has_any_blocking_call,
        "{label}: mp-tcp-bufsync bin carries NO blocking wire::* calls — \
         oracle preconditions violated (cannot prove the swap was real)"
    );
    // And the inverse: poll must NOT carry blocking calls; if any
    // bin slipped past the cycle-195 swap, the canonicaliser would
    // mask the regression.
    assert!(
        !poll_src.contains("wire::read_msg_expect(&mut "),
        "{label}: mp-tcp-poll bin contains blocking read_msg_expect \
         — cycle-195 swap regressed in this bin"
    );
    assert!(
        !poll_src.contains("wire::write_msg(&mut "),
        "{label}: mp-tcp-poll bin contains blocking write_msg \
         — cycle-195 swap regressed in this bin"
    );
    assert!(
        !poll_src.contains("wire::barrier_cross(&mut "),
        "{label}: mp-tcp-poll bin contains blocking barrier_cross \
         — cycle-195 swap regressed in this bin"
    );

    let poll_canon = strip_relay_banner_comments(&poll_to_bufsync_equivalent(poll_src));
    let bufsync_canon = strip_relay_banner_comments(bufsync_src);
    if poll_canon != bufsync_canon {
        // Diff helper: line-by-line first-divergence
        let pl: Vec<&str> = poll_canon.lines().collect();
        let bl: Vec<&str> = bufsync_canon.lines().collect();
        let mut diff = String::new();
        for (i, (a, b)) in pl.iter().zip(bl.iter()).enumerate() {
            if a != b {
                diff.push_str(&format!(
                    "line {}:\n  poll(canon):    {a:?}\n  bufsync(canon): {b:?}\n",
                    i + 1
                ));
                if diff.len() > 4096 {
                    break;
                }
            }
        }
        if pl.len() != bl.len() {
            diff.push_str(&format!("\nlength: poll={} bufsync={}", pl.len(), bl.len()));
        }
        panic!(
            "{label}: mp-tcp-poll bin (after legal-swap canonicalisation) \
             differs from mp-tcp-bufsync's. This means the cycle-195 \
             swap missed a call site OR a non-emit-layer drift slipped \
             into mp-tcp-poll's plan/ substrate.\n--- divergences:\n{diff}\n\
             --- poll (canon, {plen} lines, head 4 KB) ---\n{phead}\n\
             --- bufsync (canon, {blen} lines, head 4 KB) ---\n{bhead}\n",
            plen = pl.len(),
            blen = bl.len(),
            phead = &poll_canon[..poll_canon.len().min(4096)],
            bhead = &bufsync_canon[..bufsync_canon.len().min(4096)],
        );
    }
}

/// 02-split-add/split — simplest in-tree multi-worker schedule.
/// 2 used workers (host + w0); minimal codegen surface; if any swap
/// site missed, this fails first.
#[test]
fn split_02_poll_equiv_bufsync() {
    let scratch = scratch_dir("split_02");
    let root = repo_root();
    let ex = root.join("nuc-nucleus/examples/02-split-add");
    let algo_src = std::fs::read_to_string(ex.join("prog.algo.nuc")).unwrap();
    let sched_src = std::fs::read_to_string(ex.join("schedules/split.sched.nuc")).unwrap();
    let r = test_common::lower_for_test(
        &algo_src,
        &sched_src,
        &test_common::LowerForTestOpts::default(),
    );
    let kernels = ex.join("kernels.rs");

    let poll_out = scratch.join("poll");
    let bufsync_out = scratch.join("bufsync");
    let poll = mp_tcp_poll::emit(&r.per_worker, &r.names, &r.sidecar, &kernels, &poll_out)
        .expect("poll emit");
    let bufsync = mp_tcp_bufsync::emit(&r.per_worker, &r.names, &r.sidecar, &kernels, &bufsync_out)
        .expect("bufsync emit");

    assert_eq!(
        poll.worker_bins.len(),
        bufsync.worker_bins.len(),
        "per-worker bin counts must match across poll/bufsync"
    );
    // Sort by file name for stable pairing across runs.
    let mut poll_bins = poll.worker_bins.clone();
    poll_bins.sort();
    let mut bufsync_bins = bufsync.worker_bins.clone();
    bufsync_bins.sort();
    for (p, b) in poll_bins.iter().zip(bufsync_bins.iter()) {
        let p_name = p.file_name().unwrap().to_str().unwrap();
        let b_name = b.file_name().unwrap().to_str().unwrap();
        assert_eq!(p_name, b_name, "per-worker bin names must match");
        let p_src = std::fs::read_to_string(p).expect("read poll bin");
        let b_src = std::fs::read_to_string(b).expect("read bufsync bin");
        assert_poll_bin_equiv_bufsync(p_name, &p_src, &b_src);
    }
}

/// 06-separable-filter/distributed2 — exercises the host-relay phase
/// (host + 4 workers, w2w pushes routed through host). Most banner-
/// text divergence happens here; the canonicalisation must hold.
///
/// Pass sequence MIRRORS mp-tcp-bufsync's `tests/host_relay_emit.rs::
/// emit_06_distributed2` — the 06/distributed2 schedule needs
/// partition_workers + partition_rows + halo_inference for the
/// transfer_inject pass to see the cross-worker fan-out shape. (The
/// test would otherwise emit a degenerate single-worker projection
/// that doesn't exercise the relay phase.)
#[test]
fn separable_filter_06_distributed2_poll_equiv_bufsync() {
    use nucleus_compiler::{
        acfg_to_events,
        algo::{lower_algo, parse_algo},
        apply_block_transforms, apply_halo_inference_partition_aware, apply_partition_blocks2d,
        apply_partition_rows, apply_partition_workers, apply_reuse_inference, build_acfg,
        build_sidecar, inject_syncs, inject_transfers, link,
        sched::{lower_sched, parse_sched},
        NameTables,
    };

    let scratch = scratch_dir("separable_filter_06_distributed2");
    let root = repo_root();
    let ex = root.join("nuc-nucleus/examples/06-separable-filter");
    let algo_src = std::fs::read_to_string(ex.join("prog.algo.nuc")).unwrap();
    let sched_src = std::fs::read_to_string(ex.join("schedules/distributed2.sched.nuc")).unwrap();
    let kernels = ex.join("kernels.rs");

    let algo_ast = parse_algo(&algo_src).expect("algo parse");
    let sched_ast = parse_sched(&sched_src).expect("sched parse");
    let algo_ir = lower_algo(&algo_ast).expect("algo lower");
    let sched_ir = lower_sched(&sched_ast).expect("sched lower");
    let linked = link(algo_ir, sched_ir).expect("link");
    let acfg = build_acfg(&linked).expect("build_acfg");
    let acfg = apply_block_transforms(&linked, acfg).expect("block transforms");
    let acfg = apply_partition_workers(&linked, acfg).expect("partition_workers");
    let acfg = apply_partition_rows(&linked, acfg).expect("partition_rows");
    let acfg = apply_partition_blocks2d(&linked, acfg).expect("partition_blocks2d");
    let (acfg, _advisory) =
        apply_halo_inference_partition_aware(&linked, acfg).expect("halo inference");
    let acfg = apply_reuse_inference(&linked, acfg).expect("reuse inference");
    let acfg = inject_syncs(acfg).expect("inject_syncs");
    let acfg = inject_transfers(&linked, acfg).expect("inject_transfers");
    let per_worker = acfg_to_events(&acfg);
    let sidecar = build_sidecar(&linked, &acfg).expect("build_sidecar");
    let names = NameTables::from_acfg(&acfg);

    let poll_out = scratch.join("poll");
    let bufsync_out = scratch.join("bufsync");
    let poll =
        mp_tcp_poll::emit(&per_worker, &names, &sidecar, &kernels, &poll_out).expect("poll emit");
    let bufsync = mp_tcp_bufsync::emit(&per_worker, &names, &sidecar, &kernels, &bufsync_out)
        .expect("bufsync emit");

    let mut poll_bins = poll.worker_bins.clone();
    poll_bins.sort();
    let mut bufsync_bins = bufsync.worker_bins.clone();
    bufsync_bins.sort();
    for (p, b) in poll_bins.iter().zip(bufsync_bins.iter()) {
        let p_name = p.file_name().unwrap().to_str().unwrap();
        let p_src = std::fs::read_to_string(p).expect("read poll bin");
        let b_src = std::fs::read_to_string(b).expect("read bufsync bin");
        assert_poll_bin_equiv_bufsync(p_name, &p_src, &b_src);
    }
}

/// 15-transpose/distributed-rows — the host-EXCLUDING-barrier coverage
/// arm (TASK-0044.02.02.01). The two pre-existing fixtures above
/// (02-split-add/split, 06-separable-filter/distributed2) both emit
/// barriers that INCLUDE host, so the `apply_host_mediation_inject`
/// driver pass is a no-op on them. This fixture closes the hole: its
/// `xpose on {w0,w1,w2,w3}` placement produces a genuinely
/// host-EXCLUDING inner barrier (participants `{w0,w1,w2,w3}`), which is
/// precisely the shape `apply_host_mediation_inject` exists to mediate
/// for the one-CTRL-stream-per-(host,worker) TCP star topology.
///
/// PROVENANCE / PREMISE CORRECTION (TASK-0044.02.02.01 cycle 231): the
/// filed task named `03-reduction/distributed` as the host-excluding
/// shape. Empirically false — 03-reduction/distributed's two barriers
/// BOTH already include host, so `apply_host_mediation_inject` is a
/// complete no-op there and the original AC#2 ("a barrier_cross_poll on
/// host's bin NOT present in the unmediated ACFG") was unsatisfiable. A
/// scan of every multi-worker schedule found 15-transpose/distributed-
/// rows is the ONLY schedule that is BOTH genuinely host-excluding AND a
/// promoted `[[required]]` e2e cell on mp-tcp-poll (see
/// `nuc-nucleus/e2e-matrix.toml`). Retargeting here fulfils — and
/// strengthens — the coverage intent: on this cell the UNMEDIATED poll
/// emit does not merely "lack" a host barrier_cross_poll, it FAILS to
/// emit at all (`Plan::build` returns a `ContractGap` on the
/// host-excluding barrier), which proves the mediation pass is
/// load-bearing rather than cosmetic.
///
/// Pass sequence MIRRORS the driver's mp-tcp-poll gate: the IR-stage
/// passes (parse..inject_transfers) PLUS an inline
/// `apply_host_mediation_inject`. The driver applies that pass for the
/// {mp-tcp-bufsync, mp-tcp-event, mp-tcp-poll, mp-uds-event} backends
/// (driver/src/main.rs host-mediation gate) but does NOT apply
/// `apply_host_data_relay_inject` for mp-tcp-poll (that DATA-arm relay
/// is mp-tcp-event / mp-uds-event only), so this test calls ONLY
/// `apply_host_mediation_inject` — unlike the mp-uds-event sibling
/// oracle which also calls the data relay. `inject_check_frames` is
/// omitted: 15-transpose/distributed-rows has no `check loop` directive,
/// so it would be a no-op.
#[test]
fn transpose_15_distributed_rows_poll_equiv_bufsync() {
    use nucleus_compiler::{
        acfg_to_events,
        algo::{lower_algo, parse_algo},
        apply_block_transforms, apply_halo_inference_partition_aware, apply_host_mediation_inject,
        apply_partition_blocks2d, apply_partition_rows, apply_partition_workers,
        apply_reuse_inference, build_acfg, build_sidecar, inject_syncs, inject_transfers, link,
        sched::{lower_sched, parse_sched},
        NameTables,
    };

    let scratch = scratch_dir("transpose_15_distributed_rows");
    let root = repo_root();
    let ex = root.join("nuc-nucleus/examples/15-transpose");
    let algo_src = std::fs::read_to_string(ex.join("prog.algo.nuc")).unwrap();
    let sched_src =
        std::fs::read_to_string(ex.join("schedules/distributed-rows.sched.nuc")).unwrap();
    let kernels = ex.join("kernels.rs");

    let algo_ast = parse_algo(&algo_src).expect("algo parse");
    let sched_ast = parse_sched(&sched_src).expect("sched parse");
    let algo_ir = lower_algo(&algo_ast).expect("algo lower");
    let sched_ir = lower_sched(&sched_ast).expect("sched lower");
    let linked = link(algo_ir, sched_ir).expect("link");
    let acfg = build_acfg(&linked).expect("build_acfg");
    let acfg = apply_block_transforms(&linked, acfg).expect("block transforms");
    let acfg = apply_partition_workers(&linked, acfg).expect("partition_workers");
    let acfg = apply_partition_rows(&linked, acfg).expect("partition_rows");
    let acfg = apply_partition_blocks2d(&linked, acfg).expect("partition_blocks2d");
    let (acfg, _advisory) =
        apply_halo_inference_partition_aware(&linked, acfg).expect("halo inference");
    let acfg = apply_reuse_inference(&linked, acfg).expect("reuse inference");
    let acfg = inject_syncs(acfg).expect("inject_syncs");
    let acfg = inject_transfers(&linked, acfg).expect("inject_transfers");

    // AC#2 (premise-correct, half 1) — the UNMEDIATED ACFG carries a
    // host-EXCLUDING barrier, so mp-tcp-poll's `Plan::build` REJECTS it
    // (its one-CTRL-stream-per-(host,worker) star cannot lower a barrier
    // that excludes the hub). This is the rejection
    // `apply_host_mediation_inject` exists to prevent; if mediation were
    // a no-op here (as it is on 03-reduction/distributed), this emit
    // would succeed and the test premise would be vacuous.
    let unmediated_pw = acfg_to_events(&acfg);
    let unmediated_sidecar = build_sidecar(&linked, &acfg).expect("build_sidecar (unmediated)");
    let unmediated_names = NameTables::from_acfg(&acfg);
    let unmediated_emit = mp_tcp_poll::emit(
        &unmediated_pw,
        &unmediated_names,
        &unmediated_sidecar,
        &kernels,
        &scratch.join("unmediated"),
    );
    let err = unmediated_emit.expect_err(
        "15-transpose/distributed-rows: UNMEDIATED mp-tcp-poll emit MUST fail \
         (host-excluding barrier rejected by Plan::build); if it succeeds, the \
         mediation pass is a no-op and this oracle does not exercise mediation",
    );
    let err_text = format!("{err:?}");
    assert!(
        err_text.contains("exclude the host worker"),
        "15-transpose/distributed-rows: UNMEDIATED emit must fail with the \
         host-excluding-barrier ContractGap; got: {err_text}"
    );

    // Mediate: same host election the mp-tcp-poll backend uses (shared
    // helper `backend_common::host_election`), mirroring the driver's
    // host-mediation gate (driver/src/main.rs).
    let preview = acfg_to_events(&acfg);
    let used: std::collections::BTreeSet<_> = preview
        .iter()
        .filter(|(_, evs)| !evs.is_empty())
        .map(|(w, _)| *w)
        .collect();
    let host = backend_common::elect_host_from_name_workers(&acfg.name_workers, &used)
        .expect("host election must succeed on 15-transpose/distributed-rows");
    let acfg = apply_host_mediation_inject(acfg, host);

    let per_worker = acfg_to_events(&acfg);
    let sidecar = build_sidecar(&linked, &acfg).expect("build_sidecar");
    let names = NameTables::from_acfg(&acfg);

    let poll_out = scratch.join("poll");
    let bufsync_out = scratch.join("bufsync");
    // AC#2 (premise-correct, half 2) — after mediation the emit SUCCEEDS;
    // host's bin now carries a `barrier_cross_poll` for the formerly
    // host-excluding barrier (host became a participant).
    let poll =
        mp_tcp_poll::emit(&per_worker, &names, &sidecar, &kernels, &poll_out).expect("poll emit");
    let bufsync = mp_tcp_bufsync::emit(&per_worker, &names, &sidecar, &kernels, &bufsync_out)
        .expect("bufsync emit");

    let host_name = names.worker.get(&host).expect("host name").clone();
    let host_bin = poll
        .worker_bins
        .iter()
        .find(|p| p.file_name().unwrap().to_str().unwrap() == format!("{host_name}.rs"))
        .expect("host bin must be present in the mediated emit");
    let host_src = std::fs::read_to_string(host_bin).expect("read host bin");
    assert!(
        host_src.contains("barrier_cross_poll"),
        "15-transpose/distributed-rows: after host-mediation the host bin \
         ({host_name}.rs) MUST carry a barrier_cross_poll call for the \
         mediated (formerly host-excluding) barrier. host bin:\n{host_src}"
    );

    // poll == bufsync per-bin, after the cycle-195 swap canonicalisation.
    let mut poll_bins = poll.worker_bins.clone();
    poll_bins.sort();
    let mut bufsync_bins = bufsync.worker_bins.clone();
    bufsync_bins.sort();
    assert_eq!(
        poll_bins.len(),
        bufsync_bins.len(),
        "per-worker bin counts must match across poll/bufsync"
    );
    for (p, b) in poll_bins.iter().zip(bufsync_bins.iter()) {
        let p_name = p.file_name().unwrap().to_str().unwrap();
        let p_src = std::fs::read_to_string(p).expect("read poll bin");
        let b_src = std::fs::read_to_string(b).expect("read bufsync bin");
        assert_poll_bin_equiv_bufsync(p_name, &p_src, &b_src);
    }
}
