//! `Plan::render_worker_program` — the per-worker `src/bin/<name>.rs`
//! emitter for the multi-process path. Originally inline in `lib.rs`
//! before the slice-4 split.
//!
//! The body assembles, in order: file-scope items (Count check-loop
//! statics + reporter struct), the TCP DATA + CTRL connection setup
//! (host = bind + accept; non-host = rendezvous-poll + connect), Drop
//! guards for Count check loops, pre-init local declarations, then the
//! per-worker `Event` walk via `Plan::render_events` — with a
//! host-only splice of the cycle-148 host-relay phase
//! (`Plan::render_relay_phase`) at the position chosen by
//! [`crate::walkers::relay_phase_insertion_point`].

use std::fmt::Write as _;

use backend_common::check_frame::{
    collect_count_check_frames, emit_count_guard_local, emit_count_reporter_struct,
    emit_count_static,
};
use backend_common::render::{render_array_init_for, rust_type_of, RenderCtxPub};
use nucleus_compiler::event::WorkerId;

use crate::walkers::relay_phase_insertion_point;
use crate::EmitError;

use super::Plan;

impl Plan<'_> {
    /// Render one worker's complete `src/bin/<name>.rs`.
    pub(crate) fn render_worker_program(&self, worker: WorkerId) -> Result<String, EmitError> {
        let mut out = String::new();
        let wname = self.worker_name(worker);
        let is_host = worker == self.host_worker;

        writeln!(
            out,
            "//! Generated by the mp-tcp-bufsync backend (TASK-0036, \
             multi-process). Worker `{wname}`{}.",
            if is_host {
                " [host/server]"
            } else {
                " [client]"
            }
        )
        .ok();
        writeln!(out, "//! Do not edit; rerun `nucleus build` to regenerate.").ok();
        writeln!(out).ok();
        writeln!(out, "#[path = \"../kernels.rs\"]").ok();
        writeln!(out, "#[allow(dead_code)]").ok();
        writeln!(out, "mod kernels;").ok();
        writeln!(out, "#[path = \"../wire.rs\"]").ok();
        writeln!(out, "#[allow(dead_code)]").ok();
        writeln!(out, "mod wire;").ok();
        writeln!(out).ok();
        // Role-specific imports so the generated file is
        // warning-clean. BOTH roles need PathBuf + fs for the
        // rendezvous-file handshake; host adds TcpListener +
        // io::Write (file write); non-host adds TcpStream + Duration
        // (connect retry + poll sleep).
        writeln!(out, "use std::fs;").ok();
        writeln!(out, "use std::path::PathBuf;").ok();
        if is_host {
            writeln!(out, "use std::net::TcpListener;").ok();
            writeln!(out, "use std::io::Write as _;").ok();
        } else {
            writeln!(out, "use std::net::TcpStream;").ok();
            writeln!(out, "use std::time::Duration;").ok();
        }
        writeln!(out).ok();

        // TASK-0052.04: per-worker file-scope items for every Count
        // check loop on THIS worker. The collector + reporter struct +
        // static `AtomicU64` shape are shared with pthreads-sync — one
        // implementation, no codegen drift (the cross-backend
        // bit-identical differential per PRD §10.1 depends on this).
        let count_frames = collect_count_check_frames(&self.per_worker[&worker]);
        if !count_frames.is_empty() {
            emit_count_reporter_struct(&mut out);
            for cf in &count_frames {
                // TASK-0222: shared template — see emit_count_static.
                emit_count_static(&mut out, &cf.ident);
            }
            writeln!(out).ok();
        }

        // Connection setup. TWO connections per (host, worker) pair:
        //
        //   - DATA  channel: Push/Wait framed messages.
        //   - CTRL  channel: barrier tokens.
        //
        // WHY TWO: all traffic on ONE stream is a single FIFO whose
        // byte order is whatever the sender emitted. The relative
        // order of a barrier vs a data transfer differs between the
        // producer and the consumer (the host emits `a,b` then a
        // barrier; the worker reaches the barrier first). On one
        // stream the worker's first read would consume the `a` frame
        // as if it were the barrier token — a framing collision.
        // pthreads-sync avoids this only because its `Slot` and
        // `Barrier` are *separate* objects (no shared FIFO). Splitting
        // data from control restores that separation: within the data
        // channel the projection guarantees Push order == Wait order;
        // within the control channel the uniform-barrier pre-order
        // index aligns on both sides. Each channel is independently
        // order-consistent; the cross-channel order never matters.
        //
        // Host is the server: it binds ONE listener per non-host
        // worker and `accept()`s exactly twice — first stream = DATA,
        // second = CTRL (deterministic role by accept order, no
        // handshake bytes). The worker connects twice in the same
        // order (DATA then CTRL), each with a bounded connect-retry
        // (a refused connect only means the listener is not up YET —
        // a liveness wait, not a data sync; deterministic eventual
        // outcome, fail-loud if the host never appears).
        // `unused_assignments`: pre-init declares `let mut d = vec![..]`
        // which is immediately overwritten by the matching Wait recv —
        // intentional (pre-init sizes the slot; the value is the
        // received one). Same shape pthreads-sync's multi-worker
        // pre-init produces; harmless and expected.
        writeln!(
            out,
            "#[allow(unused_mut, dead_code, unused_variables, \
             unused_assignments, clippy::needless_late_init)]"
        )
        .ok();
        writeln!(out, "fn main() {{").ok();

        if is_host {
            // Host: bind 127.0.0.1:0 for EACH non-host worker, then
            // ATOMICALLY publish the OS-assigned port via a rendezvous
            // file. Tmp-file + POSIX rename = atomic on the same FS so
            // a polling worker never reads a partial integer.
            // TASK-0176: replaces the prior env-var handshake whose
            // `__nuc_pick_port` helper had a close-then-rebind TOCTOU.
            writeln!(
                out,
                "    let rendezvous_dir: PathBuf = std::env::var_os(\"NUC_RENDEZVOUS_DIR\")\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20.map(PathBuf::from)\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20.unwrap_or_else(|| panic!(\"host: NUC_RENDEZVOUS_DIR not set (run.sh must export it)\"));"
            )
            .ok();
            writeln!(
                out,
                "    let _ = &rendezvous_dir; // referenced below per-worker"
            )
            .ok();
            // Sequential per-worker bind → publish → accept. For
            // every non-host worker this host serves we bind first,
            // then accept(). The order means worker N+1's port file
            // is not published until worker N has completed BOTH its
            // accepts, so worker N+1 is blocked on the rendezvous
            // poll while host accepts N — the 6s poll bound is shared
            // by all workers, not budgeted per-worker. The cycle-148
            // 06/distributed2 promotion (host + 4 workers; TASK-0327
            // host-relay) confirms this is fine in practice: per-
            // worker accept latency on loopback is ~ms, so 4 workers
            // comfortably finish within the 6s budget. A future
            // schedule with substantially more workers (or slower
            // accept) would need either parallel accepts (per-worker
            // thread) or publish-all-port-files-first, then accept-
            // all in a second pass. Filed: TASK-0176 closure notes
            // carry this forward.
            for nw in self.non_host_workers() {
                let nwn = self.worker_name(nw);
                writeln!(
                    out,
                    "    let listener_{nwn} = TcpListener::bind(\"127.0.0.1:0\")\n\
                     \x20\x20\x20\x20\x20\x20\x20\x20.unwrap_or_else(|e| panic!(\"host: bind 127.0.0.1:0 for {nwn} failed: {{e}}\"));"
                )
                .ok();
                writeln!(
                    out,
                    "    let port_{nwn}: u16 = listener_{nwn}.local_addr()\n\
                     \x20\x20\x20\x20\x20\x20\x20\x20.unwrap_or_else(|e| panic!(\"host: local_addr for {nwn} listener failed: {{e}}\"))\n\
                     \x20\x20\x20\x20\x20\x20\x20\x20.port();"
                )
                .ok();
                // Atomic publish: write to <name>.port.tmp then rename
                // to <name>.port. POSIX rename within the same dir is
                // atomic, so a polling worker either sees nothing or
                // sees the full integer — never a partial write.
                // Atomic publish: write the port to <name>.port.tmp,
                // drop the file, rename to <name>.port. POSIX rename
                // within a single directory is atomic — the polling
                // worker either sees nothing or sees the full integer,
                // never a partial write. No `sync_all`: the rendezvous
                // file is process-local-loopback ephemeral state, not
                // durable storage; the page cache is visible across
                // processes immediately.
                writeln!(
                    out,
                    "    {{\n\
                     \x20\x20\x20\x20\x20\x20\x20\x20let rdv_final = rendezvous_dir.join(\"{nwn}.port\");\n\
                     \x20\x20\x20\x20\x20\x20\x20\x20let rdv_tmp = rendezvous_dir.join(\"{nwn}.port.tmp\");\n\
                     \x20\x20\x20\x20\x20\x20\x20\x20let mut f = fs::File::create(&rdv_tmp)\n\
                     \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20.unwrap_or_else(|e| panic!(\"host: create rendezvous tmp `{{}}` for {nwn} failed: {{e}}\", rdv_tmp.display()));\n\
                     \x20\x20\x20\x20\x20\x20\x20\x20write!(f, \"{{}}\", port_{nwn})\n\
                     \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20.unwrap_or_else(|e| panic!(\"host: write port {{}} to rendezvous tmp `{{}}` for {nwn} failed: {{e}}\", port_{nwn}, rdv_tmp.display()));\n\
                     \x20\x20\x20\x20\x20\x20\x20\x20drop(f);\n\
                     \x20\x20\x20\x20\x20\x20\x20\x20fs::rename(&rdv_tmp, &rdv_final)\n\
                     \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20.unwrap_or_else(|e| panic!(\"host: rename rendezvous `{{}}` -> `{{}}` for {nwn} failed: {{e}}\", rdv_tmp.display(), rdv_final.display()));\n\
                     \x20\x20\x20\x20}}"
                )
                .ok();
                writeln!(
                    out,
                    "    let (mut data_{nwn}, _) = listener_{nwn}.accept()\n\
                     \x20\x20\x20\x20\x20\x20\x20\x20.unwrap_or_else(|e| panic!(\"host: accept DATA from {nwn} failed: {{e}}\"));"
                )
                .ok();
                writeln!(
                    out,
                    "    let (mut ctrl_{nwn}, _) = listener_{nwn}.accept()\n\
                     \x20\x20\x20\x20\x20\x20\x20\x20.unwrap_or_else(|e| panic!(\"host: accept CTRL from {nwn} failed: {{e}}\"));"
                )
                .ok();
                writeln!(out, "    data_{nwn}.set_nodelay(true).ok();").ok();
                writeln!(out, "    ctrl_{nwn}.set_nodelay(true).ok();").ok();
                writeln!(out, "    wire::apply_sock_buf(&data_{nwn});").ok();
                writeln!(out, "    wire::apply_sock_buf(&ctrl_{nwn});").ok();
            }
        } else {
            let wn = wname.clone();
            // Non-host worker: poll the rendezvous file the HOST writes
            // after it binds 127.0.0.1:0. Bound: 600 x 10 ms = 6 s
            // (symmetric with `connect_retry` so both liveness waits
            // share one mental budget). If the file never appears the
            // host did not start or failed to bind — fail LOUD naming
            // the path (TASK-0176).
            writeln!(
                out,
                "    let rendezvous_dir: PathBuf = std::env::var_os(\"NUC_RENDEZVOUS_DIR\")\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20.map(PathBuf::from)\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20.unwrap_or_else(|| panic!(\"{wn}: NUC_RENDEZVOUS_DIR not set (run.sh must export it)\"));"
            )
            .ok();
            writeln!(
                out,
                "    let rdv_path = rendezvous_dir.join(\"{wn}.port\");"
            )
            .ok();
            writeln!(
                out,
                "    fn read_rendezvous_port(path: &std::path::Path, who: &str) -> u16 {{\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20let mut attempt = 0u32;\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20loop {{\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20match fs::read_to_string(path) {{\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20Ok(s) => {{\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20let trimmed = s.trim();\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20return trimmed.parse::<u16>().unwrap_or_else(|e| panic!(\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\"{{}}: rendezvous file `{{}}` contained `{{}}` which is not a u16: {{}}\",\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20who, path.display(), trimmed, e\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20));\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20}}\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20Err(_e) => {{\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20attempt += 1;\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20if attempt > 600 {{\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20panic!(\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\"{{}}: rendezvous file `{{}}` did not appear within 6s ({{}} attempts x 10ms) — host worker did not start or failed to bind\",\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20who, path.display(), attempt\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20);\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20}}\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20std::thread::sleep(Duration::from_millis(10));\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20}}\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20}}\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20}}\n\
                 \x20\x20\x20\x20}}"
            )
            .ok();
            writeln!(
                out,
                "    let port: u16 = read_rendezvous_port(&rdv_path, \"{wn}\");"
            )
            .ok();
            writeln!(
                out,
                "    fn connect_retry(port: u16, role: &str) -> TcpStream {{\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20let mut attempt = 0u32;\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20loop {{\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20match TcpStream::connect((\"127.0.0.1\", port)) {{\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20Ok(s) => return s,\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20Err(e) => {{\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20attempt += 1;\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20if attempt > 600 {{ panic!(\"{wn}: cannot connect {{role}} to host 127.0.0.1:{{port}} after {{attempt}} tries: {{e}}\"); }}\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20std::thread::sleep(Duration::from_millis(10));\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20}}\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20}}\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20}}\n\
                 \x20\x20\x20\x20}}"
            )
            .ok();
            writeln!(
                out,
                "    let mut data_host = connect_retry(port, \"DATA\");"
            )
            .ok();
            writeln!(
                out,
                "    let mut ctrl_host = connect_retry(port, \"CTRL\");"
            )
            .ok();
            writeln!(out, "    data_host.set_nodelay(true).ok();").ok();
            writeln!(out, "    ctrl_host.set_nodelay(true).ok();").ok();
            writeln!(out, "    wire::apply_sock_buf(&data_host);").ok();
            writeln!(out, "    wire::apply_sock_buf(&ctrl_host);").ok();
        }
        writeln!(out).ok();

        // TASK-0052.04: per-Count-check-loop Drop guard local. The
        // guard's Drop fires when `fn main` returns, printing a
        // stderr summary line. SAME shape as pthreads-sync — single
        // codegen implementation.
        for cf in &count_frames {
            // TASK-0222: shared template — see emit_count_guard_local.
            emit_count_guard_local(&mut out, &cf.ident, &cf.loop_var, cf.latency_max_ns);
        }
        if !count_frames.is_empty() {
            writeln!(out).ok();
        }

        // Pre-init: data this worker Waits on (overwritten on recv)
        // OR writes via an indexed Fire output and never whole-array.
        // Sorted by name. Sized/typed from the sidecar — SAME logic
        // and spelling as pthreads-sync's multi-worker pre-init.
        let pre_init = self.collect_pre_init(worker)?;
        for (name, did) in &pre_init {
            let ty = self.sidecar.data_type(*did).ok_or_else(|| {
                EmitError::ContractGap(format!(
                    "pre-init data `{name}` ({did:?}) has no ResolvedType in sidecar"
                ))
            })?;
            let rty = rust_type_of(ty);
            let init = render_array_init_for(ty);
            writeln!(out, "    let mut {name}: {rty} = {init};").ok();
        }
        if !pre_init.is_empty() {
            writeln!(out).ok();
        }

        let ctx = RenderCtxPub::new(self.names, self.sidecar);

        // TASK-0327 (cycle 148): for HOST, when the schedule has w2w
        // pushes, splice the synchronous relay phase right BEFORE the
        // first top-level Wait event (the gather start). The relay
        // phase drains all worker-to-worker (seq, dst) hops through
        // host's existing data sockets. Insertion-point heuristic
        // (acceptable for the cycle-148 06/distributed2 reproducer
        // shape — scatter → cross-relay → gather): host has no data
        // reads BETWEEN scatter Pushes and gather Waits, so relay-
        // reads on data_<src> don't race host's own reads. If no top-
        // level Wait exists, the relay goes at the END (just before
        // main returns). Non-host workers render unchanged — they
        // just see `data_host` for both directions, host does the
        // forwarding.
        let host_events = &self.per_worker[&worker];
        let host_relay = if is_host {
            self.render_relay_phase(1)?
        } else {
            String::new()
        };
        if is_host && !host_relay.is_empty() {
            let split_at = relay_phase_insertion_point(host_events);
            self.render_events(
                &host_events[..split_at],
                &mut out,
                1,
                worker,
                is_host,
                &ctx,
                None,
            )?;
            out.push_str(&host_relay);
            self.render_events(
                &host_events[split_at..],
                &mut out,
                1,
                worker,
                is_host,
                &ctx,
                None,
            )?;
        } else {
            self.render_events(host_events, &mut out, 1, worker, is_host, &ctx, None)?;
        }

        writeln!(out, "}}").ok();
        Ok(out)
    }
}
