//! mp-uds-event plan shim.
//!
//! The multi-process emit `Plan` substrate (host election, chan
//! registry, per-pair capacity, peer-index routing, barrier analysis,
//! host-relay codegen, the entire event walk + worker-program
//! assembly) lives ONCE in [`backend_common::event_plan`], parameterised
//! over the [`backend_common::event_plan::EventTransport`] trait
//! (TASK-0044.03.02 lift). This file supplies only mp-uds-event's
//! `EventTransport` impl — the Unix-domain-socket transport primitives
//! (path-as-rendezvous, `UnixListener` / `UnixStream` /
//! `mio::net::UnixStream`, the UDS `sun_path` 104-byte cap check, the
//! `/tmp`-rooted run.sh swap) — plus a `Plan` type alias the crate's
//! `lib.rs` consumes exactly as it did the old in-crate `Plan`, and a
//! `render_run_sh` wrapper.
//!
//! mp-tcp-event is the sibling consumer; its shim
//! (`nucleus/backends/mp-tcp-event/src/plan.rs`) supplies the TCP
//! loopback variant. The two impls are the COMPLETE, enumerable delta
//! between the backends — everything else is shared.

use std::fmt::Write as _;

use backend_common::event_plan::EventTransport;

use crate::EmitError;

/// mp-uds-event transport: Unix domain sockets. The handshake block +
/// stream types are built STRUCTURALLY from their arguments (never by
/// textual replace; see `feedback-textual-replace-codegen-unsafe`). The
/// one sanctioned `String::replace` is in `render_run_sh_post` over a
/// FIXED shell-script literal block (zero sibling-substring risk;
/// annotated at the call site).
pub(crate) struct UdsEventTransport;

impl EventTransport for UdsEventTransport {
    const BACKEND_NAME: &'static str = "mp-uds-event";
    const FILE_HEADER_PREFIX: &'static str =
        "//! Generated by the mp-uds-event backend (TASK-0044.03.01, multi-process over Unix domain sockets).";
    const CTRL_STD_STREAM_TY: &'static str = "std::os::unix::net::UnixStream";
    const DATA_MIO_STREAM_TY: &'static str = "mio::net::UnixStream";

    /// mp-uds-event additionally buffers `buffer=N` frames per (seq,
    /// peer) in the APPLICATION ring, so the SO_*BUF sizing here is the
    /// WIRE frame size, not the ring depth — a different rationale than
    /// mp-tcp-bufsync's sync-one-msg sizing, hence the per-backend
    /// comment.
    const SO_BUF_COMMENT: &'static str =
        "# Socket buffer requirement from the schedule's per-channel\n\
         # buffer needs (largest single transfer payload). Same shape\n\
         # as mp-tcp-bufsync — mp-uds-event additionally buffers up to\n\
         # `transfer DATA : buffer=N` frames per (seq, peer) IN THE\n\
         # APPLICATION ring, so the SO_*BUF sizing here is the WIRE\n\
         # frame size, not the ring depth.\n";

    fn emit_role_imports(out: &mut String, is_host: bool) {
        // UDS path-as-rendezvous: the socket PATH itself is the
        // rendezvous identity, so no `fs` (port-in-file) + no
        // `io::Write` (port-file write) are needed; only PathBuf + the
        // UDS listener/stream types.
        writeln!(out, "use std::path::PathBuf;").ok();
        if is_host {
            writeln!(out, "use std::os::unix::net::UnixListener;").ok();
        } else {
            writeln!(out, "use std::os::unix::net::UnixStream as StdUnixStream;").ok();
            writeln!(out, "use std::time::Duration;").ok();
        }
    }

    /// UDS path-as-rendezvous handshake + DATA/CTRL socket setup (cycle
    /// 197 TASK-0044.03.01). Host = server, non-host = client. UDS uses
    /// the SOCKET PATH itself as the rendezvous identity — no port
    /// number to publish (which the TCP backend needs, TASK-0176). The
    /// host BINDS its UnixListener at `<NUC_RENDEZVOUS_DIR>/<nwn>.{data,
    /// ctrl}.sock`; the non-host worker connect_retry's the same paths.
    ///
    /// AC#9: UDS sun_path is capped at 108 bytes on Linux glibc and 104
    /// on musl/macOS. The emitted code does a runtime check before
    /// bind/connect and fails LOUD with a clear error naming the path +
    /// length + cap — vs the bare ENAMETOOLONG the syscall would
    /// surface — using the smaller cap (104) with a margin.
    ///
    /// Emitted verbatim (byte-identical to the pre-lift mp-uds-event
    /// emit).
    fn emit_handshake(out: &mut String, wname: &str, is_host: bool, non_host_names: &[String]) {
        if is_host {
            writeln!(
                out,
                "    let rendezvous_dir: PathBuf = std::env::var_os(\"NUC_RENDEZVOUS_DIR\")\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20.map(PathBuf::from)\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20.unwrap_or_else(|| panic!(\"host: NUC_RENDEZVOUS_DIR not set (run.sh must export it)\"));"
            )
            .ok();
            writeln!(out, "    let _ = &rendezvous_dir;").ok();
            // AC#9: emit the UDS path-length check helper ONCE per
            // worker binary. Cap = 104 (musl/macOS sun_path); Linux
            // glibc allows 108 but we take the smaller for portability
            // + leave a margin so a near-cap path isn't accepted by
            // Linux only to fail on a musl rebuild.
            writeln!(
                out,
                "    fn check_uds_path_len(p: &std::path::Path, who: &str) {{\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20// AC#9 (cycle-197 TASK-0044.03.01): UDS sun_path is\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20// capped at 108 bytes on Linux glibc and 104 on\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20// musl/macOS. Use the smaller cap to defend against\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20// silent breakage when a generated project is run\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20// on a musl distro after development on glibc.\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20const UDS_PATH_CAP: usize = 104;\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20let bytes = p.as_os_str().len();\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20if bytes >= UDS_PATH_CAP {{\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20panic!(\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\"{{who}}: UDS rendezvous path `{{path}}` is {{bytes}} bytes long, which meets-or-exceeds the {{cap}}-byte UDS sun_path cap (musl/macOS limit; Linux glibc is 108 but we take the smaller for portability + margin). Shorten NUC_RENDEZVOUS_DIR or move scratch to /tmp.\",\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20who = who, path = p.display(), bytes = bytes, cap = UDS_PATH_CAP\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20);\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20}}\n\
                 \x20\x20\x20\x20}}"
            )
            .ok();
            // Per non-host worker: TWO UDS sockets (DATA + CTRL) —
            // same shape as mp-tcp-event's TCP DATA + CTRL split.
            // Path-as-rendezvous: <NUC_RENDEZVOUS_DIR>/<nwn>.{data,ctrl}.sock
            for nwn in non_host_names {
                writeln!(
                    out,
                    "    let data_path_{nwn} = rendezvous_dir.join(\"{nwn}.data.sock\");"
                )
                .ok();
                writeln!(
                    out,
                    "    let ctrl_path_{nwn} = rendezvous_dir.join(\"{nwn}.ctrl.sock\");"
                )
                .ok();
                writeln!(
                    out,
                    "    check_uds_path_len(&data_path_{nwn}, \"host: bind DATA to {nwn}\");"
                )
                .ok();
                writeln!(
                    out,
                    "    check_uds_path_len(&ctrl_path_{nwn}, \"host: bind CTRL to {nwn}\");"
                )
                .ok();
                writeln!(
                    out,
                    "    let data_listener_{nwn} = UnixListener::bind(&data_path_{nwn})\n\
                     \x20\x20\x20\x20\x20\x20\x20\x20.unwrap_or_else(|e| panic!(\"host: bind DATA UDS `{{}}` for {nwn} failed: {{e}}\", data_path_{nwn}.display()));"
                )
                .ok();
                writeln!(
                    out,
                    "    let ctrl_listener_{nwn} = UnixListener::bind(&ctrl_path_{nwn})\n\
                     \x20\x20\x20\x20\x20\x20\x20\x20.unwrap_or_else(|e| panic!(\"host: bind CTRL UDS `{{}}` for {nwn} failed: {{e}}\", ctrl_path_{nwn}.display()));"
                )
                .ok();
                writeln!(
                    out,
                    "    let (data_{nwn}_std, _) = data_listener_{nwn}.accept()\n\
                     \x20\x20\x20\x20\x20\x20\x20\x20.unwrap_or_else(|e| panic!(\"host: accept DATA from {nwn} failed: {{e}}\"));"
                )
                .ok();
                writeln!(
                    out,
                    "    let (ctrl_{nwn}_raw, _) = ctrl_listener_{nwn}.accept()\n\
                     \x20\x20\x20\x20\x20\x20\x20\x20.unwrap_or_else(|e| panic!(\"host: accept CTRL from {nwn} failed: {{e}}\"));"
                )
                .ok();
                writeln!(out, "    wire::apply_sock_buf(&data_{nwn}_std);").ok();
                writeln!(out, "    wire::apply_sock_buf(&ctrl_{nwn}_raw);").ok();
                writeln!(
                    out,
                    "    let ctrl_{nwn}: Rc<RefCell<std::os::unix::net::UnixStream>> = Rc::new(RefCell::new(ctrl_{nwn}_raw));"
                )
                .ok();
                // Convert std UnixStream -> mio UnixStream + set non-blocking.
                writeln!(
                    out,
                    "    data_{nwn}_std.set_nonblocking(true)\n\
                     \x20\x20\x20\x20\x20\x20\x20\x20.unwrap_or_else(|e| panic!(\"host: set_nonblocking on DATA to {nwn} failed: {{e}}\"));"
                )
                .ok();
                writeln!(
                    out,
                    "    let data_{nwn} = mio::net::UnixStream::from_std(data_{nwn}_std);"
                )
                .ok();
            }
        } else {
            // Non-host: connect_retry to the host-bound UDS paths.
            // No port file to read — the PATH itself is the rendezvous.
            let wn = wname;
            writeln!(
                out,
                "    let rendezvous_dir: PathBuf = std::env::var_os(\"NUC_RENDEZVOUS_DIR\")\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20.map(PathBuf::from)\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20.unwrap_or_else(|| panic!(\"{wn}: NUC_RENDEZVOUS_DIR not set (run.sh must export it)\"));"
            )
            .ok();
            writeln!(
                out,
                "    let data_path = rendezvous_dir.join(\"{wn}.data.sock\");"
            )
            .ok();
            writeln!(
                out,
                "    let ctrl_path = rendezvous_dir.join(\"{wn}.ctrl.sock\");"
            )
            .ok();
            // AC#9 path-length check (client side: same cap rule).
            writeln!(
                out,
                "    fn check_uds_path_len(p: &std::path::Path, who: &str) {{\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20const UDS_PATH_CAP: usize = 104;\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20let bytes = p.as_os_str().len();\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20if bytes >= UDS_PATH_CAP {{\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20panic!(\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\"{{who}}: UDS rendezvous path `{{path}}` is {{bytes}} bytes long, which meets-or-exceeds the {{cap}}-byte UDS sun_path cap (musl/macOS limit). Shorten NUC_RENDEZVOUS_DIR.\",\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20who = who, path = p.display(), bytes = bytes, cap = UDS_PATH_CAP\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20);\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20}}\n\
                 \x20\x20\x20\x20}}"
            )
            .ok();
            writeln!(
                out,
                "    check_uds_path_len(&data_path, \"{wn}: connect DATA\");"
            )
            .ok();
            writeln!(
                out,
                "    check_uds_path_len(&ctrl_path, \"{wn}: connect CTRL\");"
            )
            .ok();
            // connect_retry for UDS: poll the path until host has
            // bound (host may not have started yet); same 6s budget
            // as the TCP variant. Fail-loud at deadline.
            writeln!(
                out,
                "    fn connect_retry(path: &std::path::Path, who: &str, role: &str) -> StdUnixStream {{\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20let mut attempt = 0u32;\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20loop {{\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20match StdUnixStream::connect(path) {{\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20Ok(s) => return s,\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20Err(e) => {{\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20attempt += 1;\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20if attempt > 600 {{ panic!(\"{{who}}: cannot connect {{role}} UDS `{{path}}` after {{attempt}} tries: {{err}}\", who = who, role = role, path = path.display(), attempt = attempt, err = e); }}\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20std::thread::sleep(Duration::from_millis(10));\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20}}\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20}}\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20}}\n\
                 \x20\x20\x20\x20}}"
            )
            .ok();
            writeln!(
                out,
                "    let data_host_std = connect_retry(&data_path, \"{wn}\", \"DATA\");"
            )
            .ok();
            writeln!(
                out,
                "    let ctrl_host_raw = connect_retry(&ctrl_path, \"{wn}\", \"CTRL\");"
            )
            .ok();
            writeln!(out, "    wire::apply_sock_buf(&data_host_std);").ok();
            writeln!(out, "    wire::apply_sock_buf(&ctrl_host_raw);").ok();
            writeln!(
                out,
                "    data_host_std.set_nonblocking(true)\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20.unwrap_or_else(|e| panic!(\"{wn}: set_nonblocking on DATA to host failed: {{e}}\"));"
            )
            .ok();
            writeln!(
                out,
                "    let data_host = mio::net::UnixStream::from_std(data_host_std);"
            )
            .ok();
            writeln!(
                out,
                "    let ctrl_host: Rc<RefCell<std::os::unix::net::UnixStream>> = Rc::new(RefCell::new(ctrl_host_raw));"
            )
            .ok();
        }
    }

    /// SWAP the shared template's `$here/.nuc-rendezvous-$$`
    /// rendezvous-dir block for a `/tmp`-rooted `mktemp -d` because UDS
    /// sun_path is capped at 104 bytes (musl/macOS). The shared
    /// template uses `$here/.nuc-rendezvous-$$` (mp-tcp-* needs only the
    /// rendezvous-FILE PATH, so the 4096-byte PATH_MAX is the binding
    /// cap there). For UDS the rendezvous DIR + socket-filename together
    /// must fit in 104 bytes; with realistic worker names + the e2e
    /// harness's deep scratch hierarchy the `$here`-rooted dir is
    /// ~120-180 bytes and busts the cap. Using a `/tmp`-rooted dir keeps
    /// it under the cap. The swap fails LOUD if the shared template's
    /// rendezvous block changes shape so the swap misses (rather than
    /// silently shipping a cap-busting path). See memory
    /// `project-uds-path-cap-rendezvous`.
    fn render_run_sh_post(shared: String) -> Result<String, EmitError> {
        // The shared template's exact block is 4 lines (see
        // `multi_binary::render_run_sh_multi`). We replace the whole
        // block atomically so a future change to the shared template
        // surfaces as a swap miss + the fail-loud sentinel below.
        let needle = "NUC_RENDEZVOUS_DIR=\"$here/.nuc-rendezvous-$$\"\n\
                      mkdir -p \"$NUC_RENDEZVOUS_DIR\"\n\
                      trap 'rm -rf \"$NUC_RENDEZVOUS_DIR\"' EXIT\n\
                      export NUC_RENDEZVOUS_DIR";
        let replacement = "# UDS-specific: rendezvous dir under /tmp because\n\
                           # mp-uds-event's UDS sockets must fit in the\n\
                           # 104-byte sun_path cap (musl/macOS limit); the\n\
                           # e2e harness's deep scratch hierarchy + worker\n\
                           # name + .sock suffix easily busts the cap if\n\
                           # we use $here. mktemp -d picks an unused name\n\
                           # under /tmp, guaranteed-fresh per run.\n\
                           NUC_RENDEZVOUS_DIR=\"$(mktemp -d -t nuc-uds-XXXXXXXX)\"\n\
                           trap 'rm -rf \"$NUC_RENDEZVOUS_DIR\"' EXIT\n\
                           export NUC_RENDEZVOUS_DIR";
        // Multi-line literal shell-script block (not a rendered Rust expression);
        // sibling-substring risk is zero. Post-replace fail-loud sentinel below
        // catches needle-not-found.
        let out = shared.replace(needle, replacement); // ALLOW textual replace: multi-line literal bash block (see comment above; needle is a fixed shared-template substring)
        if !out.contains("nuc-uds-XXXXXXXX") {
            return Err(EmitError::ContractGap(format!(
                "mp-uds-event render_run_sh: shared template's rendezvous-dir \
                 block changed shape — the cycle-197 step-5 UDS-path swap \
                 missed. Expected the literal needle:\n{needle}\n\nbut the \
                 shared template emitted:\n{shared}"
            )));
        }
        Ok(out)
    }
}

/// mp-uds-event's concrete `Plan` — the shared generic substrate with
/// the UDS transport bound in. `lib.rs` uses this exactly as it used
/// the old in-crate `Plan` (`Plan::build`, `.render_worker_program`,
/// `.used_workers`, `.worker_name`).
pub(crate) type Plan<'a> = backend_common::event_plan::Plan<'a, UdsEventTransport>;

/// Multi-process run.sh — delegates to the shared substrate's
/// `Plan::render_run_sh` (UDS post-processing swaps the rendezvous dir
/// for a `/tmp`-rooted path). Kept as a free function so `lib.rs`'s
/// `multi_worker::render_run_sh(&plan)` call resolves unchanged after
/// the lift.
pub(crate) fn render_run_sh(plan: &Plan<'_>) -> Result<String, EmitError> {
    plan.render_run_sh()
}
