//! mp-tcp-event plan shim.
//!
//! The multi-process emit `Plan` substrate (host election, chan
//! registry, per-pair capacity, peer-index routing, barrier analysis,
//! host-relay codegen, the entire event walk + worker-program
//! assembly) lives ONCE in [`backend_common::event_plan`], parameterised
//! over the [`backend_common::event_plan::EventTransport`] trait
//! (TASK-0044.03.02 lift). This file supplies only mp-tcp-event's
//! `EventTransport` impl — the TCP-loopback transport primitives (TCP
//! port-in-file rendezvous, `TcpListener` / `TcpStream` /
//! `mio::net::TcpStream`) — plus a `Plan` type alias the crate's
//! `lib.rs` consumes exactly as it did the old in-crate `Plan`, and a
//! `render_run_sh` wrapper.
//!
//! mp-uds-event is the sibling consumer; its shim
//! (`nucleus/backends/mp-uds-event/src/plan.rs`) supplies the Unix
//! domain socket variant. The two impls are the COMPLETE, enumerable
//! delta between the backends — everything else is shared.

use std::fmt::Write as _;

use backend_common::event_plan::EventTransport;

use crate::EmitError;

/// mp-tcp-event transport: TCP loopback. The handshake block + stream
/// types are built STRUCTURALLY from their arguments (never by textual
/// replace; see `feedback-textual-replace-codegen-unsafe`).
pub(crate) struct TcpEventTransport;

impl EventTransport for TcpEventTransport {
    const BACKEND_NAME: &'static str = "mp-tcp-event";
    const FILE_HEADER_PREFIX: &'static str =
        "//! Generated by the mp-tcp-event backend (TASK-0042.05, multi-process).";
    const CTRL_STD_STREAM_TY: &'static str = "std::net::TcpStream";
    const DATA_MIO_STREAM_TY: &'static str = "mio::net::TcpStream";

    /// mp-tcp-event additionally buffers `buffer=N` frames per (seq,
    /// peer) in the APPLICATION ring, so the SO_*BUF sizing here is the
    /// WIRE frame size, not the ring depth — a different rationale than
    /// mp-tcp-bufsync's sync-one-msg sizing, hence the per-backend
    /// comment.
    const SO_BUF_COMMENT: &'static str =
        "# Socket buffer requirement from the schedule's per-channel\n\
         # buffer needs (largest single transfer payload). Same shape\n\
         # as mp-tcp-bufsync — mp-tcp-event additionally buffers up to\n\
         # `transfer DATA : buffer=N` frames per (seq, peer) IN THE\n\
         # APPLICATION ring, so the SO_*BUF sizing here is the WIRE\n\
         # frame size, not the ring depth.\n";

    fn emit_role_imports(out: &mut String, is_host: bool) {
        // TCP port-in-file rendezvous needs fs + PathBuf; host writes
        // the port (io::Write), non-host reads it + sleeps (Duration).
        writeln!(out, "use std::fs;").ok();
        writeln!(out, "use std::path::PathBuf;").ok();
        if is_host {
            writeln!(out, "use std::net::TcpListener;").ok();
            writeln!(out, "use std::io::Write as _;").ok();
        } else {
            writeln!(out, "use std::net::TcpStream as StdTcpStream;").ok();
            writeln!(out, "use std::time::Duration;").ok();
        }
    }

    /// Rendezvous-file handshake + DATA/CTRL socket setup. Host =
    /// server, non-host = client. Rendezvous-file mechanism is the
    /// SINGLE-ALLOCATOR pattern that closes the close-then-rebind
    /// TOCTOU window (TASK-0176); DO NOT reintroduce the deleted
    /// `__nuc_pick_port` helper. Emitted verbatim (byte-identical to
    /// the pre-lift mp-tcp-event emit).
    fn emit_handshake(out: &mut String, wname: &str, is_host: bool, non_host_names: &[String]) {
        if is_host {
            writeln!(
                out,
                "    let rendezvous_dir: PathBuf = std::env::var_os(\"NUC_RENDEZVOUS_DIR\")\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20.map(PathBuf::from)\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20.unwrap_or_else(|| panic!(\"host: NUC_RENDEZVOUS_DIR not set (run.sh must export it)\"));"
            )
            .ok();
            writeln!(out, "    let _ = &rendezvous_dir;").ok();
            // Per non-host worker: bind, publish port, accept DATA + CTRL.
            for nwn in non_host_names {
                writeln!(
                    out,
                    "    let listener_{nwn} = TcpListener::bind(\"127.0.0.1:0\")\n\
                     \x20\x20\x20\x20\x20\x20\x20\x20.unwrap_or_else(|e| panic!(\"host: bind 127.0.0.1:0 for {nwn} failed: {{e}}\"));"
                )
                .ok();
                writeln!(
                    out,
                    "    let port_{nwn}: u16 = listener_{nwn}.local_addr()\n\
                     \x20\x20\x20\x20\x20\x20\x20\x20.unwrap_or_else(|e| panic!(\"host: local_addr for {nwn} listener failed: {{e}}\"))\n\
                     \x20\x20\x20\x20\x20\x20\x20\x20.port();"
                )
                .ok();
                writeln!(
                    out,
                    "    {{\n\
                     \x20\x20\x20\x20\x20\x20\x20\x20let rdv_final = rendezvous_dir.join(\"{nwn}.port\");\n\
                     \x20\x20\x20\x20\x20\x20\x20\x20let rdv_tmp = rendezvous_dir.join(\"{nwn}.port.tmp\");\n\
                     \x20\x20\x20\x20\x20\x20\x20\x20let mut f = fs::File::create(&rdv_tmp)\n\
                     \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20.unwrap_or_else(|e| panic!(\"host: create rendezvous tmp `{{}}` for {nwn} failed: {{e}}\", rdv_tmp.display()));\n\
                     \x20\x20\x20\x20\x20\x20\x20\x20write!(f, \"{{}}\", port_{nwn})\n\
                     \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20.unwrap_or_else(|e| panic!(\"host: write port {{}} to rendezvous tmp `{{}}` for {nwn} failed: {{e}}\", port_{nwn}, rdv_tmp.display()));\n\
                     \x20\x20\x20\x20\x20\x20\x20\x20drop(f);\n\
                     \x20\x20\x20\x20\x20\x20\x20\x20fs::rename(&rdv_tmp, &rdv_final)\n\
                     \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20.unwrap_or_else(|e| panic!(\"host: rename rendezvous `{{}}` -> `{{}}` for {nwn} failed: {{e}}\", rdv_tmp.display(), rdv_final.display()));\n\
                     \x20\x20\x20\x20}}"
                )
                .ok();
                // Bounded accept (TASK-0461.01): the prior bare
                // `listener_{nwn}.accept()` was an UNBOUNDED blocking
                // call — a worker that never connected left host wedged
                // here forever at 0% CPU with no established socket (the
                // 10.5h-night-eater signature; silent sibling of the
                // mp-tcp-bufsync/poll fix in TASK-0461).
                // `wire::accept_with_deadline` (already shipped dormant
                // in the emitted `wire.rs`, copied from
                // `mp_tcp_common::WIRE_RUNTIME_SRC`) polls with a
                // wall-clock deadline and fails LOUD naming the worker.
                // It returns the stream DIRECTLY (not a tuple) and
                // restores the listener + stream to BLOCKING; the
                // subsequent std->mio `set_nonblocking(true)` on the
                // stream is unaffected (the helper toggles the LISTENER).
                writeln!(
                    out,
                    "    let data_{nwn}_std = wire::accept_with_deadline(&listener_{nwn}, \"DATA\", \"{nwn}\");"
                )
                .ok();
                writeln!(
                    out,
                    "    let ctrl_{nwn}_raw = wire::accept_with_deadline(&listener_{nwn}, \"CTRL\", \"{nwn}\");"
                )
                .ok();
                writeln!(out, "    data_{nwn}_std.set_nodelay(true).ok();").ok();
                writeln!(out, "    ctrl_{nwn}_raw.set_nodelay(true).ok();").ok();
                writeln!(out, "    wire::apply_sock_buf(&data_{nwn}_std);").ok();
                writeln!(out, "    wire::apply_sock_buf(&ctrl_{nwn}_raw);").ok();
                writeln!(
                    out,
                    "    let ctrl_{nwn}: Rc<RefCell<std::net::TcpStream>> = Rc::new(RefCell::new(ctrl_{nwn}_raw));"
                )
                .ok();
                // Convert std TcpStream -> mio TcpStream + set non-blocking.
                writeln!(
                    out,
                    "    data_{nwn}_std.set_nonblocking(true)\n\
                     \x20\x20\x20\x20\x20\x20\x20\x20.unwrap_or_else(|e| panic!(\"host: set_nonblocking on DATA to {nwn} failed: {{e}}\"));"
                )
                .ok();
                writeln!(
                    out,
                    "    let data_{nwn} = mio::net::TcpStream::from_std(data_{nwn}_std);"
                )
                .ok();
            }
        } else {
            // Non-host: read the rendezvous file then connect_retry
            // for DATA + CTRL.
            let wn = wname;
            writeln!(
                out,
                "    let rendezvous_dir: PathBuf = std::env::var_os(\"NUC_RENDEZVOUS_DIR\")\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20.map(PathBuf::from)\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20.unwrap_or_else(|| panic!(\"{wn}: NUC_RENDEZVOUS_DIR not set (run.sh must export it)\"));"
            )
            .ok();
            writeln!(
                out,
                "    let rdv_path = rendezvous_dir.join(\"{wn}.port\");"
            )
            .ok();
            writeln!(
                out,
                "    fn read_rendezvous_port(path: &std::path::Path, who: &str) -> u16 {{\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20let mut attempt = 0u32;\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20loop {{\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20match fs::read_to_string(path) {{\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20Ok(s) => {{\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20let trimmed = s.trim();\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20return trimmed.parse::<u16>().unwrap_or_else(|e| panic!(\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\"{{}}: rendezvous file `{{}}` contained `{{}}` which is not a u16: {{}}\",\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20who, path.display(), trimmed, e\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20));\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20}}\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20Err(_e) => {{\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20attempt += 1;\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20if attempt > 600 {{\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20panic!(\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\"{{}}: rendezvous file `{{}}` did not appear within 6s ({{}} attempts x 10ms) — host worker did not start or failed to bind\",\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20who, path.display(), attempt\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20);\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20}}\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20std::thread::sleep(Duration::from_millis(10));\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20}}\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20}}\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20}}\n\
                 \x20\x20\x20\x20}}"
            )
            .ok();
            writeln!(
                out,
                "    let port: u16 = read_rendezvous_port(&rdv_path, \"{wn}\");"
            )
            .ok();
            writeln!(
                out,
                "    fn connect_retry(port: u16, role: &str) -> StdTcpStream {{\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20let mut attempt = 0u32;\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20loop {{\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20match StdTcpStream::connect((\"127.0.0.1\", port)) {{\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20Ok(s) => return s,\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20Err(e) => {{\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20attempt += 1;\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20if attempt > 600 {{ panic!(\"{wn}: cannot connect {{role}} to host 127.0.0.1:{{port}} after {{attempt}} tries: {{e}}\"); }}\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20std::thread::sleep(Duration::from_millis(10));\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20}}\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20}}\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20}}\n\
                 \x20\x20\x20\x20}}"
            )
            .ok();
            writeln!(
                out,
                "    let data_host_std = connect_retry(port, \"DATA\");"
            )
            .ok();
            writeln!(
                out,
                "    let ctrl_host_raw = connect_retry(port, \"CTRL\");"
            )
            .ok();
            writeln!(out, "    data_host_std.set_nodelay(true).ok();").ok();
            writeln!(out, "    ctrl_host_raw.set_nodelay(true).ok();").ok();
            writeln!(out, "    wire::apply_sock_buf(&data_host_std);").ok();
            writeln!(out, "    wire::apply_sock_buf(&ctrl_host_raw);").ok();
            writeln!(
                out,
                "    data_host_std.set_nonblocking(true)\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20.unwrap_or_else(|e| panic!(\"{wn}: set_nonblocking on DATA to host failed: {{e}}\"));"
            )
            .ok();
            writeln!(
                out,
                "    let data_host = mio::net::TcpStream::from_std(data_host_std);"
            )
            .ok();
            writeln!(
                out,
                "    let ctrl_host: Rc<RefCell<std::net::TcpStream>> = Rc::new(RefCell::new(ctrl_host_raw));"
            )
            .ok();
        }
    }

    /// TCP uses the shared multi_binary run.sh template directly — no
    /// post-processing (the `$here`-rooted rendezvous-FILE path fits
    /// the 4096-byte PATH_MAX; only UDS hits the 104-byte sun_path cap).
    fn render_run_sh_post(shared: String) -> Result<String, EmitError> {
        Ok(shared)
    }
}

/// mp-tcp-event's concrete `Plan` — the shared generic substrate with
/// the TCP transport bound in. `lib.rs` uses this exactly as it used
/// the old in-crate `Plan` (`Plan::build`, `.render_worker_program`,
/// `.used_workers`, `.worker_name`).
pub(crate) type Plan<'a> = backend_common::event_plan::Plan<'a, TcpEventTransport>;

/// Multi-process run.sh — delegates to the shared substrate's
/// `Plan::render_run_sh` (TCP post-processing is identity). Kept as a
/// free function so `lib.rs`'s `multi_worker::render_run_sh(&plan)` call
/// resolves unchanged after the lift.
pub(crate) fn render_run_sh(plan: &Plan<'_>) -> Result<String, EmitError> {
    plan.render_run_sh()
}
