// Kernel bodies for example 13-cnn-inference.
//
// PRD §6.2.2: kernel bodies live in an adjacent Rust source file and
// are real Rust functions. Nucleus does NOT interpolate text into
// these bodies; they are compiled by the host toolchain unmodified.
//
// Six kernels:
//   - `conv_block_1`  — (Vec<i32>) -> Vec<i32>, pure.
//                       3x3 SAME conv (zero-pad) + ReLU + 2x2 maxpool.
//                       C0=1 -> C1=8 channels; spatial 28x28 -> 14x14.
//   - `conv_block_2`  — (Vec<i32>) -> Vec<i32>, pure.
//                       3x3 SAME conv + ReLU + 2x2 maxpool.
//                       C1=8 -> C2=16 channels; 14x14 -> 7x7.
//   - `classifier`    — (Vec<i32>) -> Vec<i32>, pure.
//                       Dense 16*7*7 = 784 -> 10 (linear; no softmax,
//                       no bias).
//   - `load_input`    — () -> Vec<i32>, effectful. Reads B*C0*H*W
//                       i32 LE words from `input.bin`.
//   - `save_output`   — (Vec<i32>) -> (), effectful. Writes
//                       B*N_CLASSES i32 LE words.
//
// Numeric type choice: i32 (NOT f32)
// -----------------------------------
// PRD §13: "Bit-identical output across backends. Trivial for integer
// algorithms; non-trivial once floating-point reductions enter (sum
// order matters). Either restrict examples to integer/deterministic
// FP, or compare with epsilon. Leaning toward integer-only for v2."
// docs/reference-impl-policy.md §5: "Prefer integer arithmetic.
// Integer ops are bit-deterministic by language definition."
//
// This example demonstrates the LAYER-WISE DATAFLOW SHAPE (PRD §9
// row 13) — whole-layer kernels, batch-axis exposed, three radically
// different decompositions of the same algorithm — NOT real ML
// inference. Inputs, weights, and activations are abstract integers.
// No quantisation, no Q-format, no learned weights.
//
// Why `Vec<i32>` and not `[i32; N]`
// ---------------------------------
// Same as examples 01..07: PRD const-in-Rust-generics flow is
// unresolved (TASK-0103). Aggregate kernel I/O uses `Vec<i32>` with
// runtime length assertions. The codegen flattens multi-dim indices
// row-major. For partial-prefix slicing (e.g. `feat1[n] <--
// conv_block_1(input[n])` where both data are rank 4 indexed with 1
// index), TASK-0209 emits a sub-slice `.to_vec()` on the arg side and
// `.copy_from_slice(&...)` on the output side.
//
// Per-kernel sub-slice lengths (TASK-0209 codegen contract):
//   - conv_block_1 arg:   C0 * H   * W   = 1 *  28 *  28 =   784
//   - conv_block_1 ret:   C1 * H/2 * W/2 = 8 *  14 *  14 =  1568
//   - conv_block_2 arg:   C1 * H/2 * W/2 = 8 *  14 *  14 =  1568
//   - conv_block_2 ret:   C2 * H/4 * W/4 = 16 *  7 *  7  =   784
//   - classifier   arg:   C2 * H/4 * W/4 = 16 *  7 *  7  =   784
//   - classifier   ret:   N_CLASSES                       =    10
//
// Determinism contract
// --------------------
// All conv/pool/dense reductions accumulate strict left-to-right via
// explicit `for` loops using `wrapping_mul`/`wrapping_add`. Integer
// arithmetic is bit-deterministic by Rust's language definition; no
// HashMap iteration, no threading, no f32. The accumulators fit in
// i32 by construction (see range note on `conv` below).
//
// Weights: deterministic from an integer formula keyed by index, so
// both this file and `reference/src/main.rs` independently compute
// the same weight set without sharing code (per
// docs/reference-impl-policy.md §2 independence). Inputs come from
// the committed `input.bin`.
//
// I/O paths
// ---------
// Effectful kernels read paths from environment variables when set,
// falling back to the conventional sibling filenames in the cwd.

use std::env;
use std::fs;
use std::io::Write;

// -----------------------------------------------------------------
// Shape constants. Mirror `prog.algo.nuc`. Single-source-of-truth
// violation (TASK-0103); resolves when const-flow lands.
// -----------------------------------------------------------------
const B: usize = 16;
const H: usize = 28;
const W: usize = 28;
const C0: usize = 1;
const C1: usize = 8;
const C2: usize = 16;
const N_CLASSES: usize = 10;

// Derived dimensions.
const H1: usize = H / 2; // 14
const W1: usize = W / 2; // 14
const H2: usize = H / 4; // 7
const W2: usize = W / 4; // 7

// Per-sample tensor sizes (flat row-major).
const SAMPLE_IN: usize = C0 * H * W; // 784
const SAMPLE_F1: usize = C1 * H1 * W1; // 1568
const SAMPLE_F2: usize = C2 * H2 * W2; // 784
const SAMPLE_OUT: usize = N_CLASSES; // 10

// Whole-program tensor sizes.
const INPUT_ELEMS: usize = B * SAMPLE_IN; // 12544
const OUTPUT_ELEMS: usize = B * SAMPLE_OUT; // 160

const BYTES_PER_WORD: usize = 4;

// -----------------------------------------------------------------
// Weights. Generated by deterministic integer formulae keyed by
// (output_channel, input_channel, ky, kx). Range is bounded so the
// conv accumulator stays inside i32 by a wide margin.
//
// Range analysis (for conv_block_1):
//   - input range: [-8, 7]   (see write_input_bin in input.bin gen)
//   - weight range: [-2, 2]
//   - per-tap product: |x * w| <= 16
//   - per-output-pixel sum: C0 * 3 * 3 * 16 = 1 * 9 * 16 = 144
//   - For conv_block_2: C1 * 3 * 3 = 72 taps; activations from
//     block 1 maxpool are bounded by 144 (the conv sum); products
//     bounded by 144 * 2 = 288; sum bounded by 72 * 288 = 20736.
//   - Classifier: 784 taps; pre-relu/pool block 2 activations bounded
//     by ~20736; weights [-2, 2]; per-class sum bounded by
//     784 * 20736 * 2 ~ 32 million. Well inside i32::MAX (~2.1B).
//
// `wrapping_*` documents the overflow contract; the inputs above
// never trip it. Pathological inputs would NOT panic.
// -----------------------------------------------------------------

/// Weight for conv layer 1, channel `oc` (output), `ic` (input),
/// kernel position `(ky, kx)`. Range [-2, 2].
fn w1(oc: usize, ic: usize, ky: usize, kx: usize) -> i32 {
    // Mix indices with small distinct primes so different positions
    // produce different weights; modulo 5 -> [0, 4]; subtract 2 ->
    // [-2, 2]. Cast to i32 after mixing in usize to avoid surprises.
    let mixed = oc.wrapping_mul(73)
        .wrapping_add(ic.wrapping_mul(19))
        .wrapping_add(ky.wrapping_mul(11))
        .wrapping_add(kx.wrapping_mul(7));
    (mixed % 5) as i32 - 2
}

/// Weight for conv layer 2. Same shape, different prime mixing so
/// the two layers do not coincidentally produce identical weights.
fn w2(oc: usize, ic: usize, ky: usize, kx: usize) -> i32 {
    let mixed = oc.wrapping_mul(101)
        .wrapping_add(ic.wrapping_mul(29))
        .wrapping_add(ky.wrapping_mul(13))
        .wrapping_add(kx.wrapping_mul(5));
    (mixed % 5) as i32 - 2
}

/// Weight for the classifier. Range [-5, 5], indexed by
/// `(class, flat_input_position)`.
///
/// Modulus 11 (prime, >= N_CLASSES=10): with `% M < 10`, weights are
/// class-periodic mod M (any polynomial f(c) mod M has period M), so
/// some pair of classes within 0..9 emits identical weight vectors,
/// collapsing 10 logits into <10 distinct values. M=11 is the
/// smallest modulus that makes `(class * 131) % M` injective on
/// 0..9 (131 coprime with 11). Range [-5, 5]; 784-tap dot product
/// bounded by 784 * max(|feat2|) * 5, still well inside i32.
fn w_cls(class: usize, k: usize) -> i32 {
    let mixed = class.wrapping_mul(131)
        .wrapping_add(k.wrapping_mul(37));
    (mixed % 11) as i32 - 5
}

// -----------------------------------------------------------------
// Pure kernels.
// -----------------------------------------------------------------

/// 3x3 SAME-padded conv + ReLU + 2x2 maxpool (stride 2).
///
/// Input shape (flat row-major): C0 x H x W = 1 x 28 x 28 = 784.
/// Output shape (flat row-major): C1 x (H/2) x (W/2) = 8 x 14 x 14 = 1568.
///
/// Pad mode: zero-pad outside the input window. Pool: hard max of
/// the four pre-relu values in each 2x2 tile (relu fuses into the
/// max trivially because max(0, max(a, b)) == max(0, a, b) when
/// applied per-element — but to keep semantics crisp we relu BEFORE
/// pool, in the per-output-channel buffer).
///
/// Determinism: every reduction is a strict left-to-right `for` loop
/// over fixed bounds with `wrapping_mul`/`wrapping_add`. No
/// f32/HashMap/Instant.
pub fn conv_block_1(input: Vec<i32>) -> Vec<i32> {
    assert_eq!(
        input.len(),
        SAMPLE_IN,
        "conv_block_1: expected {} elements, got {}",
        SAMPLE_IN,
        input.len()
    );
    // Conv -> relu intermediate, shape C1 x H x W = 8 x 28 x 28.
    let mut conv_out = vec![0i32; C1 * H * W];
    for oc in 0..C1 {
        for y in 0..H {
            for x in 0..W {
                let mut acc: i32 = 0;
                // 3x3 kernel; offsets dy/dx in [-1, 0, 1]; zero-pad
                // outside input bounds.
                for ky in 0..3usize {
                    for kx in 0..3usize {
                        // Cast to i32 for signed arithmetic before
                        // bounds check.
                        let iy = y as i32 + ky as i32 - 1;
                        let ix = x as i32 + kx as i32 - 1;
                        for ic in 0..C0 {
                            let v = if iy < 0 || iy >= H as i32 || ix < 0 || ix >= W as i32 {
                                0i32
                            } else {
                                input[ic * H * W + iy as usize * W + ix as usize]
                            };
                            let w = w1(oc, ic, ky, kx);
                            acc = acc.wrapping_add(v.wrapping_mul(w));
                        }
                    }
                }
                // ReLU.
                let relu = if acc > 0 { acc } else { 0 };
                conv_out[oc * H * W + y * W + x] = relu;
            }
        }
    }
    // 2x2 maxpool stride 2.
    let mut out = vec![0i32; SAMPLE_F1];
    for oc in 0..C1 {
        for oy in 0..H1 {
            for ox in 0..W1 {
                // Four taps. Pick the strict left-to-right max via a
                // single sequence of `max` calls in a fixed order
                // (i32::max is order-independent BUT we still spell
                // out the order for clarity).
                let a = conv_out[oc * H * W + (2 * oy) * W + (2 * ox)];
                let b = conv_out[oc * H * W + (2 * oy) * W + (2 * ox + 1)];
                let c = conv_out[oc * H * W + (2 * oy + 1) * W + (2 * ox)];
                let d = conv_out[oc * H * W + (2 * oy + 1) * W + (2 * ox + 1)];
                let m = a.max(b).max(c).max(d);
                out[oc * H1 * W1 + oy * W1 + ox] = m;
            }
        }
    }
    out
}

/// 3x3 SAME-padded conv + ReLU + 2x2 maxpool. Channels C1=8 -> C2=16;
/// spatial 14x14 -> 7x7.
pub fn conv_block_2(input: Vec<i32>) -> Vec<i32> {
    assert_eq!(
        input.len(),
        SAMPLE_F1,
        "conv_block_2: expected {} elements, got {}",
        SAMPLE_F1,
        input.len()
    );
    let mut conv_out = vec![0i32; C2 * H1 * W1];
    for oc in 0..C2 {
        for y in 0..H1 {
            for x in 0..W1 {
                let mut acc: i32 = 0;
                for ky in 0..3usize {
                    for kx in 0..3usize {
                        let iy = y as i32 + ky as i32 - 1;
                        let ix = x as i32 + kx as i32 - 1;
                        for ic in 0..C1 {
                            let v = if iy < 0
                                || iy >= H1 as i32
                                || ix < 0
                                || ix >= W1 as i32
                            {
                                0i32
                            } else {
                                input[ic * H1 * W1 + iy as usize * W1 + ix as usize]
                            };
                            let w = w2(oc, ic, ky, kx);
                            acc = acc.wrapping_add(v.wrapping_mul(w));
                        }
                    }
                }
                let relu = if acc > 0 { acc } else { 0 };
                conv_out[oc * H1 * W1 + y * W1 + x] = relu;
            }
        }
    }
    let mut out = vec![0i32; SAMPLE_F2];
    for oc in 0..C2 {
        for oy in 0..H2 {
            for ox in 0..W2 {
                let a = conv_out[oc * H1 * W1 + (2 * oy) * W1 + (2 * ox)];
                let b = conv_out[oc * H1 * W1 + (2 * oy) * W1 + (2 * ox + 1)];
                let c = conv_out[oc * H1 * W1 + (2 * oy + 1) * W1 + (2 * ox)];
                let d = conv_out[oc * H1 * W1 + (2 * oy + 1) * W1 + (2 * ox + 1)];
                let m = a.max(b).max(c).max(d);
                out[oc * H2 * W2 + oy * W2 + ox] = m;
            }
        }
    }
    out
}

/// Dense classifier: flatten C2 x H2 x W2 = 784 input scalars and
/// compute the per-class wrapping-dot-product against `w_cls`. No
/// bias, no softmax (output is raw i32 logits).
///
/// Determinism: per-class strict left-to-right accumulation.
pub fn classifier(input: Vec<i32>) -> Vec<i32> {
    assert_eq!(
        input.len(),
        SAMPLE_F2,
        "classifier: expected {} elements, got {}",
        SAMPLE_F2,
        input.len()
    );
    let mut out = vec![0i32; N_CLASSES];
    for class in 0..N_CLASSES {
        let mut acc: i32 = 0;
        for k in 0..SAMPLE_F2 {
            acc = acc.wrapping_add(input[k].wrapping_mul(w_cls(class, k)));
        }
        out[class] = acc;
    }
    out
}

// -----------------------------------------------------------------
// Effectful kernels: I/O.
// -----------------------------------------------------------------

pub fn load_input() -> Vec<i32> {
    let path = env::var("NUC_INPUT_PATH").unwrap_or_else(|_| "input.bin".to_string());
    let bytes = fs::read(&path)
        .unwrap_or_else(|e| panic!("load_input: cannot read {}: {}", path, e));
    let need = INPUT_ELEMS * BYTES_PER_WORD;
    assert!(
        bytes.len() >= need,
        "load_input: file {} has {} bytes; need at least {}",
        path,
        bytes.len(),
        need
    );
    let mut out = Vec::with_capacity(INPUT_ELEMS);
    for i in 0..INPUT_ELEMS {
        let off = i * BYTES_PER_WORD;
        let word = i32::from_le_bytes([
            bytes[off],
            bytes[off + 1],
            bytes[off + 2],
            bytes[off + 3],
        ]);
        out.push(word);
    }
    out
}

pub fn save_output(data: Vec<i32>) {
    assert_eq!(
        data.len(),
        OUTPUT_ELEMS,
        "save_output: expected {} elements, got {}",
        OUTPUT_ELEMS,
        data.len()
    );
    let path = env::var("NUC_OUTPUT_PATH").unwrap_or_else(|_| "output.bin".to_string());
    let mut bytes = Vec::with_capacity(data.len() * BYTES_PER_WORD);
    for v in &data {
        bytes.extend_from_slice(&v.to_le_bytes());
    }
    let mut f = fs::File::create(&path)
        .unwrap_or_else(|e| panic!("save_output: cannot create {}: {}", path, e));
    f.write_all(&bytes)
        .unwrap_or_else(|e| panic!("save_output: write failed: {}", e));
}
