//! Project-skeleton renderers — string templates for the standalone
//! Cargo project a backend emits. TASK-0246 (cycle 38) + TASK-0257
//! (cycle 112).
//!
//! # Why this lives in backend-common
//!
//! Through cycles 17/22/24/31 these renderers grew inside
//! `pthreads-sync` (the first single-binary backend) and pthreads-async
//! imported them via `pthreads_sync::render_cargo_toml` /
//! `render_run_sh`. Cycle 37 (TASK-0244) extracted most of the shared
//! codegen surface into `backend-common` but LEFT these two string
//! templates in pthreads-sync. That residual arrow was not a genuine
//! semantic delegation — the templates are inert strings, identical
//! across pthreads-sync + pthreads-async, with no pthreads-sync-
//! specific content. TASK-0246 (cycle 38) lifted the single-binary
//! templates here. TASK-0257 (cycle 112) lifts the multi-binary
//! templates here in turn, closing the prior 3-way duplication across
//! mp-tcp-bufsync + mp-tcp-event single-worker + mp-tcp-event multi-
//! worker. The single-worker straight-line `main.rs` emitter — the
//! LAST inter-backend arrow, once `pthreads_sync::render_single_worker_main`
//! — was itself relocated into this crate
//! ([`crate::single_worker_main`]) in TASK-0455.11, so no backend now
//! delegates to another backend: every backend's single-worker arm IS
//! the shared `backend_common::single_worker_main` renderer,
//! byte-identical by construction.
//!
//! # Module shape
//!
//! - [`single_binary`] — Cargo.toml + run.sh for backends that emit
//!   ONE binary into a single Cargo project (`pthreads-sync`,
//!   `pthreads-async`). The shape is "one `[[bin]]` target named
//!   `nuc-generated` at `src/main.rs`, panic = abort release profile,
//!   run.sh that wraps `cargo build --release` +
//!   `target/release/nuc-generated`".
//!
//! - [`multi_binary`] — Cargo.toml + run.sh (single-process AND
//!   multi-process variants) for backends that emit N binaries under
//!   `src/bin/<name>.rs` and orchestrate them via a launcher script
//!   (`mp-tcp-bufsync`, `mp-tcp-event`). The Cargo.toml takes an
//!   optional [`CargoDependencies`] block (mp-tcp-event passes `mio =
//!   ...`); the run.sh takes per-backend SO_BUF commentary as a
//!   parameter.
//!
//! # The [`CargoDependencies`] slot (TASK-0288)
//!
//! Both `render_cargo_toml` entry points take a typed
//! [`CargoDependencies`] rather than the original raw
//! `Option<&str>` textual passthrough (TASK-0257 forward-carried
//! P2.1 hardening). The typed slot models exactly the real caller
//! usage: an OPTIONAL single `[dependencies]` section whose body is
//! verbatim TOML text. Both the renderer and the type own the
//! `[dependencies]` header — the caller supplies ONLY the body
//! (dependency entries plus any `#` comment lines), never the
//! section header itself.
//!
//! Why a newtype over the body, not a `&[(name, spec)]` map: the
//! real bodies interleave `#` comment lines with the entries
//! (mp-tcp-event / mp-uds-event explain their `mio` feature choices
//! inline; see `MIO_DEPENDENCY_BLOCK`). A structured key/value map
//! would not round-trip those comments byte-for-byte, and modelling
//! arbitrary TOML value syntax (`mio = { version = ..., features =
//! [...] }`) is speculative generality the two-comment-plus-one-entry
//! real usage does not justify. The newtype keeps the body verbatim
//! while making the *section* typed: a future caller cannot silently
//! jam a `[dev-dependencies]` / `[build-dependencies]` / multi-section
//! TOML string through a parameter that the type system says is the
//! body of a single `[dependencies]` section. If a real second
//! section type ever materialises, extend [`CargoDependencies`] then
//! (a typed `dev: Option<...>` field), not pre-emptively.
//!
//! # Header text
//!
//! TASK-0246 (cycle 38) updated the emitted Cargo.toml + run.sh
//! headers to the same neutral form TASK-0231 (cycle 32) established
//! for main.rs: `# Generated by the nucleus pre-compiler.` This
//! drops the stale "pthreads-sync backend" provenance lie now that
//! the templates live in `backend-common` and serve every single-
//! binary backend. The byte-identical differential between
//! pthreads-sync + pthreads-async still holds (both consume the
//! SAME helper, so their emitted Cargo.toml + run.sh are byte-equal
//! to each other modulo the per-cell scratch path, which the cross-
//! backend tests already strip).

/// Typed slot for the optional `[dependencies]` section a generated
/// Cargo.toml may carry (TASK-0288 — replaces the original raw
/// `Option<&str>` textual passthrough that TASK-0257 P2.1 flagged).
///
/// # What this models — and what it deliberately does NOT
///
/// A `CargoDependencies` is the BODY of a single, optional
/// `[dependencies]` section: the dependency entries plus any `#`
/// comment lines that explain them. The `[dependencies]` header
/// itself is owned by the renderer, never by the caller's string.
/// [`CargoDependencies::none`] emits no section at all (byte-stable
/// shape for the dependency-free backends); [`CargoDependencies::
/// section_body`] interpolates the supplied verbatim body inside one
/// `[dependencies]` section.
///
/// It does NOT model `[dev-dependencies]`, `[build-dependencies]`,
/// target-specific dependency tables, or multiple sections. The
/// original `Option<&str>` parameter — named "dependencies" but in
/// fact a free-form TOML passthrough — silently let a caller jam any
/// of those through; the whole point of this type is to close that
/// hole (the constructor names the contract, and `render_into`
/// asserts no body line opens a `[section]` header — the type alone
/// could not reject a smuggled header in a &str body). No real
/// caller needs a second section
/// today (verified across all nine call sites: mpi-blocking /
/// mpi-nonblocking pass `mpi = "0.8"`, openmp-rs passes `rayon =
/// "1"`, mp-tcp-event / mp-uds-event pass a commented `mio` block,
/// every other arm passes [`none`](CargoDependencies::none)). When a
/// real second section type materialises, add a typed field for it
/// here — do not reach back to the free-form string.
///
/// # Body verbatim-ness
///
/// The body is stored verbatim (comments and all) precisely because
/// the real `mio` bodies interleave explanatory `#` comments with the
/// `mio = { ... }` entry. A structured key/value map would not
/// round-trip those comments byte-for-byte; preserving the emitted
/// Cargo.toml byte-for-byte across this lift is the load-bearing
/// invariant (TASK-0288 AC#2), so the body stays an opaque verbatim
/// string. Trailing-newline normalisation (in the private
/// `render_into` helper) means a caller may supply the body with or
/// without a trailing `\n` and get the same bytes.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct CargoDependencies<'a> {
    /// `None` => no `[dependencies]` section is emitted. `Some(body)`
    /// => exactly one `[dependencies]` section with `body` as its
    /// verbatim contents.
    section_body: Option<&'a str>,
}

impl<'a> CargoDependencies<'a> {
    /// No `[dependencies]` section. The byte-stable shape every
    /// dependency-free backend arm relies on (pthreads-sync,
    /// pthreads-async, the single-worker arms of openmp-rs / the
    /// mp-* backends). Equivalent to the original `extra_dependencies
    /// = None`.
    pub const fn none() -> Self {
        Self { section_body: None }
    }

    /// One `[dependencies]` section with `body` as its verbatim
    /// contents (entries plus any leading `#` comment lines). The
    /// caller MUST NOT include the `[dependencies]` header line —
    /// the renderer emits it. Equivalent to the original
    /// `extra_dependencies = Some(body)`.
    pub const fn section_body(body: &'a str) -> Self {
        Self {
            section_body: Some(body),
        }
    }

    /// Interpolate the `[dependencies]` section (if any) into `s`,
    /// which must already end at the point a `[dependencies]` section
    /// would begin (i.e. just after the `[workspace]` block's
    /// trailing blank line). Shared by both
    /// [`single_binary::render_cargo_toml`] and
    /// [`multi_binary::render_cargo_toml`] so the section shape —
    /// header, verbatim body, and the exactly-one-blank-line spacing
    /// before whatever follows — is byte-identical across the two
    /// project layouts (it always was; this just makes the shared
    /// shape a single source of truth rather than two copies).
    ///
    /// Trailing-newline normalisation: the body may arrive with or
    /// without a trailing `\n`; either way the result ends with
    /// exactly one blank line (`"\n\n"`) so the section that follows
    /// (`[[bin]]`) starts at a byte-stable offset.
    fn render_into(&self, s: &mut String) {
        let Some(body) = self.section_body else {
            return;
        };
        // Enforcement for the type's whole point (wave-7 review P2):
        // the body must be entries-only — a smuggled `[section]` header
        // would silently re-open the free-form passthrough this type
        // exists to close. Same assert-defended-passthrough pattern as
        // `render_run_sh_multi`'s so_buf_comment_block.
        for line in body.lines() {
            assert!(
                !line.trim_start().starts_with('['),
                "CargoDependencies::section_body must contain dependency \
                 entries only, not a TOML section header; got line: {line:?}"
            );
        }
        s.push_str("[dependencies]\n");
        s.push_str(body);
        if !s.ends_with("\n\n") {
            if !s.ends_with('\n') {
                s.push('\n');
            }
            s.push('\n');
        }
    }
}

/// Project-skeleton renderers for the SINGLE-BINARY tier-1 backends
/// (`pthreads-sync`, `pthreads-async`). Both emit one Cargo project
/// with one `[[bin]]` target named `nuc-generated`; the only
/// per-backend variation is the `main.rs` body, not the project
/// skeleton, so the templates are shared verbatim.
pub mod single_binary {
    use super::CargoDependencies;

    /// Emit the standalone Cargo.toml the generated project ships.
    ///
    /// Shared by pthreads-sync + pthreads-async + openmp-rs (TASK-0246
    /// for the first two; TASK-0044.01.01 cycle 196 added the
    /// `deps` parameter for openmp-rs's multi-worker arm which needs
    /// `rayon = "1"` in the emitted `[dependencies]` section; TASK-0288
    /// replaced that raw `Option<&str>` with the typed
    /// [`CargoDependencies`] slot). The `nuc-generated` binary name is
    /// deliberately backend-agnostic: the choice of single-binary
    /// backend only changes per-loop codegen, not the project
    /// skeleton.
    ///
    /// [`CargoDependencies::none`] (the byte-stable original shape)
    /// emits NO `[dependencies]` section — used by pthreads-sync,
    /// pthreads-async, and openmp-rs's SINGLE-worker arm (every
    /// single-worker emit must remain byte-identical across the three
    /// single-binary backends; the cross-backend differential test
    /// `openmp-rs/tests/single_worker_emit.rs::
    /// single_worker_empty_eventlist_emits_byte_identical_to_pthreads_sync`
    /// pins that invariant).
    ///
    /// [`CargoDependencies::section_body`] interpolates the verbatim
    /// body into a `[dependencies]` section between the `[workspace]`
    /// block and the `[[bin]]` target (same shared private
    /// `render_into` path
    /// [`super::multi_binary::render_cargo_toml`] uses). Used by
    /// openmp-rs's MULTI-worker arm to emit `rayon = "1"` and by
    /// mpi-blocking / mpi-nonblocking to emit `mpi = "0.8"`.
    pub fn render_cargo_toml(deps: CargoDependencies<'_>) -> String {
        let mut s = String::from(
            "# Generated by the nucleus pre-compiler. Do not edit; rerun \
             `nucleus build` to regenerate.\n\
             [package]\n\
             name        = \"nuc-generated\"\n\
             version     = \"0.0.0\"\n\
             edition     = \"2021\"\n\
             publish     = false\n\
             \n\
             [workspace]\n\
             # Empty: this crate is standalone, not part of any parent workspace.\n\
             \n",
        );
        // Optional `[dependencies]` section via the shared typed slot
        // (TASK-0288). Byte-identical to the prior inline
        // interpolation: same header, verbatim body, and exactly-one-
        // blank-line normalisation before `[[bin]]`.
        deps.render_into(&mut s);
        s.push_str(
            "[[bin]]\n\
             name = \"nuc-generated\"\n\
             path = \"src/main.rs\"\n\
             \n\
             [profile.release]\n\
             panic = \"abort\"\n",
        );
        s
    }

    /// Emit the run.sh the generated project ships.
    ///
    /// Shared by pthreads-sync + pthreads-async (TASK-0246). Builds
    /// the release binary with `cargo build --release` then invokes
    /// `target/release/nuc-generated` with `NUC_INPUT_PATH` /
    /// `NUC_OUTPUT_PATH` env vars wired from the script's two
    /// positional args (default: `input.bin` / `output.bin`).
    pub fn render_run_sh() -> String {
        String::from(
            "#!/usr/bin/env bash\n\
             # Generated by the nucleus pre-compiler. Rerun `nucleus build` to regenerate.\n\
             # Usage: bash run.sh INPUT_BIN OUTPUT_BIN\n\
             set -euo pipefail\n\
             \n\
             here=\"$(cd -- \"$(dirname -- \"${BASH_SOURCE[0]}\")\" && pwd)\"\n\
             input_bin=\"${1:-input.bin}\"\n\
             output_bin=\"${2:-output.bin}\"\n\
             \n\
             (cd \"$here\" && cargo build --release --quiet)\n\
             \n\
             NUC_INPUT_PATH=\"$input_bin\" \\\n\
             NUC_OUTPUT_PATH=\"$output_bin\" \\\n\
             \"$here/target/release/nuc-generated\"\n",
        )
    }
}

/// Project-skeleton renderers for the MULTI-BINARY tier-1 backends
/// (`mp-tcp-bufsync`, `mp-tcp-event`). Both emit N `[[bin]]` targets
/// at `src/bin/<name>.rs` and orchestrate them via a launcher
/// `run.sh`. The single-worker fallback (`used_workers <= 1`) reuses
/// the multi-binary Cargo layout (one `[[bin]]` named `nuc-generated`
/// at `src/bin/nuc-generated.rs`) and a simplified single-process
/// `run.sh` that calls just that one binary.
///
/// TASK-0257 (cycle 112) lifted these from the per-backend copies
/// they had grown in during cycles 32 (mp-tcp-bufsync) and 79
/// (mp-tcp-event Stage 3). The post-lift emit bytes drift from the
/// pre-lift bytes ONLY in the file headers (mp-tcp-bufsync /
/// mp-tcp-event tags collapse into the neutral `nucleus pre-compiler`
/// form, same precedent TASK-0246 established for [`single_binary`]
/// in cycle 38). Runtime output bytes are unchanged; the cross-
/// backend differential against the independent `reference.bin`
/// oracle still bites.
pub mod multi_binary {
    use super::CargoDependencies;
    use std::fmt::Write as _;

    /// Emit the Cargo.toml the generated multi-binary project ships.
    ///
    /// One `[[bin]]` per `bin_names` entry, pointing at `src/bin/
    /// <name>.rs`. [`CargoDependencies::section_body`] interpolates
    /// the supplied verbatim body into a `[dependencies]` section
    /// before the `[[bin]]` targets — used by `mp-tcp-event` /
    /// `mp-uds-event` to pull in `mio`; `mp-tcp-bufsync` / `mp-tcp-poll`
    /// pass [`CargoDependencies::none`] (no external deps). TASK-0288
    /// replaced the prior raw `Option<&str>` passthrough with the
    /// typed slot.
    ///
    /// Header: neutral `# Generated by the nucleus pre-compiler.`
    /// (TASK-0257 follows the TASK-0246 single_binary precedent —
    /// per-backend provenance is recorded in the per-worker `.rs`
    /// file headers via each backend's `render_worker_program`, not
    /// the project skeleton).
    pub fn render_cargo_toml(bin_names: &[String], deps: CargoDependencies<'_>) -> String {
        let mut s = String::from(
            "# Generated by the nucleus pre-compiler. Do not edit; rerun \
             `nucleus build` to regenerate.\n\
             [package]\n\
             name        = \"nuc-generated\"\n\
             version     = \"0.0.0\"\n\
             edition     = \"2021\"\n\
             publish     = false\n\
             \n\
             [workspace]\n\
             # Empty: standalone, not part of any parent workspace.\n\
             \n",
        );
        // Optional `[dependencies]` section via the shared typed slot
        // (TASK-0288). Byte-identical to the prior inline
        // interpolation: same header, verbatim body, and exactly-one-
        // blank-line normalisation before the `[[bin]]` targets.
        deps.render_into(&mut s);
        for b in bin_names {
            // Each worker is its own binary target. `src/bin/<name>.rs`
            // is the conventional auto-discovered location but we
            // declare it explicitly so the manifest is the single
            // source of truth for which binaries exist (deterministic,
            // greppable).
            writeln!(s, "[[bin]]").ok();
            writeln!(s, "name = \"{b}\"").ok();
            writeln!(s, "path = \"src/bin/{b}.rs\"").ok();
            writeln!(s).ok();
        }
        s.push_str("[profile.release]\npanic = \"abort\"\n");
        s
    }

    /// Single-process run.sh: build + run the one binary at
    /// `target/release/nuc-generated`. Used by both mp-tcp-bufsync
    /// and mp-tcp-event when `used_workers <= 1`. Mirrors the
    /// pthreads-sync run.sh contract (INPUT_BIN OUTPUT_BIN positional).
    pub fn render_run_sh_single() -> String {
        String::from(
            "#!/usr/bin/env bash\n\
             # Generated by the nucleus pre-compiler (multi-binary backend, \
             single-process fallback: 0/1 used workers). Rerun `nucleus build` to regenerate.\n\
             # Usage: bash run.sh INPUT_BIN OUTPUT_BIN\n\
             set -euo pipefail\n\
             \n\
             here=\"$(cd -- \"$(dirname -- \"${BASH_SOURCE[0]}\")\" && pwd)\"\n\
             input_bin=\"${1:-input.bin}\"\n\
             output_bin=\"${2:-output.bin}\"\n\
             \n\
             (cd \"$here\" && cargo build --release --quiet)\n\
             \n\
             NUC_INPUT_PATH=\"$input_bin\" \\\n\
             NUC_OUTPUT_PATH=\"$output_bin\" \\\n\
             \"$here/target/release/nuc-generated\"\n",
        )
    }

    /// Multi-process run.sh: launch one process per used worker, host
    /// first. Sets up the shared rendezvous directory (TASK-0176) the
    /// host workers use to publish their kernel-assigned ports +
    /// EXIT-trap cleanup, exports `NUC_SO_BUF` for socket-buffer
    /// sizing, waits for every worker, returns non-zero (naming the
    /// worker) on any failure.
    ///
    /// `host_name`: stable name of the host worker (launched first).
    /// `non_host_names_plan_order`: stable names of the non-host
    /// workers, in plan-order (deterministic). The launch loop emits
    /// them in the supplied order — host first, then this slice in
    /// order — and the wait loop names each worker for failure
    /// diagnostics in the same order. The parameter name carries
    /// the order-sensitivity contract; passing a hashset-shuffled or
    /// sorted slice from a future call site would be a silent
    /// determinism regression (TASK-0257 cycle-112 architect P2.3).
    /// `so_buf_bytes`: derived per-backend from the largest cross-
    /// worker payload (sync sizing for mp-tcp-bufsync; wire-frame
    /// sizing for mp-tcp-event since application-ring buffering
    /// handles `buffer=N`). The 64 KiB floor is applied at the
    /// callsite, not here, to keep this function backend-agnostic.
    /// `so_buf_comment_block`: full multi-line comment text above
    /// the `export NUC_SO_BUF=...` line — each backend explains its
    /// sizing rationale (`sync=1 msg` for mp-tcp-bufsync; the wire-
    /// vs-ring distinction for mp-tcp-event). Every line must be
    /// blank or `#`-prefixed; a debug-assertion enforces this so a
    /// future caller cannot silently break the shell-comment shape
    /// (TASK-0257 cycle-112 architect P2.2 hardening — the invariant
    /// was previously documented but not type-/assert-enforced).
    pub fn render_run_sh_multi(
        host_name: &str,
        non_host_names_plan_order: &[String],
        so_buf_bytes: usize,
        so_buf_comment_block: &str,
    ) -> String {
        // TASK-0257 P2.2: the `so_buf_comment_block` contract is
        // "every line is a shell comment". Catch a non-comment line
        // BEFORE it ships in the emit; the lift's whole point is to
        // make the per-backend SO_BUF rationale a documented parameter,
        // and an un-prefixed line would silently break the shell
        // semantics (treated as a bare command on `bash run.sh`).
        //
        // `assert!` (not `debug_assert!`) so the bite is profile-agnostic
        // — closing TASK-0291. The check is a single linear scan of a
        // ~few-line static comment string at codegen time, nowhere near
        // a hot loop, so the runtime cost is irrelevant.
        assert!(
            so_buf_comment_block
                .lines()
                .all(|l| l.is_empty() || l.starts_with('#')),
            "render_run_sh_multi: every line of `so_buf_comment_block` MUST be blank or `#`-prefixed (shell comment). Got: {so_buf_comment_block:?}"
        );
        let mut s = String::new();
        writeln!(s, "#!/usr/bin/env bash").ok();
        writeln!(
            s,
            "# Generated by the nucleus pre-compiler (multi-binary backend, multi-process)."
        )
        .ok();
        writeln!(s, "# Usage: bash run.sh INPUT_BIN OUTPUT_BIN").ok();
        writeln!(s, "set -uo pipefail").ok();
        writeln!(s).ok();
        writeln!(
            s,
            "here=\"$(cd -- \"$(dirname -- \"${{BASH_SOURCE[0]}}\")\" && pwd)\""
        )
        .ok();
        writeln!(s, "input_bin=\"${{1:-input.bin}}\"").ok();
        writeln!(s, "output_bin=\"${{2:-output.bin}}\"").ok();
        writeln!(s).ok();
        writeln!(s, "(cd \"$here\" && cargo build --release --quiet)").ok();
        writeln!(s).ok();
        // Rendezvous directory + EXIT trap (TASK-0176): each host
        // worker binds 127.0.0.1:0 ITSELF (OS-assigned ephemeral port)
        // and writes the port to `$NUC_RENDEZVOUS_DIR/<worker>.port`
        // atomically (tmp-file + rename). The non-host worker polls-
        // with-retry on that file, reads the port, then connects. The
        // worker that *uses* the port also *allocates* it — no close-
        // then-rebind window, no race for the port between picker-exit
        // and host-bind. `$$` (run.sh's pid) suffix isolates concurrent
        // matrix cells from each other. Cleaned on EXIT (trap) so
        // both successful + failed runs tidy up.
        writeln!(
            s,
            "NUC_RENDEZVOUS_DIR=\"$here/.nuc-rendezvous-$$\"\n\
             mkdir -p \"$NUC_RENDEZVOUS_DIR\"\n\
             trap 'rm -rf \"$NUC_RENDEZVOUS_DIR\"' EXIT\n\
             export NUC_RENDEZVOUS_DIR"
        )
        .ok();
        writeln!(s).ok();
        // Per-backend SO_BUF commentary block (caller-supplied,
        // already `#`-prefixed) then the export.
        s.push_str(so_buf_comment_block);
        if !s.ends_with('\n') {
            s.push('\n');
        }
        writeln!(s, "export NUC_SO_BUF={so_buf_bytes}").ok();
        writeln!(s).ok();
        // Host first so its listener is binding while workers spin
        // up (workers retry-connect anyway; this just minimises
        // retries).
        writeln!(
            s,
            "NUC_INPUT_PATH=\"$input_bin\" NUC_OUTPUT_PATH=\"$output_bin\" \\\n\
             \x20\x20\"$here/target/release/{host_name}\" &\n\
             PID_{host_name}=$!"
        )
        .ok();
        for nwn in non_host_names_plan_order {
            writeln!(
                s,
                "NUC_INPUT_PATH=\"$input_bin\" NUC_OUTPUT_PATH=\"$output_bin\" \\\n\
                 \x20\x20\"$here/target/release/{nwn}\" &\n\
                 PID_{nwn}=$!"
            )
            .ok();
        }
        writeln!(s).ok();
        // Wait for every worker; non-zero (naming the worker) if any
        // fails. `wait <pid>` returns that child's status.
        writeln!(s, "rc=0").ok();
        let mut all = vec![host_name.to_string()];
        all.extend(non_host_names_plan_order.iter().cloned());
        for n in &all {
            writeln!(
                s,
                "if ! wait \"$PID_{n}\"; then echo \"run.sh: worker '{n}' failed (exit $?)\" >&2; rc=1; fi"
            )
            .ok();
        }
        writeln!(s, "exit \"$rc\"").ok();
        s
    }
}

#[cfg(test)]
mod tests {
    use super::single_binary::{render_cargo_toml, render_run_sh};
    use super::CargoDependencies;

    /// The Cargo.toml header is the FIRST line emitted; the
    /// cross-backend byte-identical invariants
    /// (pthreads-async/tests/skeleton.rs,
    /// mp-tcp-bufsync/tests/pingpong.rs) depend on it being stable.
    /// TASK-0246 (cycle 38) updated the header from
    /// `# Generated by the pthreads-sync backend.` to the neutral
    /// `# Generated by the nucleus pre-compiler.` (same form
    /// TASK-0231 already established for main.rs); the assertion
    /// below pins the new form.
    #[test]
    fn cargo_toml_header_byte_stable() {
        let s = render_cargo_toml(CargoDependencies::none());
        assert!(
            s.starts_with("# Generated by the nucleus pre-compiler."),
            "Cargo.toml header drifted: {:?}",
            &s[..s.find('\n').unwrap_or(s.len())]
        );
    }

    /// Mirrors the Cargo.toml header test. The run.sh shebang +
    /// header are the first two lines.
    #[test]
    fn run_sh_header_byte_stable() {
        let s = render_run_sh();
        assert!(s.starts_with("#!/usr/bin/env bash\n"));
        assert!(
            s.contains("# Generated by the nucleus pre-compiler."),
            "run.sh header drifted"
        );
    }

    /// The Cargo.toml must declare exactly ONE [[bin]] target named
    /// `nuc-generated` pointing at `src/main.rs`. Backends choose
    /// single-binary vs multi-binary by selecting the template, not
    /// by post-processing the string.
    #[test]
    fn cargo_toml_emits_single_bin_target() {
        let s = render_cargo_toml(CargoDependencies::none());
        assert_eq!(s.matches("[[bin]]").count(), 1);
        assert!(s.contains("name = \"nuc-generated\""));
        assert!(s.contains("path = \"src/main.rs\""));
    }

    /// TASK-0044.01.01 cycle 196: [`CargoDependencies::none`] MUST
    /// NOT emit a `[dependencies]` block. This is the byte-stable
    /// shape pthreads-sync, pthreads-async, and openmp-rs's
    /// single-worker arm all rely on (the cross-backend single-worker
    /// differential is anchored on this byte equality).
    #[test]
    fn cargo_toml_omits_dependencies_when_none() {
        let s = render_cargo_toml(CargoDependencies::none());
        assert!(
            !s.contains("[dependencies]"),
            "[dependencies] section MUST NOT appear for CargoDependencies::none(); got:\n{s}"
        );
    }

    /// TASK-0044.01.01 cycle 196: [`CargoDependencies::section_body`]
    /// interpolates the supplied content as a `[dependencies]` block
    /// between `[workspace]` and `[[bin]]`. This is the openmp-rs
    /// multi-worker shape (pulls in `rayon`). The block MUST appear
    /// before the `[[bin]]` target so Cargo parses the manifest in
    /// the conventional order.
    #[test]
    fn cargo_toml_emits_dependencies_when_some() {
        let deps = "rayon = \"1\"\n";
        let s = render_cargo_toml(CargoDependencies::section_body(deps));
        assert!(
            s.contains("[dependencies]\n"),
            "[dependencies] section MUST appear for CargoDependencies::section_body; got:\n{s}"
        );
        assert!(
            s.contains("rayon = \"1\""),
            "supplied deps content MUST be interpolated verbatim; got:\n{s}"
        );
        let deps_pos = s.find("[dependencies]").expect("[dependencies] present");
        let bin_pos = s.find("[[bin]]").expect("[[bin]] present");
        assert!(
            deps_pos < bin_pos,
            "[dependencies] must precede [[bin]] in:\n{s}"
        );
    }

    /// [`CargoDependencies::section_body`] accepts a body string with
    /// OR without a trailing newline. The post-deps spacing is
    /// byte-stable across callers (exactly one blank line before
    /// `[[bin]]`). The normalisation lives in the private
    /// `CargoDependencies::render_into` helper, shared with
    /// `multi_binary::render_cargo_toml`.
    #[test]
    fn cargo_toml_normalises_trailing_newline_on_extra_deps() {
        let with_nl = render_cargo_toml(CargoDependencies::section_body("rayon = \"1\"\n"));
        let without_nl = render_cargo_toml(CargoDependencies::section_body("rayon = \"1\""));
        assert_eq!(
            with_nl, without_nl,
            "trailing-newline on deps MUST be normalised away (byte-stable post-deps shape)"
        );
    }
}

#[cfg(test)]
mod multi_binary_tests {
    use super::multi_binary::{render_cargo_toml, render_run_sh_multi, render_run_sh_single};
    use super::CargoDependencies;

    /// Cargo.toml header is the FIRST line and the load-bearing
    /// regression canary. Same neutral form single_binary uses
    /// (TASK-0257 follows the TASK-0246 precedent).
    #[test]
    fn cargo_toml_header_byte_stable() {
        let s = render_cargo_toml(
            &[String::from("host"), String::from("w0")],
            CargoDependencies::none(),
        );
        assert!(
            s.starts_with("# Generated by the nucleus pre-compiler."),
            "multi_binary Cargo.toml header drifted: {:?}",
            &s[..s.find('\n').unwrap_or(s.len())]
        );
    }

    /// One `[[bin]]` per `bin_names` entry, in supplied order. Pinning
    /// count guards against a `for b in bin_names` regression that
    /// would emit zero or duplicate targets.
    #[test]
    fn cargo_toml_emits_one_bin_per_name() {
        let names = vec![
            String::from("host"),
            String::from("w0"),
            String::from("w1"),
            String::from("w2"),
        ];
        let s = render_cargo_toml(&names, CargoDependencies::none());
        assert_eq!(s.matches("[[bin]]").count(), 4);
        for n in &names {
            assert!(
                s.contains(&format!("name = \"{n}\"")),
                "missing [[bin]] target for {n} in:\n{s}"
            );
            assert!(
                s.contains(&format!("path = \"src/bin/{n}.rs\"")),
                "missing src/bin/{n}.rs path entry in:\n{s}"
            );
        }
        assert!(s.contains("[profile.release]\npanic = \"abort\"\n"));
    }

    /// [`CargoDependencies::none`] MUST NOT emit a `[dependencies]`
    /// block. This is the mp-tcp-bufsync shape (no external crates).
    #[test]
    fn cargo_toml_omits_dependencies_when_none() {
        let s = render_cargo_toml(&[String::from("nuc-generated")], CargoDependencies::none());
        assert!(
            !s.contains("[dependencies]"),
            "[dependencies] section MUST NOT appear for CargoDependencies::none(); got:\n{s}"
        );
    }

    /// [`CargoDependencies::section_body`] emits a `[dependencies]`
    /// block with the supplied content, before the `[[bin]]` targets.
    /// This is the mp-tcp-event shape (pulls in `mio`).
    #[test]
    fn cargo_toml_emits_dependencies_when_some() {
        let deps = "mio = { version = \"0.8\", default-features = false, features = [\"os-poll\", \"net\"] }\n";
        let s = render_cargo_toml(
            &[String::from("nuc-generated")],
            CargoDependencies::section_body(deps),
        );
        assert!(
            s.contains("[dependencies]\n"),
            "[dependencies] section MUST appear for CargoDependencies::section_body; got:\n{s}"
        );
        assert!(
            s.contains("mio = { version = \"0.8\""),
            "supplied deps content MUST be interpolated verbatim; got:\n{s}"
        );
        // [dependencies] block must precede the [[bin]] targets.
        let deps_pos = s.find("[dependencies]").expect("[dependencies] present");
        let bin_pos = s.find("[[bin]]").expect("[[bin]] present");
        assert!(deps_pos < bin_pos);
    }

    /// Single-process run.sh has the neutral header + shebang +
    /// `target/release/nuc-generated` invocation. Mirrors the
    /// single_binary contract.
    #[test]
    fn run_sh_single_header_byte_stable() {
        let s = render_run_sh_single();
        assert!(s.starts_with("#!/usr/bin/env bash\n"));
        assert!(
            s.contains("# Generated by the nucleus pre-compiler"),
            "run_sh_single header drifted: got first lines:\n{}",
            &s[..s.find("\n\n").unwrap_or(s.len())]
        );
        assert!(s.contains("\"$here/target/release/nuc-generated\"\n"));
    }

    /// Multi-process run.sh launches host first, then non-host
    /// workers in supplied order. The wait loop names each worker
    /// for failure diagnostics in the same order.
    ///
    /// TASK-0257 cycle-112 architect P2.3 hardening: the test passes
    /// a DELIBERATELY non-sorted slice (`w1` before `w0`) and
    /// asserts the emitted PID assignment order matches the SUPPLIED
    /// order, not lexicographic / numeric / sorted. A future caller
    /// that hashed or sorted the workers before calling would silently
    /// change the emit order; this test bites such a caller AND would
    /// also bite a refactor that internally sorts within
    /// `render_run_sh_multi`. The contract surface is `_plan_order`.
    #[test]
    fn run_sh_multi_launches_host_then_non_host_in_order() {
        let s = render_run_sh_multi(
            "host",
            // Deliberately not sorted: w1 BEFORE w0. Plan-order
            // discipline says we emit them in the supplied order.
            &[String::from("w1"), String::from("w0")],
            65536,
            "# test SO_BUF commentary\n",
        );
        assert!(s.starts_with("#!/usr/bin/env bash\n"));
        // Host PID assignment appears before any non-host PID
        // assignment.
        let host_pid_pos = s.find("PID_host=$!").expect("host PID assignment present");
        let w1_pid_pos = s.find("PID_w1=$!").expect("w1 PID assignment present");
        let w0_pid_pos = s.find("PID_w0=$!").expect("w0 PID assignment present");
        assert!(host_pid_pos < w1_pid_pos);
        // The supplied non-sorted order MUST be preserved: w1 first,
        // w0 second.
        assert!(
            w1_pid_pos < w0_pid_pos,
            "render_run_sh_multi MUST preserve the supplied `non_host_names_plan_order` slice order. \
             A future refactor that internally sorts the slice would silently change emit order \
             and bite the determinism gate at a distance. Got w0 before w1 in:\n{s}"
        );
        // Each worker has a wait + fail-named-worker line.
        for n in &["host", "w1", "w0"] {
            assert!(
                s.contains(&format!("if ! wait \"$PID_{n}\"")),
                "missing wait loop for worker {n} in:\n{s}"
            );
            assert!(s.contains(&format!("worker '{n}' failed")));
        }
        // Wait-loop also preserves supplied order: wait for w1 before
        // waiting for w0 (host wait still first).
        let wait_w1_pos = s.find("wait \"$PID_w1\"").expect("w1 wait line present");
        let wait_w0_pos = s.find("wait \"$PID_w0\"").expect("w0 wait line present");
        assert!(wait_w1_pos < wait_w0_pos);
    }

    /// `so_buf_comment_block` is interpolated verbatim before the
    /// `export NUC_SO_BUF=...` line. Pinning the verbatim interpolation
    /// guards against a future refactor that silently strips or
    /// rewrites the per-backend commentary.
    #[test]
    fn run_sh_multi_interpolates_so_buf_comment_verbatim() {
        let comment = "# the lazy fox\n# jumps over\n# the quick brown dog\n";
        let s = render_run_sh_multi("host", &[], 12345, comment);
        assert!(
            s.contains(comment),
            "so_buf_comment_block MUST appear verbatim before NUC_SO_BUF; got:\n{s}"
        );
        let comment_end = s.find(comment).unwrap() + comment.len();
        let nuc_so_buf_pos = s
            .find("export NUC_SO_BUF=12345")
            .expect("NUC_SO_BUF present");
        assert!(
            comment_end <= nuc_so_buf_pos,
            "so_buf_comment_block MUST precede the NUC_SO_BUF export"
        );
    }

    /// TASK-0257 cycle-112 architect P2.2 hardening: a non-comment
    /// line in `so_buf_comment_block` would silently break the shell
    /// semantics on `bash run.sh` (the line would be treated as a
    /// bare command). The `assert!` in `render_run_sh_multi` catches
    /// the contract violation; this test verifies the bite.
    ///
    /// TASK-0291 cycle: was previously a `debug_assert!` + this test
    /// failed under `cargo test --release` (debug_asserts stripped);
    /// converted to `assert!` so the bite is profile-agnostic.
    #[test]
    #[should_panic(expected = "every line of `so_buf_comment_block`")]
    fn run_sh_multi_asserts_so_buf_comment_lines_are_shell_comments() {
        // Second line is a bare command — would be a shell defect if
        // it ever shipped. The debug-assert MUST bite this in debug.
        let bad_comment = "# legitimate\nthis-is-not-a-comment\n";
        let _ = render_run_sh_multi("host", &[], 1, bad_comment);
    }

    /// Rendezvous directory + EXIT trap (TASK-0176 contract) emit
    /// verbatim in the multi-process run.sh.
    #[test]
    fn run_sh_multi_emits_rendezvous_dir_with_exit_trap() {
        let s = render_run_sh_multi("host", &[String::from("w0")], 65536, "# x\n");
        assert!(s.contains("NUC_RENDEZVOUS_DIR=\"$here/.nuc-rendezvous-$$\""));
        assert!(s.contains("trap 'rm -rf \"$NUC_RENDEZVOUS_DIR\"' EXIT"));
        assert!(s.contains("export NUC_RENDEZVOUS_DIR"));
    }
}

/// TASK-0288: unit tests for the typed [`CargoDependencies`] slot
/// itself — the constructors, the verbatim-body contract, and the
/// renderer-owns-the-header invariant the type exists to enforce.
/// These exercise both `render_cargo_toml` entry points so the typed
/// shape is pinned independent of which project layout consumes it.
#[cfg(test)]
mod cargo_dependencies_tests {
    use super::{multi_binary, single_binary, CargoDependencies};

    /// `Default` and `none()` agree (both = no section). Pins the
    /// derive so a future field addition cannot silently make
    /// `Default` emit a section.
    #[test]
    fn default_equals_none() {
        assert_eq!(CargoDependencies::default(), CargoDependencies::none());
    }

    /// The header is owned by the RENDERER, not the caller. A real
    /// `mio` body (comment lines + one `mio = { ... }` entry) is
    /// interpolated verbatim, and the body the caller supplied must
    /// NOT itself contain a `[dependencies]` header line — i.e. the
    /// emitted Cargo.toml has exactly ONE `[dependencies]` section
    /// even though the body is a multi-line comment-bearing block.
    /// This is the invariant the typed slot exists to make
    /// impossible to violate by jamming a second section header
    /// through a free-form string.
    #[test]
    fn section_body_is_interpolated_verbatim_under_one_owned_header() {
        let mio_body = "# explanatory comment line\n\
                        mio = { version = \"0.8\", default-features = false, features = [\"os-poll\", \"net\"] }\n";
        let s = single_binary::render_cargo_toml(CargoDependencies::section_body(mio_body));
        // Exactly one [dependencies] header — the renderer's, never
        // the caller's. The verbatim comment + entry are both present.
        assert_eq!(
            s.matches("[dependencies]").count(),
            1,
            "renderer MUST emit exactly one [dependencies] header; got:\n{s}"
        );
        assert!(s.contains("# explanatory comment line\n"));
        assert!(s.contains("mio = { version = \"0.8\""));
    }

    /// AC#3: the typed shape is the single source of truth for the
    /// `[dependencies]` section across BOTH project layouts. The
    /// section body (header + verbatim contents + the one-blank-line
    /// spacing that follows) emitted by `single_binary` and
    /// `multi_binary` for the SAME [`CargoDependencies`] is
    /// byte-identical — they share the private `render_into` helper.
    /// Were a second typed section ever added (e.g. a `dev:` field),
    /// this cross-layout equality is the regression that guards it.
    #[test]
    fn dependencies_section_is_byte_identical_across_both_layouts() {
        let body = "rayon = \"1\"\n";
        let single = single_binary::render_cargo_toml(CargoDependencies::section_body(body));
        let multi = multi_binary::render_cargo_toml(
            &[String::from("nuc-generated")],
            CargoDependencies::section_body(body),
        );
        // Slice each emit from the `[dependencies]` header to just
        // before its first `[[bin]]` target; those slices are the
        // shared section and MUST be byte-equal.
        let dep_slice = |s: &str| -> String {
            let start = s.find("[dependencies]").expect("[dependencies] present");
            let end = s.find("[[bin]]").expect("[[bin]] present");
            s[start..end].to_string()
        };
        assert_eq!(
            dep_slice(&single),
            dep_slice(&multi),
            "the [dependencies] section MUST be byte-identical across single_binary + multi_binary \
             (both share CargoDependencies::render_into)"
        );
    }

    /// Trailing-newline normalisation lives in the typed slot and so
    /// is shared by both layouts: a body with or without a trailing
    /// `\n` yields byte-identical output in EACH layout. (The
    /// single_binary copy of this is in `mod tests`; this pins the
    /// multi_binary side too, closing the silent-sibling gap.)
    #[test]
    fn trailing_newline_normalised_in_multi_binary_too() {
        let names = [String::from("nuc-generated")];
        let with_nl =
            multi_binary::render_cargo_toml(&names, CargoDependencies::section_body("rayon = \"1\"\n"));
        let without_nl =
            multi_binary::render_cargo_toml(&names, CargoDependencies::section_body("rayon = \"1\""));
        assert_eq!(
            with_nl, without_nl,
            "trailing-newline on the body MUST be normalised away in multi_binary too"
        );
    }
}
