//! Project-skeleton renderers — string templates for the standalone
//! Cargo project a backend emits. TASK-0246 (cycle 38).
//!
//! # Why this lives in backend-common
//!
//! Through cycles 17/22/24/31 these renderers grew inside
//! `pthreads-sync` (the first single-binary backend) and pthreads-async
//! imported them via `pthreads_sync::render_cargo_toml` /
//! `render_run_sh`. Cycle 37 (TASK-0244) extracted most of the shared
//! codegen surface into `backend-common` but LEFT these two string
//! templates in pthreads-sync. That residual arrow was not a genuine
//! semantic delegation — the templates are inert strings, identical
//! across pthreads-sync + pthreads-async, with no pthreads-sync-
//! specific content. TASK-0246 (cycle 38) finishes the move: the
//! templates now live in `backend_common::project_skeleton`, and the
//! only inter-backend arrow that survives is
//! `pthreads_sync::render_single_worker_main` (a real semantic
//! delegation: pthreads-async's single-worker arm IS pthreads-sync's
//! straight-line main.rs, byte-identical by construction).
//!
//! # Module shape
//!
//! - [`single_binary`] — Cargo.toml + run.sh for backends that emit
//!   ONE binary into a single Cargo project (`pthreads-sync`,
//!   `pthreads-async`). The shape is "one [[bin]] target named
//!   `nuc-generated`, panic = abort release profile, run.sh that
//!   wraps `cargo build --release` + `target/release/nuc-generated`".
//!
//! The multi-process variant for `mp-tcp-bufsync` (which emits N
//! `[[bin]]` targets and a launcher that orchestrates worker
//! processes) stays in `mp-tcp-bufsync` because its signature
//! (`render_cargo_toml(bin_names: &[String])`) and its substrate
//! (TCP, free-port picker, multi-process launcher) are genuinely
//! mp-tcp-bufsync-specific, not a shareable template.
//!
//! # Header text
//!
//! TASK-0246 (cycle 38) updated the emitted Cargo.toml + run.sh
//! headers to the same neutral form TASK-0231 (cycle 32) established
//! for main.rs: `# Generated by the nucleus pre-compiler.` This
//! drops the stale "pthreads-sync backend" provenance lie now that
//! the templates live in `backend-common` and serve every single-
//! binary backend. The byte-identical differential between
//! pthreads-sync + pthreads-async still holds (both consume the
//! SAME helper, so their emitted Cargo.toml + run.sh are byte-equal
//! to each other modulo the per-cell scratch path, which the cross-
//! backend tests already strip).

/// Project-skeleton renderers for the SINGLE-BINARY tier-1 backends
/// (`pthreads-sync`, `pthreads-async`). Both emit one Cargo project
/// with one `[[bin]]` target named `nuc-generated`; the only
/// per-backend variation is the `main.rs` body, not the project
/// skeleton, so the templates are shared verbatim.
pub mod single_binary {
    /// Emit the standalone Cargo.toml the generated project ships.
    ///
    /// Shared by pthreads-sync + pthreads-async (TASK-0246). The
    /// `nuc-generated` binary name is deliberately backend-agnostic:
    /// the choice of single-binary backend only changes per-loop
    /// codegen, not the project skeleton.
    pub fn render_cargo_toml() -> String {
        String::from(
            "# Generated by the nucleus pre-compiler. Do not edit; rerun \
             `nucleus build` to regenerate.\n\
             [package]\n\
             name        = \"nuc-generated\"\n\
             version     = \"0.0.0\"\n\
             edition     = \"2021\"\n\
             publish     = false\n\
             \n\
             [workspace]\n\
             # Empty: this crate is standalone, not part of any parent workspace.\n\
             \n\
             [[bin]]\n\
             name = \"nuc-generated\"\n\
             path = \"src/main.rs\"\n\
             \n\
             [profile.release]\n\
             panic = \"abort\"\n",
        )
    }

    /// Emit the run.sh the generated project ships.
    ///
    /// Shared by pthreads-sync + pthreads-async (TASK-0246). Builds
    /// the release binary with `cargo build --release` then invokes
    /// `target/release/nuc-generated` with `NUC_INPUT_PATH` /
    /// `NUC_OUTPUT_PATH` env vars wired from the script's two
    /// positional args (default: `input.bin` / `output.bin`).
    pub fn render_run_sh() -> String {
        String::from(
            "#!/usr/bin/env bash\n\
             # Generated by the nucleus pre-compiler. Rerun `nucleus build` to regenerate.\n\
             # Usage: bash run.sh INPUT_BIN OUTPUT_BIN\n\
             set -euo pipefail\n\
             \n\
             here=\"$(cd -- \"$(dirname -- \"${BASH_SOURCE[0]}\")\" && pwd)\"\n\
             input_bin=\"${1:-input.bin}\"\n\
             output_bin=\"${2:-output.bin}\"\n\
             \n\
             (cd \"$here\" && cargo build --release --quiet)\n\
             \n\
             NUC_INPUT_PATH=\"$input_bin\" \\\n\
             NUC_OUTPUT_PATH=\"$output_bin\" \\\n\
             \"$here/target/release/nuc-generated\"\n",
        )
    }
}

#[cfg(test)]
mod tests {
    use super::single_binary::{render_cargo_toml, render_run_sh};

    /// The Cargo.toml header is the FIRST line emitted; the
    /// cross-backend byte-identical invariants
    /// (pthreads-async/tests/skeleton.rs,
    /// mp-tcp-bufsync/tests/pingpong.rs) depend on it being stable.
    /// TASK-0246 (cycle 38) updated the header from
    /// `# Generated by the pthreads-sync backend.` to the neutral
    /// `# Generated by the nucleus pre-compiler.` (same form
    /// TASK-0231 already established for main.rs); the assertion
    /// below pins the new form.
    #[test]
    fn cargo_toml_header_byte_stable() {
        let s = render_cargo_toml();
        assert!(
            s.starts_with("# Generated by the nucleus pre-compiler."),
            "Cargo.toml header drifted: {:?}",
            &s[..s.find('\n').unwrap_or(s.len())]
        );
    }

    /// Mirrors the Cargo.toml header test. The run.sh shebang +
    /// header are the first two lines.
    #[test]
    fn run_sh_header_byte_stable() {
        let s = render_run_sh();
        assert!(s.starts_with("#!/usr/bin/env bash\n"));
        assert!(
            s.contains("# Generated by the nucleus pre-compiler."),
            "run.sh header drifted"
        );
    }

    /// The Cargo.toml must declare exactly ONE [[bin]] target named
    /// `nuc-generated` pointing at `src/main.rs`. Backends choose
    /// single-binary vs multi-binary by selecting the template, not
    /// by post-processing the string.
    #[test]
    fn cargo_toml_emits_single_bin_target() {
        let s = render_cargo_toml();
        assert_eq!(s.matches("[[bin]]").count(), 1);
        assert!(s.contains("name = \"nuc-generated\""));
        assert!(s.contains("path = \"src/main.rs\""));
    }
}
