//! String templates for the generated `no_std` lib project (TASK-0047).
//!
//! These are EMBEDDED-SPECIFIC and deliberately NOT shared with
//! `backend_common::project_skeleton` (which renders std single/multi-
//! BINARY projects with `panic = "abort"` and a `[[bin]]` named
//! `nuc-generated`). A compile-only `no_std` LIB has a genuinely
//! different shape — `[lib]`, no `[[bin]]`, no `panic` profile (a lib
//! `cargo check` needs no panic strategy), no `run.sh` (nothing to run).
//! Forcing it through the shared single-binary template would be the
//! WRONG abstraction, not a reuse win.

/// The `NucleusShim` trait + `StubShim` impl emitted verbatim into
/// every generated lib (AC#2 / AC#3). Held as a constant so the test
/// suite can pin its exact shape and the M10 shim author has one
/// canonical reference for the trait surface.
///
/// The four methods (AC#2): `alloc_in_region` (reserve backing storage
/// in a named region — a TCM / shared-SRAM / SDRAM address on real
/// hardware), `dma_push` (enqueue a DMA descriptor draining a buffer to
/// a peripheral / peer), `dma_wait` (block until a DMA channel
/// completes), `irq_barrier` (an IRQ-completion control barrier). The
/// `StubShim` no-ops all four — compile-only (AC#3 / AC#6).
pub const NUCLEUS_SHIM_SRC: &str = "\
/// The hardware-abstraction trait the generated `no_std` code lowers
/// against. A per-MCU SHIM crate (M10+, TASK-0048) implements this with
/// real DMA descriptors, IRQ vector binding, and memory-region
/// addresses; the M9 `StubShim` below no-ops every method (compile-only,
/// no real hardware — PRD \u{00A7}7.3 / \u{00A7}11 M9).
///
/// Design question (recorded for M10): the methods are presented as
/// SYNCHRONOUS (`dma_push` enqueues, `dma_wait` blocks). A real
/// async/IRQ-driven shim may prefer a completion-future or a callback;
/// that is an M10 design decision once a concrete MCU shim exists. M9
/// fixes the minimal blocking surface so the trait shape is stable.
pub trait NucleusShim {
    /// Reserve `bytes` of backing storage in memory `region` (a
    /// backend-opaque region handle). Returns a raw pointer to the
    /// region; the stub returns null (compile-only).
    fn alloc_in_region(&mut self, region: usize, bytes: usize) -> *mut u8;
    /// Enqueue a DMA transfer of `len` bytes from `src` on channel
    /// `chan` (drain a buffer to a peripheral / peer).
    fn dma_push(&mut self, chan: usize, src: *const u8, len: usize);
    /// Block until DMA channel `chan` has completed.
    fn dma_wait(&mut self, chan: usize);
    /// An IRQ-completion control barrier identified by `tag`. Unused by
    /// the single-worker examples 1 + 5 (no `Event::Sync` in a naive
    /// schedule); declared for the M10/M11 multi-MCU barrier surface.
    fn irq_barrier(&mut self, tag: u32);
}

/// Do-nothing shim satisfying [`NucleusShim`] — the M9 compile-only
/// target (AC#3). No DMA, no IRQ, no real timing (AC#6): every method
/// is a no-op, so the generated `run` compiles and executes on
/// zero-filled input arrays.
pub struct StubShim;

impl NucleusShim for StubShim {
    fn alloc_in_region(&mut self, _region: usize, _bytes: usize) -> *mut u8 {
        core::ptr::null_mut()
    }
    fn dma_push(&mut self, _chan: usize, _src: *const u8, _len: usize) {}
    fn dma_wait(&mut self, _chan: usize) {}
    fn irq_barrier(&mut self, _tag: u32) {}
}
";

/// Assemble the full `src/lib.rs`: header + trait/stub + `mod kernels`
/// (the verbatim pure bodies) + `run<S>`.
///
/// `kernel_defs` is the already-extracted pure kernel fn text (may be
/// empty for a program with no pure compute kernel). `run_body` is the
/// rendered body of `fn run<S: NucleusShim>(shim: &mut S)`.
pub fn render_lib(kernel_defs: &str, run_body: &str) -> String {
    let mut s = String::new();
    s.push_str(
        "//! Generated by the nucleus pre-compiler (embedded-pattern, M9).\n\
         //! Do not edit; rerun `nucleus build` to regenerate.\n\
         //!\n\
         //! A `no_std` compile-only lib (PRD \u{00A7}7.3 / \u{00A7}11 M9). The pure\n\
         //! compute kernels are copied verbatim from the source kernels.rs;\n\
         //! the effectful I/O kernels are lowered to `NucleusShim` hooks.\n\
         #![no_std]\n\
         #![allow(unused_mut, dead_code, unused_variables)]\n\
         \n",
    );
    s.push_str(NUCLEUS_SHIM_SRC);
    s.push('\n');
    // The pure kernel bodies live in a private `mod kernels` — the same
    // `kernels::<name>(..)` call spelling the run body emits.
    s.push_str("/// Pure compute kernels, copied verbatim from the source\n");
    s.push_str("/// kernels.rs (PRD \u{00A7}6.2.2: Nucleus does not interpolate kernel\n");
    s.push_str("/// bodies). The effectful I/O kernels are NOT here — they map to\n");
    s.push_str("/// `NucleusShim` hooks in `run` below.\n");
    s.push_str("mod kernels {\n");
    // Indent the extracted defs by 4 spaces so they sit inside the mod.
    for line in kernel_defs.lines() {
        if line.is_empty() {
            s.push('\n');
        } else {
            s.push_str("    ");
            s.push_str(line);
            s.push('\n');
        }
    }
    s.push_str("}\n\n");
    // The entry point: a generic `run` over any `NucleusShim`.
    s.push_str(
        "/// Lower the single-worker event list. Generic over any\n\
         /// [`NucleusShim`]; M9 ships the do-nothing [`StubShim`] so\n\
         /// `cargo check --target thumbv7em-none-eabihf` validates the\n\
         /// shape without real hardware.\n\
         pub fn run<S: NucleusShim>(shim: &mut S) {\n",
    );
    s.push_str(run_body);
    s.push_str("}\n");
    s
}

/// The generated project's `Cargo.toml`: a standalone `no_std` LIB
/// crate. No `[[bin]]`, no `panic` profile (a lib needs neither for
/// `cargo check`), no external deps. `edition = "2021"` matches the
/// pinned 1.83.0 toolchain (flake.nix `rustChannel`).
pub fn render_cargo_toml() -> String {
    String::from(
        "# Generated by the nucleus pre-compiler (embedded-pattern, M9). Do not edit; \
         rerun `nucleus build` to regenerate.\n\
         [package]\n\
         name        = \"nuc-embedded-generated\"\n\
         version     = \"0.0.0\"\n\
         edition     = \"2021\"\n\
         publish     = false\n\
         \n\
         [workspace]\n\
         # Empty: this crate is standalone, not part of any parent workspace.\n\
         \n\
         [lib]\n\
         name = \"nuc_embedded_generated\"\n\
         path = \"src/lib.rs\"\n",
    )
}

// --------------------------------------------------------------------
// M10 (TASK-0048.01) bin-emit templates — the Renode-runnable no_std
// BINARY shape. ADDITIVE: these are SEPARATE functions from the M9 lib
// templates above; the lib path (render_cargo_toml / render_lib) is
// UNCHANGED. The bin shape is the OPPOSITE of the lib in every honest
// respect (it HAS a [[bin]], a panic profile, a panic_handler, a
// cortex-m-rt entry, a linker script) — so the docs here state the bin
// facts, NOT the lib facts (feedback-verbatim-copy-comment-doc-lie).
//
// These mirror the PROVEN hand-written template at
// tests/renode/uart-smoke/ (commits b57d030 + 7de02f9), verified
// end-to-end in Renode by the cycle-237b review gate. The register
// addresses + bits below are the SAME ones the architect verified
// against the actual Renode STM32F7_USART.cs model source.

/// The `Usart1Shim` impl emitted into the generated BIN's `main.rs`
/// (M10, TASK-0048.01 / TASK-0048.02). This is the CONCRETE
/// [`NucleusShim`] the M9 `StubShim` no-ops:
///
/// - `alloc_in_region` IS the REAL input path (TASK-0048.02): it hands
///   back a pointer into the Renode-injected input region (axiSram @
///   0x2400_0000, where the `.resc` `sysbus LoadBinary @input.bin`s the
///   fixture) and advances an internal byte cursor by `bytes`. The load
///   lowering then copies those `bytes` into the data array (see lib.rs
///   `render_fire`'s effectful-input arm). Sequential loads (`a <--
///   load_input(); b <-- load_input_b()`) consume the region in order,
///   matching `input.bin`'s layout (a's N words then b's N words —
///   exactly the advancing offsets `kernels.rs::read_i32_le_slice`
///   uses, WITHOUT this backend parsing kernel bodies).
/// - `dma_push` IS the UART emission: it streams the `len` RAW bytes of
///   the drained output region (the `save_output(c)` effectful Fire
///   lowers to `shim.dma_push(0, c.as_ptr() as *const u8,
///   core::mem::size_of_val(&c)); shim.dma_wait(0)` — see lib.rs
///   `render_fire`) verbatim over USART1. The `renode-embedded-ex1`
///   recipe captures those bytes and `cmp`s them BYTE-EXACT against
///   `reference.bin` (PRD §10.3 point 3). Raw (not ASCII): a byte-exact
///   reference diff is the value-correctness bar, and Renode's USART
///   file backend captures raw bytes faithfully (proven in the
///   TASK-0048.02 de-risk: a hand firmware streamed c and the capture
///   was `cmp -s`-identical to reference.bin).
/// - `dma_wait` / `irq_barrier` are no-ops: the injection is synchronous
///   (the region is populated before the CPU starts), so there is
///   nothing to block on. Real async DMA/IRQ is parent TASK-0048 AC#1.
///
/// REGISTERS (STM32H7 USART1 @ 0x4001_1000; Renode UART.STM32F7_USART):
/// CR1 @ +0x00 (UE bit0, TE bit3), ISR @ +0x1C (TXE bit7), TDR @ +0x28.
/// Renode hardwires TXE=true (the TX poll never waits there; back-
/// pressure is UNVALIDATED — but the poll is the correct pattern, so we
/// emit it). CR1 = UE|TE enable IS load-bearing (the model DROPS bytes
/// if the transmitter is not enabled).
///
/// INPUT REGION: axiSram @ 0x2400_0000 (512K, mapped in the platform but
/// NOT in `memory.x`, so the firmware's stack/.bss never collide with
/// the injected fixture). The `.resc` injects the fixture there before
/// the CPU runs.
pub const USART1_SHIM_SRC: &str = "\
// STM32H7 USART1 — Renode models it as UART.STM32F7_USART @ 0x4001_1000
// (platforms/cpus/stm32h743.repl). Register layout (STM32F7/H7):
//   CR1 @ +0x00  (UE = bit 0, TE = bit 3)
//   ISR @ +0x1C  (TXE = bit 7: transmit data register empty)
//   TDR @ +0x28  (transmit data register)
const USART1_CR1: *mut u32 = 0x4001_1000 as *mut u32;
const USART1_ISR: *const u32 = 0x4001_101C as *const u32;
const USART1_TDR: *mut u32 = 0x4001_1028 as *mut u32;
const USART1_TXE: u32 = 1 << 7;

// The Renode-injected input region: axiSram @ 0x2400_0000 (mapped in the
// stm32h743 platform, NOT in memory.x — so the linker never places the
// stack/.bss here and the injected fixture is safe). The `.resc` does
// `sysbus LoadBinary @input.bin 0x2400_0000` BEFORE the CPU starts, so by
// the time `run` executes the bytes are already present (no DMA wait).
const NUC_INPUT_REGION: *const u8 = 0x2400_0000 as *const u8;

/// Push one byte out over USART1. Renode's STM32F7_USART hardwires
/// TXE=true so this poll never actually waits there; on real silicon it
/// blocks until the transmit register drains. The poll is the correct
/// pattern regardless.
fn usart1_putc(b: u8) {
    unsafe {
        while core::ptr::read_volatile(USART1_ISR) & USART1_TXE == 0 {}
        core::ptr::write_volatile(USART1_TDR, b as u32);
    }
}

/// The CONCRETE shim for the STM32H7 Renode target.
///
/// - `alloc_in_region` is the REAL input path: it returns a pointer into
///   the injected input region (`NUC_INPUT_REGION`) at the current cursor
///   and advances the cursor by `bytes`. Sequential loads consume the
///   region in order (matching `input.bin`'s array-concatenation layout).
/// - `dma_push` is the UART emission: it streams the `len` RAW bytes of
///   the drained region verbatim over USART1 (captured + `cmp`'d
///   byte-exact vs reference.bin by `just renode-embedded-ex1`).
/// - `dma_wait` / `irq_barrier` are no-ops (synchronous injection; real
///   DMA/IRQ is parent TASK-0048 AC#1).
struct Usart1Shim {
    // Byte offset into NUC_INPUT_REGION consumed so far. Each effectful
    // load advances it by the loaded array's byte length.
    input_cursor: usize,
}

impl Usart1Shim {
    fn new() -> Self {
        Usart1Shim { input_cursor: 0 }
    }
}

impl NucleusShim for Usart1Shim {
    fn alloc_in_region(&mut self, _region: usize, bytes: usize) -> *mut u8 {
        // Hand back the next `bytes`-sized slice of the injected input
        // region and advance the cursor. The load lowering copies from
        // this pointer into the data array. (Cast away const: the load
        // lowering only READS through it; mut is the trait's contract.)
        let p = unsafe { NUC_INPUT_REGION.add(self.input_cursor) } as *mut u8;
        self.input_cursor += bytes;
        p
    }
    fn dma_push(&mut self, _chan: usize, src: *const u8, len: usize) {
        // Stream the drained output region's RAW bytes verbatim over
        // USART1. The `renode-embedded-ex1` recipe captures these and
        // `cmp`s them BYTE-EXACT against reference.bin (PRD §10.3 point 3
        // value-correctness). `read_volatile` so the byte loads are not
        // reordered/elided across the MMIO writes in `usart1_putc`.
        let mut i = 0usize;
        while i < len {
            let byte = unsafe { core::ptr::read_volatile(src.add(i)) };
            usart1_putc(byte);
            i += 1;
        }
    }
    fn dma_wait(&mut self, _chan: usize) {}
    fn irq_barrier(&mut self, _tag: u32) {}
}
";

/// Assemble the full Renode-runnable `src/main.rs` for the BIN target
/// (M10, TASK-0048.01). Mirrors the proven template at
/// tests/renode/uart-smoke/src/main.rs: a single self-contained
/// `#![no_std]` / `#![no_main]` file with a cortex-m-rt `#[entry]`, a
/// `#[panic_handler]`, the `NucleusShim` trait + `StubShim` (verbatim
/// reuse of [`NUCLEUS_SHIM_SRC`] so the trait surface is IDENTICAL to
/// the lib path), `mod kernels` (the verbatim pure bodies), the lowered
/// `run<S>`, and the concrete [`USART1_SHIM_SRC`] `Usart1Shim`.
///
/// `kernel_defs` is the already-extracted pure kernel fn text. `run_body`
/// is the rendered body of `fn run<S: NucleusShim>(shim: &mut S)` — the
/// SAME body the lib path emits (the only difference between lib and bin
/// is the surrounding scaffolding, not the lowering).
pub fn render_bin_main(kernel_defs: &str, run_body: &str) -> String {
    let mut s = String::new();
    s.push_str(
        "//! Generated by the nucleus pre-compiler (embedded-pattern, M10 BIN).\n\
         //! Do not edit; rerun `nucleus build --shim stm32h7` to regenerate.\n\
         //!\n\
         //! A Renode-runnable `no_std` BIN for the STM32H7 (Cortex-M7).\n\
         //! Boots via cortex-m-rt, loads REAL input from the Renode-injected\n\
         //! region (axiSram @ 0x2400_0000), calls the lowered `run`, and the\n\
         //! effectful save Fire's `dma_push` streams the RAW output bytes\n\
         //! over USART1 (captured + diffed BYTE-EXACT vs reference.bin in\n\
         //! Renode). Mirrors tests/renode/uart-smoke/ (the proven M10 template).\n\
         #![no_std]\n\
         #![no_main]\n\
         #![allow(unused_mut, dead_code, unused_variables)]\n\
         \n\
         use core::panic::PanicInfo;\n\
         use cortex_m_rt::entry;\n\
         \n",
    );
    s.push_str(NUCLEUS_SHIM_SRC);
    s.push('\n');
    s.push_str(USART1_SHIM_SRC);
    s.push('\n');
    // The pure kernel bodies live in a private `mod kernels` — the same
    // `kernels::<name>(..)` call spelling the run body emits (identical
    // to the lib path).
    s.push_str("/// Pure compute kernels, copied verbatim from the source\n");
    s.push_str("/// kernels.rs (PRD \u{00A7}6.2.2: Nucleus does not interpolate kernel\n");
    s.push_str("/// bodies). The effectful I/O kernels are NOT here — they map to\n");
    s.push_str("/// `NucleusShim` hooks in `run` below.\n");
    s.push_str("mod kernels {\n");
    for line in kernel_defs.lines() {
        if line.is_empty() {
            s.push('\n');
        } else {
            s.push_str("    ");
            s.push_str(line);
            s.push('\n');
        }
    }
    s.push_str("}\n\n");
    // The lowered run — identical body to the lib path.
    s.push_str(
        "/// Lower the single-worker event list. Generic over any\n\
         /// [`NucleusShim`]; the BIN instantiates it with the concrete\n\
         /// `Usart1Shim` (whose `dma_push` IS the UART emission).\n\
         pub fn run<S: NucleusShim>(shim: &mut S) {\n",
    );
    s.push_str(run_body);
    s.push_str("}\n\n");
    // The cortex-m-rt entry point: enable USART1, build the concrete
    // shim, run, then spin. Inside `run` the load Fires fill the arrays
    // from the injected input region (via the shim) and the save Fire's
    // dma_push streams the RAW computed output bytes over USART1.
    s.push_str(
        "#[entry]\n\
         fn main() -> ! {\n    \
             unsafe {\n        \
                 // Enable the USART (UE = bit 0) and its transmitter (TE = bit 3).\n        \
                 // This enable IS load-bearing under Renode (the model drops bytes\n        \
                 // if the transmitter is not enabled).\n        \
                 core::ptr::write_volatile(USART1_CR1, (1 << 0) | (1 << 3));\n    \
             }\n    \
             let mut shim = Usart1Shim::new();\n    \
             run(&mut shim);\n    \
             loop {}\n\
         }\n\
         \n\
         #[panic_handler]\n\
         fn panic(_: &PanicInfo) -> ! {\n    \
             loop {}\n\
         }\n",
    );
    s
}

/// The generated BIN project's `Cargo.toml` (M10, TASK-0048.01). The
/// OPPOSITE of [`render_cargo_toml`]'s lib shape: it HAS a `[[bin]]`,
/// the `cortex-m-rt` dependency, and `panic = "abort"` profiles (a
/// runnable no_std bin needs all three — there is no unwinder on bare
/// metal). Standalone empty `[workspace]` so it is NOT pulled into the
/// nucleus/ cargo workspace (otherwise `just build` / `just ci` would
/// try to build ARM-only code on the host and fail). Mirrors
/// tests/renode/uart-smoke/Cargo.toml.
pub fn render_bin_cargo_toml() -> String {
    String::from(
        "# Generated by the nucleus pre-compiler (embedded-pattern, M10 BIN). Do not edit; \
         rerun `nucleus build --shim stm32h7` to regenerate.\n\
         [package]\n\
         name        = \"nuc-embedded-generated\"\n\
         version     = \"0.0.0\"\n\
         edition     = \"2021\"\n\
         publish     = false\n\
         \n\
         [[bin]]\n\
         name = \"nuc-embedded-generated\"\n\
         path = \"src/main.rs\"\n\
         \n\
         [dependencies]\n\
         cortex-m-rt = \"0.7\"\n\
         \n\
         [profile.dev]\n\
         panic = \"abort\"\n\
         \n\
         [profile.release]\n\
         panic = \"abort\"\n\
         \n\
         [workspace]\n\
         # Empty: this crate is standalone, not part of any parent workspace\n\
         # (it cross-compiles only for thumbv7em-none-eabihf).\n",
    )
}

/// The STM32H743 `memory.x` linker fragment (M10, TASK-0048.01).
/// Mirrors tests/renode/uart-smoke/memory.x EXACTLY: 128K FLASH @
/// 0x08000000, 128K RAM @ 0x20000000 (the FULL DTCM). DO NOT raise RAM
/// past 128K without mapping a larger region (axiSram @ 0x24000000), or
/// the stack would silently overflow DTCM with no linker error.
pub fn render_memory_x() -> String {
    String::from(
        "/* STM32H743 memory map (from Renode platforms/cpus/stm32h743.repl):\n\
        \x20  flashBank1 @ 0x08000000 (size 0x100000 = 1024K) and DTCM @ 0x20000000\n\
        \x20  (size 0x20000 = 128K). FLASH here is a strict subset (128K of 1024K).\n\
        \x20  RAM here is the FULL DTCM (128K == 0x20000) — do NOT raise RAM LENGTH\n\
        \x20  past 128K without mapping a larger region (e.g. axiSram @ 0x24000000),\n\
        \x20  or the stack would silently overflow DTCM with no linker error. */\n\
        MEMORY\n\
        {\n\
        \x20 FLASH : ORIGIN = 0x08000000, LENGTH = 128K\n\
        \x20 RAM   : ORIGIN = 0x20000000, LENGTH = 128K\n\
        }\n",
    )
}

/// The generated BIN's `build.rs` (M10, TASK-0048.01). Puts `memory.x`
/// on the linker search path so cortex-m-rt's `link.x` finds it.
/// Mirrors tests/renode/uart-smoke/build.rs.
pub fn render_build_rs() -> String {
    String::from(
        "// Put memory.x on the linker search path so cortex-m-rt's link.x finds it.\n\
        use std::env;\n\
        use std::fs;\n\
        use std::path::PathBuf;\n\
        \n\
        fn main() {\n    \
            let out = PathBuf::from(env::var(\"OUT_DIR\").unwrap());\n    \
            fs::write(out.join(\"memory.x\"), include_bytes!(\"memory.x\")).unwrap();\n    \
            println!(\"cargo:rustc-link-search={}\", out.display());\n    \
            println!(\"cargo:rerun-if-changed=memory.x\");\n    \
            println!(\"cargo:rerun-if-changed=build.rs\");\n\
        }\n",
    )
}

/// The generated BIN's `.cargo/config.toml` (M10, TASK-0048.01).
/// Defaults the target to thumbv7em-none-eabihf and links via
/// cortex-m-rt's bundled `link.x`. Mirrors
/// tests/renode/uart-smoke/.cargo/config.toml.
pub fn render_cargo_config() -> String {
    String::from(
        "# cortex-m-rt links via its bundled link.x (which pulls in memory.x from\n\
        # the build-script search path). Default the target so a bare `cargo\n\
        # build` cross-compiles for the Cortex-M7.\n\
        [target.thumbv7em-none-eabihf]\n\
        rustflags = [\"-C\", \"link-arg=-Tlink.x\"]\n\
        \n\
        [build]\n\
        target = \"thumbv7em-none-eabihf\"\n",
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn cargo_toml_is_a_lib_not_a_bin() {
        let s = render_cargo_toml();
        assert!(s.contains("[lib]"), "embedded Cargo.toml must declare [lib]");
        assert!(
            !s.contains("[[bin]]"),
            "embedded Cargo.toml must NOT declare a [[bin]] — compile-only no_std lib"
        );
        assert!(
            !s.contains("panic"),
            "a no_std lib needs no panic profile for cargo check"
        );
    }

    #[test]
    fn shim_trait_declares_all_four_methods() {
        // AC#2: the four shim methods are present in the canonical
        // trait source.
        for m in [
            "fn alloc_in_region",
            "fn dma_push",
            "fn dma_wait",
            "fn irq_barrier",
        ] {
            assert!(
                NUCLEUS_SHIM_SRC.contains(m),
                "NucleusShim trait missing method {m}"
            );
        }
        assert!(
            NUCLEUS_SHIM_SRC.contains("struct StubShim"),
            "StubShim impl missing"
        );
    }

    #[test]
    fn render_lib_emits_no_std_and_run() {
        let s = render_lib("pub fn add(a: i32, b: i32) -> i32 { a }\n", "    // body\n");
        assert!(s.starts_with("//! Generated by the nucleus pre-compiler"));
        assert!(s.contains("#![no_std]"));
        assert!(s.contains("pub trait NucleusShim"));
        assert!(s.contains("mod kernels {"));
        // The kernel def is indented inside the mod.
        assert!(s.contains("    pub fn add(a: i32, b: i32) -> i32 { a }"));
        assert!(s.contains("pub fn run<S: NucleusShim>(shim: &mut S) {"));
    }

    // ---- M10 (TASK-0048.01) bin-emit template tests ----

    #[test]
    fn render_bin_cargo_toml_is_a_runnable_bin() {
        // The bin shape is the OPPOSITE of the lib: it HAS a [[bin]], a
        // cortex-m-rt dep, and panic=abort profiles, and is its own
        // empty [workspace].
        let s = render_bin_cargo_toml();
        assert!(s.contains("[[bin]]"), "bin Cargo.toml must declare [[bin]]");
        assert!(
            s.contains("cortex-m-rt = \"0.7\""),
            "bin Cargo.toml must depend on cortex-m-rt 0.7"
        );
        assert!(
            s.contains("[profile.dev]") && s.contains("[profile.release]"),
            "bin Cargo.toml must set panic=abort on both profiles"
        );
        assert!(
            s.matches("panic = \"abort\"").count() == 2,
            "panic=abort must appear on both profiles"
        );
        assert!(
            s.contains("[workspace]"),
            "bin Cargo.toml must be its own empty [workspace] (isolation)"
        );
        assert!(
            !s.contains("[lib]"),
            "bin Cargo.toml must NOT declare [lib]"
        );
    }

    #[test]
    fn render_bin_main_is_a_runnable_firmware() {
        let s = render_bin_main(
            "pub fn add(a: i32, b: i32) -> i32 { a.wrapping_add(b) }\n",
            "    let mut c: [i32; 256] = [0; 256];\n",
        );
        // no_std / no_main firmware header.
        assert!(s.contains("#![no_std]"), "bin main must be no_std");
        assert!(s.contains("#![no_main]"), "bin main must be no_main");
        // cortex-m-rt entry + panic handler (a runnable bin needs both;
        // the lib has NEITHER — keep the docs honest per class).
        assert!(s.contains("use cortex_m_rt::entry;"), "missing cortex-m-rt import");
        assert!(s.contains("#[entry]"), "missing #[entry]");
        assert!(s.contains("#[panic_handler]"), "missing #[panic_handler]");
        // The SAME trait surface as the lib (verbatim reuse).
        assert!(s.contains("pub trait NucleusShim"), "trait missing");
        assert!(s.contains("struct StubShim"), "StubShim missing (verbatim reuse)");
        // The concrete USART1 shim — its dma_push IS the UART emission.
        assert!(s.contains("struct Usart1Shim"), "Usart1Shim missing");
        assert!(
            s.contains("impl NucleusShim for Usart1Shim"),
            "Usart1Shim must impl NucleusShim"
        );
        // TASK-0048.02: dma_push streams RAW output bytes (the byte-exact
        // reference.bin diff is the value-correctness bar); the old ASCII
        // summary framing (NUC-EX1 / checksum) is GONE.
        assert!(
            s.contains("usart1_putc(byte);"),
            "dma_push must stream raw output bytes over USART1"
        );
        assert!(!s.contains("NUC-EX1"), "ASCII summary framing must be GONE");
        assert!(!s.contains("checksum="), "ASCII checksum framing must be GONE");
        // TASK-0048.02: the shim reads REAL input from the injected region.
        assert!(
            s.contains("const NUC_INPUT_REGION: *const u8 = 0x2400_0000 as *const u8;"),
            "shim must read injected input from axiSram @ 0x2400_0000"
        );
        assert!(
            s.contains("input_cursor"),
            "shim must track an input cursor across sequential loads"
        );
        // USART1 registers exactly as the proven template.
        assert!(s.contains("0x4001_1000"), "USART1_CR1 address");
        assert!(s.contains("0x4001_101C"), "USART1_ISR address");
        assert!(s.contains("0x4001_1028"), "USART1_TDR address");
        // main enables the USART then calls run.
        assert!(s.contains("fn main() -> !"), "missing entry main");
        assert!(s.contains("let mut shim = Usart1Shim::new();"), "main must build the shim");
        assert!(s.contains("run(&mut shim);"), "main must call run");
        // The kernel def is indented inside mod kernels (same as lib).
        assert!(s.contains("    pub fn add(a: i32, b: i32) -> i32 { a.wrapping_add(b) }"));
        assert!(s.contains("pub fn run<S: NucleusShim>(shim: &mut S) {"));
    }

    #[test]
    fn memory_x_pins_128k_flash_and_ram() {
        let s = render_memory_x();
        assert!(s.contains("ORIGIN = 0x08000000, LENGTH = 128K"), "FLASH region");
        assert!(s.contains("ORIGIN = 0x20000000, LENGTH = 128K"), "RAM region");
    }

    #[test]
    fn build_rs_and_cargo_config_target_thumbv7em() {
        let b = render_build_rs();
        assert!(b.contains("memory.x"), "build.rs must wire memory.x");
        assert!(b.contains("rustc-link-search"), "build.rs must add link search");
        let c = render_cargo_config();
        assert!(
            c.contains("[target.thumbv7em-none-eabihf]"),
            "config must target thumbv7em-none-eabihf"
        );
        assert!(c.contains("-Tlink.x"), "config must link via link.x");
    }
}
