//! String templates for the generated `no_std` lib project (TASK-0047).
//!
//! These are EMBEDDED-SPECIFIC and deliberately NOT shared with
//! `backend_common::project_skeleton` (which renders std single/multi-
//! BINARY projects with `panic = "abort"` and a `[[bin]]` named
//! `nuc-generated`). A compile-only `no_std` LIB has a genuinely
//! different shape — `[lib]`, no `[[bin]]`, no `panic` profile (a lib
//! `cargo check` needs no panic strategy), no `run.sh` (nothing to run).
//! Forcing it through the shared single-binary template would be the
//! WRONG abstraction, not a reuse win.

/// The `NucleusShim` trait + `StubShim` impl emitted verbatim into
/// every generated lib (AC#2 / AC#3). Held as a constant so the test
/// suite can pin its exact shape and the M10 shim author has one
/// canonical reference for the trait surface.
///
/// The four methods (AC#2): `alloc_in_region` (reserve backing storage
/// in a named region — a TCM / shared-SRAM / SDRAM address on real
/// hardware), `dma_push` (enqueue a DMA descriptor draining a buffer to
/// a peripheral / peer), `dma_wait` (block until a DMA channel
/// completes), `irq_barrier` (an IRQ-completion control barrier). The
/// `StubShim` no-ops all four — compile-only (AC#3 / AC#6).
pub const NUCLEUS_SHIM_SRC: &str = "\
/// The hardware-abstraction trait the generated `no_std` code lowers
/// against. A per-MCU SHIM crate (M10+, TASK-0048) implements this with
/// real DMA descriptors, IRQ vector binding, and memory-region
/// addresses; the M9 `StubShim` below no-ops every method (compile-only,
/// no real hardware — PRD \u{00A7}7.3 / \u{00A7}11 M9).
///
/// Design question (recorded for M10): the methods are presented as
/// SYNCHRONOUS (`dma_push` enqueues, `dma_wait` blocks). A real
/// async/IRQ-driven shim may prefer a completion-future or a callback;
/// that is an M10 design decision once a concrete MCU shim exists. M9
/// fixes the minimal blocking surface so the trait shape is stable.
pub trait NucleusShim {
    /// Reserve `bytes` of backing storage in memory `region` (a
    /// backend-opaque region handle). Returns a raw pointer to the
    /// region; the stub returns null (compile-only).
    fn alloc_in_region(&mut self, region: usize, bytes: usize) -> *mut u8;
    /// Enqueue a DMA transfer of `len` bytes from `src` on channel
    /// `chan` (drain a buffer to a peripheral / peer).
    fn dma_push(&mut self, chan: usize, src: *const u8, len: usize);
    /// Block until DMA channel `chan` has completed.
    fn dma_wait(&mut self, chan: usize);
    /// An IRQ-completion control barrier identified by `tag`. Unused by
    /// the single-worker examples 1 + 5 (no `Event::Sync` in a naive
    /// schedule); declared for the M10/M11 multi-MCU barrier surface.
    fn irq_barrier(&mut self, tag: u32);
}

/// Do-nothing shim satisfying [`NucleusShim`] — the M9 compile-only
/// target (AC#3). No DMA, no IRQ, no real timing (AC#6): every method
/// is a no-op, so the generated `run` compiles and executes on
/// zero-filled input arrays.
pub struct StubShim;

impl NucleusShim for StubShim {
    fn alloc_in_region(&mut self, _region: usize, _bytes: usize) -> *mut u8 {
        core::ptr::null_mut()
    }
    fn dma_push(&mut self, _chan: usize, _src: *const u8, _len: usize) {}
    fn dma_wait(&mut self, _chan: usize) {}
    fn irq_barrier(&mut self, _tag: u32) {}
}
";

/// Assemble the full `src/lib.rs`: header + trait/stub + `mod kernels`
/// (the verbatim pure bodies) + `run<S>`.
///
/// `kernel_defs` is the already-extracted pure kernel fn text (may be
/// empty for a program with no pure compute kernel). `run_body` is the
/// rendered body of `fn run<S: NucleusShim>(shim: &mut S)`.
pub fn render_lib(kernel_defs: &str, run_body: &str) -> String {
    let mut s = String::new();
    s.push_str(
        "//! Generated by the nucleus pre-compiler (embedded-pattern, M9).\n\
         //! Do not edit; rerun `nucleus build` to regenerate.\n\
         //!\n\
         //! A `no_std` compile-only lib (PRD \u{00A7}7.3 / \u{00A7}11 M9). The pure\n\
         //! compute kernels are copied verbatim from the source kernels.rs;\n\
         //! the effectful I/O kernels are lowered to `NucleusShim` hooks.\n\
         #![no_std]\n\
         #![allow(unused_mut, dead_code, unused_variables)]\n\
         \n",
    );
    s.push_str(NUCLEUS_SHIM_SRC);
    s.push('\n');
    // The pure kernel bodies live in a private `mod kernels` — the same
    // `kernels::<name>(..)` call spelling the run body emits.
    s.push_str("/// Pure compute kernels, copied verbatim from the source\n");
    s.push_str("/// kernels.rs (PRD \u{00A7}6.2.2: Nucleus does not interpolate kernel\n");
    s.push_str("/// bodies). The effectful I/O kernels are NOT here — they map to\n");
    s.push_str("/// `NucleusShim` hooks in `run` below.\n");
    s.push_str("mod kernels {\n");
    // Indent the extracted defs by 4 spaces so they sit inside the mod.
    for line in kernel_defs.lines() {
        if line.is_empty() {
            s.push('\n');
        } else {
            s.push_str("    ");
            s.push_str(line);
            s.push('\n');
        }
    }
    s.push_str("}\n\n");
    // The entry point: a generic `run` over any `NucleusShim`.
    s.push_str(
        "/// Lower the single-worker event list. Generic over any\n\
         /// [`NucleusShim`]; M9 ships the do-nothing [`StubShim`] so\n\
         /// `cargo check --target thumbv7em-none-eabihf` validates the\n\
         /// shape without real hardware.\n\
         pub fn run<S: NucleusShim>(shim: &mut S) {\n",
    );
    s.push_str(run_body);
    s.push_str("}\n");
    s
}

/// The generated project's `Cargo.toml`: a standalone `no_std` LIB
/// crate. No `[[bin]]`, no `panic` profile (a lib needs neither for
/// `cargo check`), no external deps. `edition = "2021"` matches the
/// pinned 1.83.0 toolchain (flake.nix `rustChannel`).
pub fn render_cargo_toml() -> String {
    String::from(
        "# Generated by the nucleus pre-compiler (embedded-pattern, M9). Do not edit; \
         rerun `nucleus build` to regenerate.\n\
         [package]\n\
         name        = \"nuc-embedded-generated\"\n\
         version     = \"0.0.0\"\n\
         edition     = \"2021\"\n\
         publish     = false\n\
         \n\
         [workspace]\n\
         # Empty: this crate is standalone, not part of any parent workspace.\n\
         \n\
         [lib]\n\
         name = \"nuc_embedded_generated\"\n\
         path = \"src/lib.rs\"\n",
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn cargo_toml_is_a_lib_not_a_bin() {
        let s = render_cargo_toml();
        assert!(s.contains("[lib]"), "embedded Cargo.toml must declare [lib]");
        assert!(
            !s.contains("[[bin]]"),
            "embedded Cargo.toml must NOT declare a [[bin]] — compile-only no_std lib"
        );
        assert!(
            !s.contains("panic"),
            "a no_std lib needs no panic profile for cargo check"
        );
    }

    #[test]
    fn shim_trait_declares_all_four_methods() {
        // AC#2: the four shim methods are present in the canonical
        // trait source.
        for m in [
            "fn alloc_in_region",
            "fn dma_push",
            "fn dma_wait",
            "fn irq_barrier",
        ] {
            assert!(
                NUCLEUS_SHIM_SRC.contains(m),
                "NucleusShim trait missing method {m}"
            );
        }
        assert!(
            NUCLEUS_SHIM_SRC.contains("struct StubShim"),
            "StubShim impl missing"
        );
    }

    #[test]
    fn render_lib_emits_no_std_and_run() {
        let s = render_lib("pub fn add(a: i32, b: i32) -> i32 { a }\n", "    // body\n");
        assert!(s.starts_with("//! Generated by the nucleus pre-compiler"));
        assert!(s.contains("#![no_std]"));
        assert!(s.contains("pub trait NucleusShim"));
        assert!(s.contains("mod kernels {"));
        // The kernel def is indented inside the mod.
        assert!(s.contains("    pub fn add(a: i32, b: i32) -> i32 { a }"));
        assert!(s.contains("pub fn run<S: NucleusShim>(shim: &mut S) {"));
    }
}
