//! The [`WirePrimitives`] trait — the single axis of variation between
//! the two sync-TCP multi-process backends that consume the shared
//! [`super::Plan`] substrate.
//!
//! # Why this trait exists
//!
//! `mp-tcp-bufsync` (blocking `recv`) and `mp-tcp-poll` (nonblocking
//! poll + `yield_now`) emit byte-identical multi-process projects
//! EXCEPT at a tiny, enumerable set of sites:
//!
//! 1. the three emitted wire-call expressions — `read_msg_expect`,
//!    `write_msg`, `barrier_cross` (poll appends `_poll` to each);
//! 2. an extra `wire::apply_nonblocking(&sock);` line per opened
//!    socket (poll only);
//! 3. the emitted per-worker file-header provenance line (backend
//!    name + originating task tag);
//! 4. the emitted host-relay banner comment block (genuinely
//!    different prose between the two);
//! 5. the `run.sh` SO_BUF commentary block;
//! 6. the compiler-time `EmitError::ContractGap` message prefix
//!    (this is NOT emitted into generated code — it is a codegen-time
//!    diagnostic — but it carries the backend name and is unit-pinned).
//!
//! Everything else (host election, xfer registry, slice-paste tile
//! derivation, accumulator classification, FIFO-shape hazards, the
//! entire event walk and worker-program assembly) is identical, so it
//! lives ONCE in [`super`] and the per-backend crate supplies only a
//! `WirePrimitives` impl.
//!
//! # All methods are associated (no `self`)
//!
//! Every variation is a pure function of its string arguments, so the
//! trait carries associated consts + associated functions only. The
//! generic [`super::Plan`] therefore needs no `W` value — it carries a
//! `PhantomData<fn() -> W>` and dispatches through `W::method(..)`.
//! All calls monomorphise; the abstraction is zero-cost.
//!
//! # Building call strings STRUCTURALLY (not by textual replace)
//!
//! Each `*_call` method MUST build its `wire::...(...)` expression from
//! its arguments directly. It must NEVER take a pre-rendered blocking
//! call string and `String::replace` a substring into the poll form:
//! sibling identifiers contain the primitive names as substrings
//! (`read_msg_expect` is a prefix of `read_msg_expect_poll`), so a
//! textual replace is the recurring `feedback-textual-replace-codegen-
//! unsafe` defect. The impls in each backend crate build the string
//! with a single `format!` over the components.

/// Per-backend wire-primitive variation for the shared sync-TCP
/// multi-process [`super::Plan`] substrate. See the module docstring
/// for the complete enumeration of variation sites and the
/// build-structurally contract.
pub trait WirePrimitives {
    /// Backend name as it appears in compiler-time
    /// `EmitError::ContractGap` diagnostics (e.g. `"mp-tcp-bufsync"`).
    /// NOT emitted into generated code.
    const BACKEND_NAME: &'static str;

    /// Backend name as it appears in the EMITTED per-worker file-header
    /// `//! Generated by the {FILE_HEADER_BACKEND} backend (...)` line.
    /// Usually equal to [`Self::BACKEND_NAME`] but kept distinct so the
    /// emitted-text contract and the diagnostic contract are separate
    /// degrees of freedom.
    const FILE_HEADER_BACKEND: &'static str;

    /// Originating-task tag in the EMITTED per-worker file-header
    /// `(... {FILE_HEADER_TASK}, multi-process)` clause
    /// (e.g. `"TASK-0036"` / `"TASK-0044.02.02"`).
    const FILE_HEADER_TASK: &'static str;

    /// The emitted `wire::read_msg_expect[...](&mut {cv}, {seq})`
    /// expression (no trailing `;`, no comment, no leading pad).
    /// `cv` is the already-rendered connection-variable name; `seq` is
    /// the `SeqTag`'s u64 value.
    fn read_msg_expect_call(cv: &str, seq: u64) -> String;

    /// The emitted `wire::write_msg[...](&mut {cv}, {seq}, &{enc})`
    /// expression. `enc` is the already-rendered encode expression
    /// (without the leading `&`).
    fn write_msg_call(cv: &str, seq: u64, enc: &str) -> String;

    /// The emitted `wire::barrier_cross[...](&mut {cv}, {bid})`
    /// expression. `cv` is the already-rendered control-channel
    /// variable; `bid` is the `SyncTag`'s u64 value.
    fn barrier_cross_call(cv: &str, bid: u64) -> String;

    /// An optional extra setup line emitted immediately after
    /// `wire::apply_sock_buf(&{sock});`. `None` for a blocking backend;
    /// `Some("wire::apply_nonblocking(&{sock});")` for a poll backend.
    /// The returned string is the bare statement (no leading pad — the
    /// caller adds the four-space indent).
    fn sock_setup_extra(sock: &str) -> Option<String>;

    /// The `run.sh` SO_BUF commentary block interpolated by
    /// `backend_common::project_skeleton::multi_binary::render_run_sh_multi`.
    fn so_buf_comment() -> &'static str;

    /// The EMITTED host-relay banner comment block, indented to `pad`
    /// (a string of spaces). Genuinely different prose between the two
    /// backends; supplied wholesale per backend so the emitted bytes
    /// stay exactly as each backend ships them today. Must NOT include
    /// a trailing newline (the caller's `writeln!` adds it).
    fn relay_banner(pad: &str) -> String;
}
