//! The [`EventTransport`] trait — the single axis of variation between
//! the two async event-reactor multi-process backends that consume the
//! shared [`super::Plan`] substrate.
//!
//! # Why this trait exists
//!
//! `mp-tcp-event` (TCP loopback) and `mp-uds-event` (Unix domain
//! sockets) emit byte-identical multi-process projects EXCEPT at a
//! tiny, enumerable set of transport-specific sites:
//!
//! 1. the emitted per-worker file-header provenance line (backend name
//!    + transport wording);
//! 2. the CTRL std-stream type spelled in the emitted barrier-shim
//!    struct fields (`std::net::TcpStream` vs
//!    `std::os::unix::net::UnixStream`);
//! 3. the DATA mio-stream type spelled in the reactor's `peers` Vec
//!    (`mio::net::TcpStream` vs `mio::net::UnixStream`);
//! 4. the role-specific `use` imports (TCP needs `std::fs` +
//!    `std::io::Write` for the port-in-file rendezvous; UDS uses the
//!    socket path itself so it needs neither);
//! 5. the rendezvous handshake + DATA/CTRL socket setup block (the big
//!    one): TCP binds `127.0.0.1:0` per worker and publishes the
//!    OS-assigned port to a rendezvous file (tmp + rename, TOCTOU-safe);
//!    UDS binds a `UnixListener` per worker at well-known
//!    `<wname>.{data,ctrl}.sock` paths and the non-host worker connects
//!    those paths directly (path-as-rendezvous);
//! 6. the `run.sh` post-processing (UDS swaps the shared template's
//!    `$here`-rooted rendezvous dir for a `/tmp`-rooted `mktemp -d` to
//!    fit the UDS `sun_path` 104-byte cap; TCP uses the shared template
//!    directly);
//! 7. the `run.sh` SO_BUF commentary block;
//! 8. the compiler-time `EmitError::ContractGap` message prefix (this
//!    is NOT emitted into generated code — it is a codegen-time
//!    diagnostic — but it carries the backend name and is unit-pinned).
//!
//! Everything else (host election, chan-id assignment, per-pair
//! capacity lookup, peer-index routing, barrier participant analysis,
//! the host-relay phase, the per-worker event walk via the shared
//! `multi_worker_walker`, accumulator classification, FIFO-shape
//! hazards) is identical, so it lives ONCE in [`super`] and the
//! per-backend crate supplies only an `EventTransport` impl.
//!
//! # All methods are associated (no `self`)
//!
//! Every variation is a pure function of its string arguments, so the
//! trait carries associated consts + associated functions only. The
//! generic [`super::Plan`] therefore needs no `T` value — it carries a
//! `PhantomData<fn() -> T>` and dispatches through `T::method(..)`.
//! All calls monomorphise; the abstraction is zero-cost.
//!
//! # Building emit strings STRUCTURALLY (not by textual replace)
//!
//! Each emit method MUST build its output string from its arguments
//! directly (a single `format!` / `writeln!` over the components). It
//! must NEVER take a pre-rendered string and `String::replace` a
//! transport substring into it: sibling identifiers contain the
//! transport names as substrings (`mio::net::TcpStream` is a substring
//! of nothing here, but `data_<name>` / `ctrl_<name>` variable names
//! and the `Stream`/`Listener` type spellings are easy to collide), so
//! a textual replace is the recurring
//! `feedback-textual-replace-codegen-unsafe` defect. The one sanctioned
//! exception is [`EventTransport::render_run_sh_post`], which swaps a
//! FIXED multi-line shell-script literal block (not a rendered Rust
//! expression, zero sibling-substring risk) and is annotated at the
//! call site; see its docstring.

use crate::EmitError;

/// Per-backend transport variation for the shared async event-reactor
/// multi-process [`super::Plan`] substrate. See the module docstring
/// for the complete enumeration of variation sites and the
/// build-structurally contract.
pub trait EventTransport {
    /// Backend name as it appears in compiler-time
    /// `EmitError::ContractGap` diagnostics (e.g. `"mp-tcp-event"`).
    /// NOT emitted into generated code, but unit-pinned by each
    /// backend's negative-path tests.
    const BACKEND_NAME: &'static str;

    /// The emitted per-worker file-header PREFIX — everything up to and
    /// including the `).` that closes the parenthetical, e.g.
    /// `"//! Generated by the mp-tcp-event backend (TASK-0042.05, \
    /// multi-process)."`. The caller appends the SHARED suffix
    /// `" Worker \`{wname}\`{role}."` structurally (the worker name +
    /// role suffix are identical between the two backends). The TCP and
    /// UDS prefixes genuinely differ (TASK-0042.05 vs TASK-0044.03.01,
    /// and the UDS line adds "over Unix domain sockets"), so the prefix
    /// is supplied wholesale per backend rather than decomposed into a
    /// backend-name + task-tag pair.
    const FILE_HEADER_PREFIX: &'static str;

    /// CTRL-channel std-stream type as spelled in the emitted
    /// barrier-shim struct fields and the non-host `ctrl_host` binding
    /// (`std::net::TcpStream` vs `std::os::unix::net::UnixStream`).
    const CTRL_STD_STREAM_TY: &'static str;

    /// DATA-channel mio-stream type as spelled in the reactor's `peers`
    /// Vec element type (`mio::net::TcpStream` vs
    /// `mio::net::UnixStream`).
    const DATA_MIO_STREAM_TY: &'static str;

    /// The `run.sh` SO_BUF commentary block interpolated by
    /// `backend_common::project_skeleton::multi_binary::render_run_sh_multi`
    /// before the `export NUC_SO_BUF=...` line.
    const SO_BUF_COMMENT: &'static str;

    /// Emit the role-specific `use` imports block (the lines between the
    /// `mod runtime;` block and the `use std::cell::RefCell;` /
    /// `use std::rc::Rc;` shared pair). Genuinely diverges: the TCP
    /// port-in-file rendezvous needs `std::fs` + (host) `std::io::Write`
    /// plus the TCP listener/stream types; the UDS path-as-rendezvous
    /// needs neither `fs` nor `io::Write`, only the UDS listener/stream
    /// types. The caller emits the shared `RefCell` / `Rc` imports +
    /// trailing blank line itself, so this method emits ONLY the
    /// transport-specific lines (no trailing blank line). Built
    /// structurally per backend; no textual replace.
    fn emit_role_imports(out: &mut String, is_host: bool);

    /// Emit the rendezvous handshake + DATA/CTRL socket setup block
    /// (the big transport-divergent block). Supplied WHOLESALE per
    /// backend — a method that returns the backend's exact current
    /// block verbatim is BETTER than a clever unification that shifts
    /// one byte (the acceptance oracle is byte-identity, not elegance).
    ///
    /// Built structurally from its args: `wname` is this worker's name,
    /// `is_host` its role, `non_host_names` the host's per-worker server
    /// list (host-side only; empty/unused for the non-host arm). No
    /// `Plan` dependency — the transport block resolves entirely in the
    /// GENERATED crate.
    ///
    /// Postconditions (shared contract both impls satisfy): for the
    /// host arm, every non-host worker `nwn` gets a `data_{nwn}` mio
    /// stream plus a `ctrl_{nwn}: Rc<RefCell<{CTRL_STD_STREAM_TY}>>`
    /// binding in scope. For the non-host arm, a `data_host` mio stream
    /// plus a `ctrl_host: Rc<RefCell<{CTRL_STD_STREAM_TY}>>` binding.
    /// The reactor and barrier-shim emit in [`super`] depend on these
    /// names.
    fn emit_handshake(out: &mut String, wname: &str, is_host: bool, non_host_names: &[String]);

    /// Post-process the `run.sh` rendered by the shared
    /// `multi_binary::render_run_sh_multi`. The TCP backend returns it
    /// unchanged; the UDS backend swaps the shared template's
    /// `$here`-rooted rendezvous-dir block for a `/tmp`-rooted
    /// `mktemp -d` so the UDS `sun_path` 104-byte cap is respected on
    /// the e2e harness's deep scratch hierarchy (see memory
    /// `project-uds-path-cap-rendezvous`). The UDS impl fails LOUD with
    /// a typed `EmitError::ContractGap` if the shared template's
    /// rendezvous block changes shape so the swap misses (rather than
    /// silently shipping a cap-busting path).
    fn render_run_sh_post(shared: String) -> Result<String, EmitError>;
}
