//! The [`MpiRendezvous`] trait — the single axis of variation between
//! the two SPMD MPI backends that consume the shared [`super::Plan`]
//! substrate.
//!
//! # Why this trait exists
//!
//! `mpi-blocking` (blocking `MPI_Send`/`MPI_Recv`) and `mpi-nonblocking`
//! (buffered `MPI_Ibsend` + `MPI_Mprobe`/`MPI_Imrecv`/`MPI_Wait`) emit
//! byte-identical SPMD multi-worker programs EXCEPT at a tiny,
//! enumerable set of sites:
//!
//! 1. the backend name in compiler-time `EmitError` diagnostics
//!    (`"mpi-blocking"` / `"mpi-nonblocking"`); this is ALSO the
//!    backend-name token in the emitted file-header line and the
//!    `mpiexec -n N` rank-count `eprintln!`;
//! 2. the emitted file-header dispatch-banner lines describing the
//!    `Push`/`Wait` lowering (`blocking MPI Send/Recv` vs `buffered
//!    MPI_Ibsend` + `MPI_Imrecv/Irecv`); genuinely different prose;
//! 3. the emitted rendezvous + barrier wrapper-type prelude — the
//!    `VecChan`/`ScalarChan`/`WorldBar`/`SubcommBar` source whose
//!    `.push()`/`.wait()` the shared walker targets (blocking send/recv
//!    bodies vs buffered `Ibsend` + `request::scope`d `Wait` bodies; the
//!    `WorldBar`/`SubcommBar` barrier wrappers are byte-identical
//!    between the two backends);
//! 4. the emitted `Universe` init block: the blocking backend takes
//!    `world` directly (`let universe = mpi::initialize()...`); the
//!    buffered backend takes `&mut universe`, attaches an `MPI_Bsend`
//!    buffer (`set_buffer_size`, sized from the schedule footprint with
//!    an `NUC_MPI_BSEND_BYTES` override), THEN takes `world`.
//!
//! Everything else (host election, rank assignment, channel-id
//! collection, barrier participant analysis incl. the
//! whole-world-vs-`MPI_Comm_split` sub-comm-barrier classification, the
//! check-frame loud reject, the single-producer/single-consumer
//! guard, the entire `render_worker_events` walk, pre-init, accumulator
//! classification) is identical, so it lives ONCE in [`super::Plan`]
//! and the per-backend crate supplies only an `MpiRendezvous` impl.
//!
//! # Methods are mostly associated (no `self`)
//!
//! Every variation is a pure function of its (string/usize) arguments,
//! so the trait carries associated consts + associated functions only.
//! The generic [`super::Plan`] therefore needs no `W` value — it carries
//! a `PhantomData<fn() -> W>` and dispatches through `W::method(..)`.
//! All calls monomorphise; the abstraction is zero-cost.

/// Per-backend MPI-rendezvous variation for the shared SPMD multi-worker
/// [`super::Plan`] substrate. See the module docstring for the complete
/// enumeration of variation sites.
pub trait MpiRendezvous {
    /// Backend name as it appears in compiler-time `EmitError`
    /// diagnostics (`"mpi-blocking"` / `"mpi-nonblocking"`) AND as the
    /// backend-name token in the emitted file-header line and the
    /// rank-count `eprintln!`. The emitted-text and diagnostic uses
    /// coincide for both MPI backends today, so one const serves both.
    const BACKEND_NAME: &'static str;

    /// Emit the file-header dispatch-banner lines (the `//! ...
    /// Push/Wait => ...` block) describing this backend's lowering. The
    /// caller has already emitted the leading `//! Generated by ...`,
    /// `//! Do not edit ...`, `//!`, and `//! SPMD: one binary ...
    /// branches on` lines; this method appends the lines from
    /// `` //! `world.rank()`. ... `` through the launch line
    /// (`` //! ... Launch: `mpiexec -n {n}`. ``), one `writeln!` per
    /// line. `n` is the used-worker / rank count.
    fn write_header_dispatch_lines(out: &mut String, n: usize);

    /// The emitted rendezvous + barrier wrapper-type prelude: the
    /// `VecChan`/`ScalarChan`/`WorldBar` source whose `.push()`/`.wait()`
    /// the shared walker targets. Returned WITHOUT a trailing newline;
    /// the caller pushes the prelude then a single `'\n'` (matching the
    /// pre-lift emit byte-for-byte).
    fn prelude() -> &'static str;

    /// Emit the `Universe` init block — the lines from
    /// `let [mut] universe = mpi::initialize()...` through
    /// `let world = universe.world();` inclusive, each already padded to
    /// the `fn main` body indent (four spaces). `bsend_bytes` is the
    /// shared [`super::Plan::bsend_bytes`] heuristic value, consulted
    /// ONLY by the buffered backend (which emits the `MPI_Bsend` buffer
    /// attach); the blocking backend ignores it.
    fn write_universe_init(out: &mut String, bsend_bytes: usize);
}
